INSERT INTO NormalizedPerson (name) VALUES ('Abiel P Mead');
INSERT INTO NormalizedPerson (name) VALUES ('Abraham Armstrong');
INSERT INTO NormalizedPerson (name) VALUES ("Abrm Alley");
INSERT INTO NormalizedPerson (name) VALUES ('A C Ainsworth');
INSERT INTO NormalizedPerson (name) VALUES ("A. Carnahan");
INSERT INTO NormalizedPerson (name) VALUES ("A. C. Buckner");
INSERT INTO NormalizedPerson (name) VALUES ("Achilles McPharlan");
INSERT INTO NormalizedPerson (name) VALUES ('Adam Trinno');
INSERT INTO NormalizedPerson (name) VALUES ("A. Erwin Groce");
INSERT INTO NormalizedPerson (name) VALUES ("Africans");
INSERT INTO NormalizedPerson (name) VALUES ('A Holdridge');
INSERT INTO NormalizedPerson (name) VALUES ('Ahumada');
INSERT INTO NormalizedPerson (name) VALUES ("A. J. Yates");
INSERT INTO NormalizedPerson (name) VALUES ("Alabamos");
INSERT INTO NormalizedPerson (name) VALUES ('Albert Gallatin');
INSERT INTO NormalizedPerson (name) VALUES ('Alcade of San Felipe');
INSERT INTO NormalizedPerson (name) VALUES ('Alcalde');
INSERT INTO NormalizedPerson (name) VALUES ('Alcalde of San Felipe');
INSERT INTO NormalizedPerson (name) VALUES ("Alexander Kilpatrick");
INSERT INTO NormalizedPerson (name) VALUES ('Alex McNair');
INSERT INTO NormalizedPerson (name) VALUES ('Alijah Hull');
INSERT INTO NormalizedPerson (name) VALUES ("Allen White");
INSERT INTO NormalizedPerson (name) VALUES ('A. McNair');
INSERT INTO NormalizedPerson (name) VALUES ('Amos Rawls');
INSERT INTO NormalizedPerson (name) VALUES ('Anastacio Bustamante');
INSERT INTO NormalizedPerson (name) VALUES ("Andrew L Phinney");
INSERT INTO NormalizedPerson (name) VALUES ("Andrew Roach");
INSERT INTO NormalizedPerson (name) VALUES ("Andrew Valentine");
INSERT INTO NormalizedPerson (name) VALUES ("Andrw Boggs");
INSERT INTO NormalizedPerson (name) VALUES ("Anthony Butler");
INSERT INTO NormalizedPerson (name) VALUES ("Anthony R. Clarke");
INSERT INTO NormalizedPerson (name) VALUES ("Anthony Soulard");
INSERT INTO NormalizedPerson (name) VALUES ("Anthony Winston");
INSERT INTO NormalizedPerson (name) VALUES ("Antonio Lopez Santa Anna");
INSERT INTO NormalizedPerson (name) VALUES ("Antonio Manches");
INSERT INTO NormalizedPerson (name) VALUES ("Apadachy Chief");
INSERT INTO NormalizedPerson (name) VALUES ('Archibald Austin');
INSERT INTO NormalizedPerson (name) VALUES ('Archilbald Austin');
INSERT INTO NormalizedPerson (name) VALUES ('Armistead Moore');
INSERT INTO NormalizedPerson (name) VALUES ('A. Sampyrac');
INSERT INTO NormalizedPerson (name) VALUES ("Austin and Tailer");
INSERT INTO NormalizedPerson (name) VALUES ("Austin Elliott");
INSERT INTO NormalizedPerson (name) VALUES ('Authorities of La Bahia');
INSERT INTO NormalizedPerson (name) VALUES ("A. W. McLane");
INSERT INTO NormalizedPerson (name) VALUES ('Ayunatmiento of San Felipe');
INSERT INTO NormalizedPerson (name) VALUES ("Ayuntamiento of the Capital of the District");
INSERT INTO NormalizedPerson (name) VALUES ("Ayuntamiento of the Jurisdiction of Brazoria");
INSERT INTO NormalizedPerson (name) VALUES ("Ayuntamto of Bexar");
INSERT INTO NormalizedPerson (name) VALUES ('Bank of St Louis');
INSERT INTO NormalizedPerson (name) VALUES ("Baron Bastrop");
INSERT INTO NormalizedPerson (name) VALUES ("Bartlett Sims");
INSERT INTO NormalizedPerson (name) VALUES ("Benjamin Beeson");
INSERT INTO NormalizedPerson (name) VALUES ("Benjamin Carrico");
INSERT INTO NormalizedPerson (name) VALUES ("Benjamin Edwards");
INSERT INTO NormalizedPerson (name) VALUES ("Benjamin F. Smith");
INSERT INTO NormalizedPerson (name) VALUES ("Benjamin Ives Gilman");
INSERT INTO NormalizedPerson (name) VALUES ("Benjamin Long");
INSERT INTO NormalizedPerson (name) VALUES ("Benjani Johnston");
INSERT INTO NormalizedPerson (name) VALUES ('Ben J. Shakelford');
INSERT INTO NormalizedPerson (name) VALUES ("Ben R. Milam");
INSERT INTO NormalizedPerson (name) VALUES ("Bernardo Gutierris");
INSERT INTO NormalizedPerson (name) VALUES ('Bogart');
INSERT INTO NormalizedPerson (name) VALUES ('Branch T Archer');
INSERT INTO NormalizedPerson (name) VALUES ("Brigham");
INSERT INTO NormalizedPerson (name) VALUES ("Brother James");
INSERT INTO NormalizedPerson (name) VALUES ('Bryrd Lockhart, Green De Witt, James Kerr');
INSERT INTO NormalizedPerson (name) VALUES ('B T Jacques');
INSERT INTO NormalizedPerson (name) VALUES ("Burrill Thompson");
INSERT INTO NormalizedPerson (name) VALUES ('Bustamentes');
INSERT INTO NormalizedPerson (name) VALUES ("Caleb S Bostwick");
INSERT INTO NormalizedPerson (name) VALUES ("Captain A Robinson");
INSERT INTO NormalizedPerson (name) VALUES ("Captain Brown of Schr liberty");
INSERT INTO NormalizedPerson (name) VALUES ("Captain Ross");
INSERT INTO NormalizedPerson (name) VALUES ("Captains of the companies East of the Trinity");
INSERT INTO NormalizedPerson (name) VALUES ("Capt. A. Thompson");
INSERT INTO NormalizedPerson (name) VALUES ("Capt Barigan");
INSERT INTO NormalizedPerson (name) VALUES ("Capt. Brown");
INSERT INTO NormalizedPerson (name) VALUES ("Capt. Chrisman");
INSERT INTO NormalizedPerson (name) VALUES ("Capt DeWitt");
INSERT INTO NormalizedPerson (name) VALUES ("Capt. Dickson");
INSERT INTO NormalizedPerson (name) VALUES ("Capt Doons");
INSERT INTO NormalizedPerson (name) VALUES ("Capt. Fuller");
INSERT INTO NormalizedPerson (name) VALUES ("Capt Harris");
INSERT INTO NormalizedPerson (name) VALUES ("Capt Henry Austin");
INSERT INTO NormalizedPerson (name) VALUES ("Capt Hiram");
INSERT INTO NormalizedPerson (name) VALUES ('Captian Richard Fields');
INSERT INTO NormalizedPerson (name) VALUES ("Capt. James Bryant");
INSERT INTO NormalizedPerson (name) VALUES ("Capt. J. W. Fanning");
INSERT INTO NormalizedPerson (name) VALUES ("Captn Bird");
INSERT INTO NormalizedPerson (name) VALUES ("Captn Jones");
INSERT INTO NormalizedPerson (name) VALUES ("Capt Postlewhaite");
INSERT INTO NormalizedPerson (name) VALUES ("Capt. Saviego");
INSERT INTO NormalizedPerson (name) VALUES ('Carbajal''s Mother');
INSERT INTO NormalizedPerson (name) VALUES ('Carlos Garcia');
INSERT INTO NormalizedPerson (name) VALUES ('C. Dyer,David Hamilton, William Spence, Joseph Newman, Nicholas Whitehead, John Clark, Thomas J. Rabb, Charles Henderson, Moses Windham, William Luce, Alexander Brown, ANdrew Rabb, John Ingram, Gabriel Straw Snyder, Andrew Rabb');
INSERT INTO NormalizedPerson (name) VALUES ('Central Committee');
INSERT INTO NormalizedPerson (name) VALUES ('Chapman');
INSERT INTO NormalizedPerson (name) VALUES ("Charles Carr");
INSERT INTO NormalizedPerson (name) VALUES ("Charles Elliott");
INSERT INTO NormalizedPerson (name) VALUES ("Charles H. Burnett");
INSERT INTO NormalizedPerson (name) VALUES ("Cherokees");
INSERT INTO NormalizedPerson (name) VALUES ("Chickasaw Indian");
INSERT INTO NormalizedPerson (name) VALUES ("Choctaws");
INSERT INTO NormalizedPerson (name) VALUES ('Christian Wilt');
INSERT INTO NormalizedPerson (name) VALUES ('Churchill Fulshear');
INSERT INTO NormalizedPerson (name) VALUES ('Citizens of Jefferson County');
INSERT INTO NormalizedPerson (name) VALUES ('Citizens of Mina');
INSERT INTO NormalizedPerson (name) VALUES ("Col. Antonio Martinez");
INSERT INTO NormalizedPerson (name) VALUES ("Col. Bradburn");
INSERT INTO NormalizedPerson (name) VALUES ("Col. Butler");
INSERT INTO NormalizedPerson (name) VALUES ("Col. Bynum");
INSERT INTO NormalizedPerson (name) VALUES ("Col. Charles Morgan");
INSERT INTO NormalizedPerson (name) VALUES ("Col: John Thompson Mason");
INSERT INTO NormalizedPerson (name) VALUES ("Col. Langworthy");
INSERT INTO NormalizedPerson (name) VALUES ("Col. Macomb");
INSERT INTO NormalizedPerson (name) VALUES ("Coln. Nicholas");
INSERT INTO NormalizedPerson (name) VALUES ("Colo. Benjn F. Foster");
INSERT INTO NormalizedPerson (name) VALUES ("Colo. James Bowie");
INSERT INTO NormalizedPerson (name) VALUES ("Colo. Leftwitch");
INSERT INTO NormalizedPerson (name) VALUES ("Colo. Mathews");
INSERT INTO NormalizedPerson (name) VALUES ("Colonel Perry");
INSERT INTO NormalizedPerson (name) VALUES ('Colonists');
INSERT INTO NormalizedPerson (name) VALUES ('Colonists(');
INSERT INTO NormalizedPerson (name) VALUES ('Colonlists');
INSERT INTO NormalizedPerson (name) VALUES ('Colony');
INSERT INTO NormalizedPerson (name) VALUES ('Colorado District');
INSERT INTO NormalizedPerson (name) VALUES ("Col. Pitts");
INSERT INTO NormalizedPerson (name) VALUES ("Col Quarles");
INSERT INTO NormalizedPerson (name) VALUES ("Col. U");
INSERT INTO NormalizedPerson (name) VALUES ('Columbia Committee');
INSERT INTO NormalizedPerson (name) VALUES ("Col. W.");
INSERT INTO NormalizedPerson (name) VALUES ("Col: Wallace.");
INSERT INTO NormalizedPerson (name) VALUES ("Col: Wilson");
INSERT INTO NormalizedPerson (name) VALUES ('Comittee of Safety of San Felipe');
INSERT INTO NormalizedPerson (name) VALUES ('Committee at Convention');
INSERT INTO NormalizedPerson (name) VALUES ('Committee of Harrisburgh');
INSERT INTO NormalizedPerson (name) VALUES ('Committee of San Felipe');
INSERT INTO NormalizedPerson (name) VALUES ("Commodore Porter");
INSERT INTO NormalizedPerson (name) VALUES ('Congress');
INSERT INTO NormalizedPerson (name) VALUES ('Convention');
INSERT INTO NormalizedPerson (name) VALUES ('Conventional Committee');
INSERT INTO NormalizedPerson (name) VALUES ('Council of War');
INSERT INTO NormalizedPerson (name) VALUES ("Coushattas");
INSERT INTO NormalizedPerson (name) VALUES ("Couzen E Sharp");
INSERT INTO NormalizedPerson (name) VALUES ("Creek Indians");
INSERT INTO NormalizedPerson (name) VALUES ("Dalley");
INSERT INTO NormalizedPerson (name) VALUES ('Dan Bissell');
INSERT INTO NormalizedPerson (name) VALUES ('Dan Black');
INSERT INTO NormalizedPerson (name) VALUES ("Daniel Dunklin");
INSERT INTO NormalizedPerson (name) VALUES ("Daniel Holoway");
INSERT INTO NormalizedPerson (name) VALUES ('Darius Shaw');
INSERT INTO NormalizedPerson (name) VALUES ("David Bright");
INSERT INTO NormalizedPerson (name) VALUES ("David H. Milburn");
INSERT INTO NormalizedPerson (name) VALUES ("David McCormick");
INSERT INTO NormalizedPerson (name) VALUES ("David M. Collinsworh");
INSERT INTO NormalizedPerson (name) VALUES ('D C Barrett');
INSERT INTO NormalizedPerson (name) VALUES ('D. Crozer');
INSERT INTO NormalizedPerson (name) VALUES ('Dexter C. Gunn and David Bucklin');
INSERT INTO NormalizedPerson (name) VALUES ("D. G. and R Mills");
INSERT INTO NormalizedPerson (name) VALUES ("D. G. Burnett");
INSERT INTO NormalizedPerson (name) VALUES ('Dillard');
INSERT INTO NormalizedPerson (name) VALUES ('District of Bravo settlers');
INSERT INTO NormalizedPerson (name) VALUES ("Dn Alexdro TreviÃ±o");
INSERT INTO NormalizedPerson (name) VALUES ("Doct Elliott");
INSERT INTO NormalizedPerson (name) VALUES ("Doct. Keep");
INSERT INTO NormalizedPerson (name) VALUES ("Doctor Beales");
INSERT INTO NormalizedPerson (name) VALUES ("Doctor Farrar");
INSERT INTO NormalizedPerson (name) VALUES ("Doctor Joseph Bowers");
INSERT INTO NormalizedPerson (name) VALUES ("Doct. Pollard");
INSERT INTO NormalizedPerson (name) VALUES ("Doctr Hoxey");
INSERT INTO NormalizedPerson (name) VALUES ("Doctr Robertson");
INSERT INTO NormalizedPerson (name) VALUES ("Doctr Sibly");
INSERT INTO NormalizedPerson (name) VALUES ('Document not sent');
INSERT INTO NormalizedPerson (name) VALUES ("Domingo de Ugartechea");
INSERT INTO NormalizedPerson (name) VALUES ("Don Felipe de la Garza");
INSERT INTO NormalizedPerson (name) VALUES ("Don Pedro Lemus");
INSERT INTO NormalizedPerson (name) VALUES ("Douglass Forsythe");
INSERT INTO NormalizedPerson (name) VALUES ("Dudley R Tinker");
INSERT INTO NormalizedPerson (name) VALUES ('Duff Chadwell');
INSERT INTO NormalizedPerson (name) VALUES ("D. W. Anthony");
INSERT INTO NormalizedPerson (name) VALUES ('Ebel Miton,Ranford Berry, F. Smith, Wm. H Smith, John Teal, and Thomas ?');
INSERT INTO NormalizedPerson (name) VALUES ("E Brooke");
INSERT INTO NormalizedPerson (name) VALUES ("Editor of the Nat. Gazette");
INSERT INTO NormalizedPerson (name) VALUES ("Edmund St John Hawkins");
INSERT INTO NormalizedPerson (name) VALUES ("Ed. Waller");
INSERT INTO NormalizedPerson (name) VALUES ("Edward Bates");
INSERT INTO NormalizedPerson (name) VALUES ("Edward Burleson");
INSERT INTO NormalizedPerson (name) VALUES ('Edwin L Pettit');
INSERT INTO NormalizedPerson (name) VALUES ("Elias A. Eliott");
INSERT INTO NormalizedPerson (name) VALUES ('Elias R Wightman');
INSERT INTO NormalizedPerson (name) VALUES ('Elias Wightman');
INSERT INTO NormalizedPerson (name) VALUES ("Eliza W. Austin");
INSERT INTO NormalizedPerson (name) VALUES ('Emigrants');
INSERT INTO NormalizedPerson (name) VALUES ('Enoch Brenson');
INSERT INTO NormalizedPerson (name) VALUES ('E R Wightman');
INSERT INTO NormalizedPerson (name) VALUES ('E. R. Wightman');
INSERT INTO NormalizedPerson (name) VALUES ('Falconer');
INSERT INTO NormalizedPerson (name) VALUES ('Faris and White');
INSERT INTO NormalizedPerson (name) VALUES ("F. Casey");
INSERT INTO NormalizedPerson (name) VALUES ('Federal Congress');
INSERT INTO NormalizedPerson (name) VALUES ("Felix Robertson");
INSERT INTO NormalizedPerson (name) VALUES ('Felix Trudeau');
INSERT INTO NormalizedPerson (name) VALUES ("Fernando Rodriguiz");
INSERT INTO NormalizedPerson (name) VALUES ("Francis Covoner");
INSERT INTO NormalizedPerson (name) VALUES ("Francisco x Eliguem");
INSERT INTO NormalizedPerson (name) VALUES ("Francis Murphy");
INSERT INTO NormalizedPerson (name) VALUES ("Francis Smith");
INSERT INTO NormalizedPerson (name) VALUES ("Francoise Janis");
INSERT INTO NormalizedPerson (name) VALUES ("Francois VallÃ©e");
INSERT INTO NormalizedPerson (name) VALUES ('Fran�ois Grapp');
INSERT INTO NormalizedPerson (name) VALUES ("Frano Pizarro Martinez");
INSERT INTO NormalizedPerson (name) VALUES ('Frederick Bates');
INSERT INTO NormalizedPerson (name) VALUES ('Freeman Pettus');
INSERT INTO NormalizedPerson (name) VALUES ("F. Smith");
INSERT INTO NormalizedPerson (name) VALUES ("F. Thorn");
INSERT INTO NormalizedPerson (name) VALUES ("Gail Borden Jr.");
INSERT INTO NormalizedPerson (name) VALUES ('G B Cotten');
INSERT INTO NormalizedPerson (name) VALUES ("G. B. Dameron");
INSERT INTO NormalizedPerson (name) VALUES ("G. Byrne");
INSERT INTO NormalizedPerson (name) VALUES ("G. Edwards");
INSERT INTO NormalizedPerson (name) VALUES ('general public');
INSERT INTO NormalizedPerson (name) VALUES ('General Public');
INSERT INTO NormalizedPerson (name) VALUES ('General William H Ashley');
INSERT INTO NormalizedPerson (name) VALUES ("Gen. Gains");
INSERT INTO NormalizedPerson (name) VALUES ("Genl. Arthur G. Wavell");
INSERT INTO NormalizedPerson (name) VALUES ("Genl. Cortazar");
INSERT INTO NormalizedPerson (name) VALUES ("Genl Filisola");
INSERT INTO NormalizedPerson (name) VALUES ("Genl. Guadalupe Victoria");
INSERT INTO NormalizedPerson (name) VALUES ("Genl. Howard");
INSERT INTO NormalizedPerson (name) VALUES ("Genl. Long");
INSERT INTO NormalizedPerson (name) VALUES ("Genl. Pedraza");
INSERT INTO NormalizedPerson (name) VALUES ("Genl Teran");
INSERT INTO NormalizedPerson (name) VALUES ("Genl. Zavalla");
INSERT INTO NormalizedPerson (name) VALUES ("Gen M B Lamar");
INSERT INTO NormalizedPerson (name) VALUES ("Gen. T. J. Rusk");
INSERT INTO NormalizedPerson (name) VALUES ("Geo and Edward Curtis");
INSERT INTO NormalizedPerson (name) VALUES ('Geo Huff');
INSERT INTO NormalizedPerson (name) VALUES ("Geo: P. Digges");
INSERT INTO NormalizedPerson (name) VALUES ("George Anne Hawkins");
INSERT INTO NormalizedPerson (name) VALUES ("George Fisher");
INSERT INTO NormalizedPerson (name) VALUES ("George Hammond");
INSERT INTO NormalizedPerson (name) VALUES ("George Harrison");
INSERT INTO NormalizedPerson (name) VALUES ("George Lauman");
INSERT INTO NormalizedPerson (name) VALUES ("George Orr");
INSERT INTO NormalizedPerson (name) VALUES ("George Robinson Jr");
INSERT INTO NormalizedPerson (name) VALUES ('George S. Pentacost');
INSERT INTO NormalizedPerson (name) VALUES ("George Sutherland");
INSERT INTO NormalizedPerson (name) VALUES ("George W Collier");
INSERT INTO NormalizedPerson (name) VALUES ("Geo. Tennell");
INSERT INTO NormalizedPerson (name) VALUES ('Gideon Blackburn');
INSERT INTO NormalizedPerson (name) VALUES ("Gilbert Legrass");
INSERT INTO NormalizedPerson (name) VALUES ("Gomez Farias");
INSERT INTO NormalizedPerson (name) VALUES ('Government of the Province of Texas');
INSERT INTO NormalizedPerson (name) VALUES ('Governor Martinez');
INSERT INTO NormalizedPerson (name) VALUES ('Governor of Coahuila');
INSERT INTO NormalizedPerson (name) VALUES ('Governor Viesca');
INSERT INTO NormalizedPerson (name) VALUES ("Govr. Trespalacios");
INSERT INTO NormalizedPerson (name) VALUES ('G. Pearce');
INSERT INTO NormalizedPerson (name) VALUES ('Green De Witt');
INSERT INTO NormalizedPerson (name) VALUES ("Griffin H. Hollimon,");
INSERT INTO NormalizedPerson (name) VALUES ("Guy M Bryan");
INSERT INTO NormalizedPerson (name) VALUES ('Hamiton N Yett and Alexr Calvit');
INSERT INTO NormalizedPerson (name) VALUES ("Hanker");
INSERT INTO NormalizedPerson (name) VALUES ('Hanson Alsbury');
INSERT INTO NormalizedPerson (name) VALUES ("Hardiman");
INSERT INTO NormalizedPerson (name) VALUES ('Hart');
INSERT INTO NormalizedPerson (name) VALUES ("Hary Elliot");
INSERT INTO NormalizedPerson (name) VALUES ('Heerl');
INSERT INTO NormalizedPerson (name) VALUES ('Henry Dodge');
INSERT INTO NormalizedPerson (name) VALUES ('Henry Morse');
INSERT INTO NormalizedPerson (name) VALUES ("Henry S Brown");
INSERT INTO NormalizedPerson (name) VALUES ("Henry Whiteside");
INSERT INTO NormalizedPerson (name) VALUES ('Henry W. Munson');
INSERT INTO NormalizedPerson (name) VALUES ("Heydens");
INSERT INTO NormalizedPerson (name) VALUES ("H. Fullerton");
INSERT INTO NormalizedPerson (name) VALUES ("H. H. League");
INSERT INTO NormalizedPerson (name) VALUES ('H. H. League, James C. Ludlow, Elias Wightman, Richard Matson.');
INSERT INTO NormalizedPerson (name) VALUES ('Hinton Curtis');
INSERT INTO NormalizedPerson (name) VALUES ("H. J. Offutt");
INSERT INTO NormalizedPerson (name) VALUES ("H. Johnson, Governor of the State of Louisiana.");
INSERT INTO NormalizedPerson (name) VALUES ("H. M.");
INSERT INTO NormalizedPerson (name) VALUES ("H. Meigs");
INSERT INTO NormalizedPerson (name) VALUES ('Horatio Alsberry');
INSERT INTO NormalizedPerson (name) VALUES ('Horatio Chriesman');
INSERT INTO NormalizedPerson (name) VALUES ("Hotchkiss");
INSERT INTO NormalizedPerson (name) VALUES ("Hugh Bradly");
INSERT INTO NormalizedPerson (name) VALUES ("Humphry Jackson");
INSERT INTO NormalizedPerson (name) VALUES ('Hyde');
INSERT INTO NormalizedPerson (name) VALUES ("I. Bledsoe");
INSERT INTO NormalizedPerson (name) VALUES ("I. F. Wells");
INSERT INTO NormalizedPerson (name) VALUES ("Ignacio de Arispe");
INSERT INTO NormalizedPerson (name) VALUES ("Imla Keep");
INSERT INTO NormalizedPerson (name) VALUES ('Inhabitants of Colony');
INSERT INTO NormalizedPerson (name) VALUES ('Inhabitants of Pecan Point');
INSERT INTO NormalizedPerson (name) VALUES ("Ira Lewis");
INSERT INTO NormalizedPerson (name) VALUES ('Ireston C. Devan');
INSERT INTO NormalizedPerson (name) VALUES ('Isaac C. Oglem');
INSERT INTO NormalizedPerson (name) VALUES ('Isaac Jesses');
INSERT INTO NormalizedPerson (name) VALUES ("Isaac Lewis Baker");
INSERT INTO NormalizedPerson (name) VALUES ('Israel McGready');
INSERT INTO NormalizedPerson (name) VALUES ('Israel Waters');
INSERT INTO NormalizedPerson (name) VALUES ("Isurael Massie");
INSERT INTO NormalizedPerson (name) VALUES ("Iturbide Emperor");
INSERT INTO NormalizedPerson (name) VALUES ('Jacob Betts');
INSERT INTO NormalizedPerson (name) VALUES ("James Austin");
INSERT INTO NormalizedPerson (name) VALUES ("James B. Baily");
INSERT INTO NormalizedPerson (name) VALUES ("James Bryan");
INSERT INTO NormalizedPerson (name) VALUES ("James Carr");
INSERT INTO NormalizedPerson (name) VALUES ("James Cox");
INSERT INTO NormalizedPerson (name) VALUES ("James E. Phelps");
INSERT INTO NormalizedPerson (name) VALUES ("James F Perry");
INSERT INTO NormalizedPerson (name) VALUES ("James Frazure");
INSERT INTO NormalizedPerson (name) VALUES ("James Gallagher");
INSERT INTO NormalizedPerson (name) VALUES ("James Hewitson");
INSERT INTO NormalizedPerson (name) VALUES ("James L. Curtis");
INSERT INTO NormalizedPerson (name) VALUES ("James Neelly");
INSERT INTO NormalizedPerson (name) VALUES ("James Nelson");
INSERT INTO NormalizedPerson (name) VALUES ("James Newell");
INSERT INTO NormalizedPerson (name) VALUES ("James Ross");
INSERT INTO NormalizedPerson (name) VALUES ("James Smith");
INSERT INTO NormalizedPerson (name) VALUES ("James Tong");
INSERT INTO NormalizedPerson (name) VALUES ("James Wilkinson");
INSERT INTO NormalizedPerson (name) VALUES ("Jas Brown");
INSERT INTO NormalizedPerson (name) VALUES ("Jas. Bruffey");
INSERT INTO NormalizedPerson (name) VALUES ("Jas Cummins");
INSERT INTO NormalizedPerson (name) VALUES ("Jas E. B. Austin");
INSERT INTO NormalizedPerson (name) VALUES ("Jas. P. Caldwell");
INSERT INTO NormalizedPerson (name) VALUES ("J.B.A");
INSERT INTO NormalizedPerson (name) VALUES ('J. B. Baley');
INSERT INTO NormalizedPerson (name) VALUES ('J. Blair');
INSERT INTO NormalizedPerson (name) VALUES ("J B Miller");
INSERT INTO NormalizedPerson (name) VALUES ('J. Botts');
INSERT INTO NormalizedPerson (name) VALUES ("J. Butler");
INSERT INTO NormalizedPerson (name) VALUES ('J. Cable');
INSERT INTO NormalizedPerson (name) VALUES ('J Child');
INSERT INTO NormalizedPerson (name) VALUES ('J. Child');
INSERT INTO NormalizedPerson (name) VALUES ("J. C. Ludlows");
INSERT INTO NormalizedPerson (name) VALUES ('J. D. Bludworth');
INSERT INTO NormalizedPerson (name) VALUES ("Jerret");
INSERT INTO NormalizedPerson (name) VALUES ('Jessee Grimes');
INSERT INTO NormalizedPerson (name) VALUES ('J. F. Buchetti');
INSERT INTO NormalizedPerson (name) VALUES ("J. Gamble");
INSERT INTO NormalizedPerson (name) VALUES ('J G Wright');
INSERT INTO NormalizedPerson (name) VALUES ("J H Bell");
INSERT INTO NormalizedPerson (name) VALUES ("J. H. H.");
INSERT INTO NormalizedPerson (name) VALUES ("J. H. Moore.");
INSERT INTO NormalizedPerson (name) VALUES ("J. H. Polly");
INSERT INTO NormalizedPerson (name) VALUES ('J. L. Dumanday');
INSERT INTO NormalizedPerson (name) VALUES ("J. Lester");
INSERT INTO NormalizedPerson (name) VALUES ('J. L Phillips');
INSERT INTO NormalizedPerson (name) VALUES ('J Mariano Guerra');
INSERT INTO NormalizedPerson (name) VALUES ("J. M. Pennington");
INSERT INTO NormalizedPerson (name) VALUES ("J. M. Wolfe");
INSERT INTO NormalizedPerson (name) VALUES ("Jno. Allcorn");
INSERT INTO NormalizedPerson (name) VALUES ("Jno. A. Williams");
INSERT INTO NormalizedPerson (name) VALUES ("Jno. C Walker");
INSERT INTO NormalizedPerson (name) VALUES ("Jno. E. Jones");
INSERT INTO NormalizedPerson (name) VALUES ("Jno. Rice Jones");
INSERT INTO NormalizedPerson (name) VALUES ("Jno. W Cole");
INSERT INTO NormalizedPerson (name) VALUES ("Joaquin de Arredondo");
INSERT INTO NormalizedPerson (name) VALUES ("John A. Merle");
INSERT INTO NormalizedPerson (name) VALUES ("John Andrews");
INSERT INTO NormalizedPerson (name) VALUES ("John A. Wharton");
INSERT INTO NormalizedPerson (name) VALUES ("John Crownover");
INSERT INTO NormalizedPerson (name) VALUES ("John Findly");
INSERT INTO NormalizedPerson (name) VALUES ("John Greig");
INSERT INTO NormalizedPerson (name) VALUES ("John H. Fowler");
INSERT INTO NormalizedPerson (name) VALUES ("John Hinkson");
INSERT INTO NormalizedPerson (name) VALUES ("John H. Money");
INSERT INTO NormalizedPerson (name) VALUES ("John Ingram");
INSERT INTO NormalizedPerson (name) VALUES ("John Kampf");
INSERT INTO NormalizedPerson (name) VALUES ("John Kenny");
INSERT INTO NormalizedPerson (name) VALUES ("John Linn");
INSERT INTO NormalizedPerson (name) VALUES ("John McArthur");
INSERT INTO NormalizedPerson (name) VALUES ('John McIntire');
INSERT INTO NormalizedPerson (name) VALUES ("John Moody");
INSERT INTO NormalizedPerson (name) VALUES ("John P. Austin.");
INSERT INTO NormalizedPerson (name) VALUES ("John P. Coles");
INSERT INTO NormalizedPerson (name) VALUES ("John Perry");
INSERT INTO NormalizedPerson (name) VALUES ("John P, Erwin");
INSERT INTO NormalizedPerson (name) VALUES ("John P. Hampton");
INSERT INTO NormalizedPerson (name) VALUES ('John P Sheldon');
INSERT INTO NormalizedPerson (name) VALUES ("John Q. Adams");
INSERT INTO NormalizedPerson (name) VALUES ("John S Bricky");
INSERT INTO NormalizedPerson (name) VALUES ('John Smith T');
INSERT INTO NormalizedPerson (name) VALUES ("Johnson Hunter");
INSERT INTO NormalizedPerson (name) VALUES ("John Sprowl");
INSERT INTO NormalizedPerson (name) VALUES ("Johns Taylor");
INSERT INTO NormalizedPerson (name) VALUES ("John Stuart");
INSERT INTO NormalizedPerson (name) VALUES ('John T Criswell');
INSERT INTO NormalizedPerson (name) VALUES ("John W Carr");
INSERT INTO NormalizedPerson (name) VALUES ("John W. Faulkner");
INSERT INTO NormalizedPerson (name) VALUES ("John W. Hall");
INSERT INTO NormalizedPerson (name) VALUES ("John Williams");
INSERT INTO NormalizedPerson (name) VALUES ("John W. Teten");
INSERT INTO NormalizedPerson (name) VALUES ("Jona. Taylor");
INSERT INTO NormalizedPerson (name) VALUES ("Jorge");
INSERT INTO NormalizedPerson (name) VALUES ("Jorge Anto Nixon Sind[ico]");
INSERT INTO NormalizedPerson (name) VALUES ("Jose Antonio Saucedo");
INSERT INTO NormalizedPerson (name) VALUES ("Joseph Callahan");
INSERT INTO NormalizedPerson (name) VALUES ("Joseph Dupong");
INSERT INTO NormalizedPerson (name) VALUES ("Joseph H. Hawkins");
INSERT INTO NormalizedPerson (name) VALUES ("Joseph Kuykendall");
INSERT INTO NormalizedPerson (name) VALUES ("Joseph M. D. Carbajal");
INSERT INTO NormalizedPerson (name) VALUES ("Joseph Rickey");
INSERT INTO NormalizedPerson (name) VALUES ("Joseph Seveson");
INSERT INTO NormalizedPerson (name) VALUES ("Joseph Stuart");
INSERT INTO NormalizedPerson (name) VALUES ("Joseph White");
INSERT INTO NormalizedPerson (name) VALUES ('Joshua Marsh');
INSERT INTO NormalizedPerson (name) VALUES ('Josiah H. Bell et al');
INSERT INTO NormalizedPerson (name) VALUES ("Jos. S. Johnston");
INSERT INTO NormalizedPerson (name) VALUES ("J. Pinckney Henderson");
INSERT INTO NormalizedPerson (name) VALUES ("J. Rankin");
INSERT INTO NormalizedPerson (name) VALUES ('J R Bedford');
INSERT INTO NormalizedPerson (name) VALUES ("J R. Nicholson");
INSERT INTO NormalizedPerson (name) VALUES ('J. Sargeant');
INSERT INTO NormalizedPerson (name) VALUES ("J. Thomas");
INSERT INTO NormalizedPerson (name) VALUES ("Juan Antonio Padilla");
INSERT INTO NormalizedPerson (name) VALUES ("Juan Davis Bradburn");
INSERT INTO NormalizedPerson (name) VALUES ('Juan Francicso Buchetti');
INSERT INTO NormalizedPerson (name) VALUES ("Juan Seguin");
INSERT INTO NormalizedPerson (name) VALUES ("Judge D. Martinez de Castro.");
INSERT INTO NormalizedPerson (name) VALUES ("Judge Murry Bullard");
INSERT INTO NormalizedPerson (name) VALUES ('Junta Gobernativa');
INSERT INTO NormalizedPerson (name) VALUES ('Junta Instituyente');
INSERT INTO NormalizedPerson (name) VALUES ("J. W. Collins");
INSERT INTO NormalizedPerson (name) VALUES ("J. W. F.");
INSERT INTO NormalizedPerson (name) VALUES ("J. W. Fannin, jr.");
INSERT INTO NormalizedPerson (name) VALUES ("J. W. Zacharie");
INSERT INTO NormalizedPerson (name) VALUES ('Knight and White');
INSERT INTO NormalizedPerson (name) VALUES ("Lafitte");
INSERT INTO NormalizedPerson (name) VALUES ('Lastraps');
INSERT INTO NormalizedPerson (name) VALUES ("L. C. Mason");
INSERT INTO NormalizedPerson (name) VALUES ('Legislature');
INSERT INTO NormalizedPerson (name) VALUES ('Leonidas W. Baker');
INSERT INTO NormalizedPerson (name) VALUES ("Leroy X Furguson");
INSERT INTO NormalizedPerson (name) VALUES ('Lieutenant Governor DeLassus');
INSERT INTO NormalizedPerson (name) VALUES ("Lipans");
INSERT INTO NormalizedPerson (name) VALUES ("L. Lessassier");
INSERT INTO NormalizedPerson (name) VALUES ("L. L. Veeders");
INSERT INTO NormalizedPerson (name) VALUES ("Louis Holloway");
INSERT INTO NormalizedPerson (name) VALUES ('Louisiana Advertiser');
INSERT INTO NormalizedPerson (name) VALUES ("L. R. Kenny");
INSERT INTO NormalizedPerson (name) VALUES ("Lt. Branom");
INSERT INTO NormalizedPerson (name) VALUES ("Lucas Alaman");
INSERT INTO NormalizedPerson (name) VALUES ("Luciano Garcia");
INSERT INTO NormalizedPerson (name) VALUES ("Luke Lesassier");
INSERT INTO NormalizedPerson (name) VALUES ("M A and Co");
INSERT INTO NormalizedPerson (name) VALUES ("Majr. Benjn. W Smith");
INSERT INTO NormalizedPerson (name) VALUES ("Majr. Burnett");
INSERT INTO NormalizedPerson (name) VALUES ("Majr Ira R. Lewis");
INSERT INTO NormalizedPerson (name) VALUES ("Majr Reynolds");
INSERT INTO NormalizedPerson (name) VALUES ("Manuel Allouri");
INSERT INTO NormalizedPerson (name) VALUES ("Maria Louise Veillon");
INSERT INTO NormalizedPerson (name) VALUES ("Martha Marple");
INSERT INTO NormalizedPerson (name) VALUES ("Martin de Leon");
INSERT INTO NormalizedPerson (name) VALUES ('Martin F Maher and Company');
INSERT INTO NormalizedPerson (name) VALUES ("Martin Perfecto de Cos");
INSERT INTO NormalizedPerson (name) VALUES ("Martins of Gonzales");
INSERT INTO NormalizedPerson (name) VALUES ('Mateo Ahumada');
INSERT INTO NormalizedPerson (name) VALUES ("Mathew Mullens");
INSERT INTO NormalizedPerson (name) VALUES ('Matthew G White');
INSERT INTO NormalizedPerson (name) VALUES ("M. Austin Bryan");
INSERT INTO NormalizedPerson (name) VALUES ("M. B. Nuckols");
INSERT INTO NormalizedPerson (name) VALUES ("McClenehan");
INSERT INTO NormalizedPerson (name) VALUES ("McCormack");
INSERT INTO NormalizedPerson (name) VALUES ('McCoy and Scanlan');
INSERT INTO NormalizedPerson (name) VALUES ("McDonald");
INSERT INTO NormalizedPerson (name) VALUES ("McFarling");
INSERT INTO NormalizedPerson (name) VALUES ("Mc Grady");
INSERT INTO NormalizedPerson (name) VALUES ("McKinney and Williams");
INSERT INTO NormalizedPerson (name) VALUES ('Members of Consultation');
INSERT INTO NormalizedPerson (name) VALUES ("M G. W. Treat");
INSERT INTO NormalizedPerson (name) VALUES ('Michael Hart');
INSERT INTO NormalizedPerson (name) VALUES ("Miguel Arciniega");
INSERT INTO NormalizedPerson (name) VALUES ("Miguel Ramos de Arispe");
INSERT INTO NormalizedPerson (name) VALUES ('Military Commandant');
INSERT INTO NormalizedPerson (name) VALUES ('Militia');
INSERT INTO NormalizedPerson (name) VALUES ('Missouri Legislature');
INSERT INTO NormalizedPerson (name) VALUES ('Missouri Territory Legislature');
INSERT INTO NormalizedPerson (name) VALUES ("Monroe Edwards");
INSERT INTO NormalizedPerson (name) VALUES ("Morgan A Heard");
INSERT INTO NormalizedPerson (name) VALUES ("Morgan L. Smith");
INSERT INTO NormalizedPerson (name) VALUES ("Moris Callahan");
INSERT INTO NormalizedPerson (name) VALUES ("Mosea Russaw");
INSERT INTO NormalizedPerson (name) VALUES ("Moses Austin");
INSERT INTO NormalizedPerson (name) VALUES ("Mr. Alexander Greaves");
INSERT INTO NormalizedPerson (name) VALUES ("Mr Alexander Somervill");
INSERT INTO NormalizedPerson (name) VALUES ("Mr Allen");
INSERT INTO NormalizedPerson (name) VALUES ("Mr. Almy");
INSERT INTO NormalizedPerson (name) VALUES ("Mr. and Mrs. Penniman");
INSERT INTO NormalizedPerson (name) VALUES ("Mr Andrew Robertson");
INSERT INTO NormalizedPerson (name) VALUES ("Mr Arnold");
INSERT INTO NormalizedPerson (name) VALUES ("Mr Atter");
INSERT INTO NormalizedPerson (name) VALUES ("Mr. Barker");
INSERT INTO NormalizedPerson (name) VALUES ("Mr. Bartholomeu");
INSERT INTO NormalizedPerson (name) VALUES ("Mr. Beard");
INSERT INTO NormalizedPerson (name) VALUES ("Mr Beardslee");
INSERT INTO NormalizedPerson (name) VALUES ("Mr. Bellier");
INSERT INTO NormalizedPerson (name) VALUES ("Mr Bent");
INSERT INTO NormalizedPerson (name) VALUES ("Mr B. Johnson");
INSERT INTO NormalizedPerson (name) VALUES ("Mr. Bolvan");
INSERT INTO NormalizedPerson (name) VALUES ("Mr B[ryan]");
INSERT INTO NormalizedPerson (name) VALUES ("Mr Burr");
INSERT INTO NormalizedPerson (name) VALUES ("Mr Cannings");
INSERT INTO NormalizedPerson (name) VALUES ("Mr. Caruthers");
INSERT INTO NormalizedPerson (name) VALUES ("Mr. Charles L. Bird");
INSERT INTO NormalizedPerson (name) VALUES ("Mr Charlton Hunt");
INSERT INTO NormalizedPerson (name) VALUES ("Mr Coldwell");
INSERT INTO NormalizedPerson (name) VALUES ("Mr Collett");
INSERT INTO NormalizedPerson (name) VALUES ("Mr. Colt");
INSERT INTO NormalizedPerson (name) VALUES ("Mr. Cook");
INSERT INTO NormalizedPerson (name) VALUES ("Mr Daniel Phelps");
INSERT INTO NormalizedPerson (name) VALUES ("Mr Dunn");
INSERT INTO NormalizedPerson (name) VALUES ("Mr. Durbin");
INSERT INTO NormalizedPerson (name) VALUES ("Mr Duty");
INSERT INTO NormalizedPerson (name) VALUES ("Mr. Eaton");
INSERT INTO NormalizedPerson (name) VALUES ("Mr. E. Comstock");
INSERT INTO NormalizedPerson (name) VALUES ("Mr Edward Hall");
INSERT INTO NormalizedPerson (name) VALUES ("Mr. Elijah Noble");
INSERT INTO NormalizedPerson (name) VALUES ("Mr Ellis");
INSERT INTO NormalizedPerson (name) VALUES ("Mr Fergusson");
INSERT INTO NormalizedPerson (name) VALUES ("Mr Fisher");
INSERT INTO NormalizedPerson (name) VALUES ("Mr. Francis W. Johnson");
INSERT INTO NormalizedPerson (name) VALUES ("Mr Fulcher");
INSERT INTO NormalizedPerson (name) VALUES ("Mr Furnash");
INSERT INTO NormalizedPerson (name) VALUES ("Mr Garrett");
INSERT INTO NormalizedPerson (name) VALUES ("Mr. G D Collier");
INSERT INTO NormalizedPerson (name) VALUES ("Mr. Givens");
INSERT INTO NormalizedPerson (name) VALUES ("Mr Grant");
INSERT INTO NormalizedPerson (name) VALUES ("Mr. Gregory");
INSERT INTO NormalizedPerson (name) VALUES ("Mr. Groce");
INSERT INTO NormalizedPerson (name) VALUES ("Mr. H.");
INSERT INTO NormalizedPerson (name) VALUES ("Mr Hail");
INSERT INTO NormalizedPerson (name) VALUES ("Mr Halliman");
INSERT INTO NormalizedPerson (name) VALUES ("Mr. Hays");
INSERT INTO NormalizedPerson (name) VALUES ("Mr Henry Clay");
INSERT INTO NormalizedPerson (name) VALUES ("Mr. Hope");
INSERT INTO NormalizedPerson (name) VALUES ("Mr Hopkins");
INSERT INTO NormalizedPerson (name) VALUES ("Mr. House");
INSERT INTO NormalizedPerson (name) VALUES ("Mr. Hugh Connell");
INSERT INTO NormalizedPerson (name) VALUES ("Mr Hugh McGuffen");
INSERT INTO NormalizedPerson (name) VALUES ("Mr. Hughs");
INSERT INTO NormalizedPerson (name) VALUES ("Mr. Iron");
INSERT INTO NormalizedPerson (name) VALUES ("Mr. James Brown");
INSERT INTO NormalizedPerson (name) VALUES ("Mr James Cole");
INSERT INTO NormalizedPerson (name) VALUES ("Mr. James McGarock, Senr");
INSERT INTO NormalizedPerson (name) VALUES ("Mr. James Shields");
INSERT INTO NormalizedPerson (name) VALUES ("Mr. J Durst");
INSERT INTO NormalizedPerson (name) VALUES ("Mr Joel Tatum");
INSERT INTO NormalizedPerson (name) VALUES ("Mr John Cummins");
INSERT INTO NormalizedPerson (name) VALUES ("Mr John Francis Merieult");
INSERT INTO NormalizedPerson (name) VALUES ("Mr John G Bond");
INSERT INTO NormalizedPerson (name) VALUES ("Mr. John Iiams");
INSERT INTO NormalizedPerson (name) VALUES ("Mr John M Henrie");
INSERT INTO NormalizedPerson (name) VALUES ("Mr. John R. Harris");
INSERT INTO NormalizedPerson (name) VALUES ("Mr John Staples");
INSERT INTO NormalizedPerson (name) VALUES ("Mr. Joseph Kent");
INSERT INTO NormalizedPerson (name) VALUES ("Mr. Joseph Powel");
INSERT INTO NormalizedPerson (name) VALUES ("Mr. Joshua Pilcher");
INSERT INTO NormalizedPerson (name) VALUES ("Mr. J. P. Fessenden");
INSERT INTO NormalizedPerson (name) VALUES ("Mr J. Pratt");
INSERT INTO NormalizedPerson (name) VALUES ("Mr J. W. Bredlove");
INSERT INTO NormalizedPerson (name) VALUES ("Mr Kenney");
INSERT INTO NormalizedPerson (name) VALUES ("Mr K Holliman");
INSERT INTO NormalizedPerson (name) VALUES ("Mr Lewis Morrison");
INSERT INTO NormalizedPerson (name) VALUES ("Mr. Livingston");
INSERT INTO NormalizedPerson (name) VALUES ("Mr. Marigney");
INSERT INTO NormalizedPerson (name) VALUES ("Mr. Mathew Adams");
INSERT INTO NormalizedPerson (name) VALUES ("Mr McConnell");
INSERT INTO NormalizedPerson (name) VALUES ("Mr McNeels");
INSERT INTO NormalizedPerson (name) VALUES ("Mr. Milligan");
INSERT INTO NormalizedPerson (name) VALUES ("Mr Mitchell");
INSERT INTO NormalizedPerson (name) VALUES ("Mr Morris");
INSERT INTO NormalizedPerson (name) VALUES ("Mr Moseley");
INSERT INTO NormalizedPerson (name) VALUES ("Mr Mosley Baker");
INSERT INTO NormalizedPerson (name) VALUES ("Mr Pack");
INSERT INTO NormalizedPerson (name) VALUES ("Mr. Parrott");
INSERT INTO NormalizedPerson (name) VALUES ('Mr Paskall');
INSERT INTO NormalizedPerson (name) VALUES ("Mr. Penneman");
INSERT INTO NormalizedPerson (name) VALUES ("Mr Penrose");
INSERT INTO NormalizedPerson (name) VALUES ("Mr. Perry");
INSERT INTO NormalizedPerson (name) VALUES ("Mr. Pilgram");
INSERT INTO NormalizedPerson (name) VALUES ("Mr. Ratliff");
INSERT INTO NormalizedPerson (name) VALUES ("Mr. Robert Le Roy");
INSERT INTO NormalizedPerson (name) VALUES ("Mr. Robidoux");
INSERT INTO NormalizedPerson (name) VALUES ("Mr. Robison");
INSERT INTO NormalizedPerson (name) VALUES ("Mr. Rogers");
INSERT INTO NormalizedPerson (name) VALUES ("Mr. S");
INSERT INTO NormalizedPerson (name) VALUES ("Mr. Samuel Carter");
INSERT INTO NormalizedPerson (name) VALUES ("Mr. Sanders");
INSERT INTO NormalizedPerson (name) VALUES ("Mrs Austen");
INSERT INTO NormalizedPerson (name) VALUES ("Mr. Sawyer");
INSERT INTO NormalizedPerson (name) VALUES ("Mr. Sayre");
INSERT INTO NormalizedPerson (name) VALUES ("Mrs Bell");
INSERT INTO NormalizedPerson (name) VALUES ("Mrs Berry");
INSERT INTO NormalizedPerson (name) VALUES ("Mrs Brady");
INSERT INTO NormalizedPerson (name) VALUES ("Mrs. C.");
INSERT INTO NormalizedPerson (name) VALUES ("Mrs Dickerson");
INSERT INTO NormalizedPerson (name) VALUES ("Mrs Eliza Page widow");
INSERT INTO NormalizedPerson (name) VALUES ("Mrs Elliott");
INSERT INTO NormalizedPerson (name) VALUES ("Mrs. Ellis");
INSERT INTO NormalizedPerson (name) VALUES ("Mrs. Emily M. Perry");
INSERT INTO NormalizedPerson (name) VALUES ("Mrs Estis");
INSERT INTO NormalizedPerson (name) VALUES ("Mrs Evens");
INSERT INTO NormalizedPerson (name) VALUES ("Mrs: Fisher");
INSERT INTO NormalizedPerson (name) VALUES ("Mrs. Grafton");
INSERT INTO NormalizedPerson (name) VALUES ("Mrs. H.");
INSERT INTO NormalizedPerson (name) VALUES ("Mr. Sharpe");
INSERT INTO NormalizedPerson (name) VALUES ("Mrs. Hawkins");
INSERT INTO NormalizedPerson (name) VALUES ("Mrs Hemphill");
INSERT INTO NormalizedPerson (name) VALUES ("Mrs. John Hall");
INSERT INTO NormalizedPerson (name) VALUES ("Mrs Lockhart");
INSERT INTO NormalizedPerson (name) VALUES ("Mrs. Long");
INSERT INTO NormalizedPerson (name) VALUES ("Mrs Mary Hall");
INSERT INTO NormalizedPerson (name) VALUES ("Mrs M Austin Holley");
INSERT INTO NormalizedPerson (name) VALUES ("Mrs. McCormick");
INSERT INTO NormalizedPerson (name) VALUES ("Mrs. McKinstry");
INSERT INTO NormalizedPerson (name) VALUES ("Mrs Meigs");
INSERT INTO NormalizedPerson (name) VALUES ("Mr Smith");
INSERT INTO NormalizedPerson (name) VALUES ("Mr. Smith");
INSERT INTO NormalizedPerson (name) VALUES ("Mrs Page");
INSERT INTO NormalizedPerson (name) VALUES ("Mrs. Peyton");
INSERT INTO NormalizedPerson (name) VALUES ("Mrs. Phelps");
INSERT INTO NormalizedPerson (name) VALUES ("Mrs. Richards");
INSERT INTO NormalizedPerson (name) VALUES ("Mrs. Robinson");
INSERT INTO NormalizedPerson (name) VALUES ("Mrs. Rumseys");
INSERT INTO NormalizedPerson (name) VALUES ("Mrs. Skriggins");
INSERT INTO NormalizedPerson (name) VALUES ("Mrs. Sweet");
INSERT INTO NormalizedPerson (name) VALUES ("Mr Stephen");
INSERT INTO NormalizedPerson (name) VALUES ("Mr. St. John");
INSERT INTO NormalizedPerson (name) VALUES ("Mrs Todd");
INSERT INTO NormalizedPerson (name) VALUES ("Mr. Strange");
INSERT INTO NormalizedPerson (name) VALUES ("Mr. Sumner");
INSERT INTO NormalizedPerson (name) VALUES ("Mrs. W");
INSERT INTO NormalizedPerson (name) VALUES ("Mrs Williams");
INSERT INTO NormalizedPerson (name) VALUES ("Mr. Thomas");
INSERT INTO NormalizedPerson (name) VALUES ("Mr. Tornel");
INSERT INTO NormalizedPerson (name) VALUES ("Mr. Tornel, Mexican Minister at Washington");
INSERT INTO NormalizedPerson (name) VALUES ("Mr Treat");
INSERT INTO NormalizedPerson (name) VALUES ("Mr Triplett");
INSERT INTO NormalizedPerson (name) VALUES ("Mr Valle");
INSERT INTO NormalizedPerson (name) VALUES ("Mr. W.");
INSERT INTO NormalizedPerson (name) VALUES ("M. R. W.");
INSERT INTO NormalizedPerson (name) VALUES ("Mr Whittlesey");
INSERT INTO NormalizedPerson (name) VALUES ("Mr. Ybarra");
INSERT INTO NormalizedPerson (name) VALUES ("Mr. Zenon Trudeau");
INSERT INTO NormalizedPerson (name) VALUES ('M. Slocum');
INSERT INTO NormalizedPerson (name) VALUES ("Nancy Bates");
INSERT INTO NormalizedPerson (name) VALUES ("Nathaniel Cox");
INSERT INTO NormalizedPerson (name) VALUES ("Nathaniel Kimball");
INSERT INTO NormalizedPerson (name) VALUES ('Nathan Pusey');
INSERT INTO NormalizedPerson (name) VALUES ('N A Ware');
INSERT INTO NormalizedPerson (name) VALUES ("Nicholas Clopper");
INSERT INTO NormalizedPerson (name) VALUES ("Nicolas Trammal");
INSERT INTO NormalizedPerson (name) VALUES ('no recipient');
INSERT INTO NormalizedPerson (name) VALUES ("N. Pope");
INSERT INTO NormalizedPerson (name) VALUES ("N. Rightor");
INSERT INTO NormalizedPerson (name) VALUES ("N. Townsend");
INSERT INTO NormalizedPerson (name) VALUES ("N. Wilson");
INSERT INTO NormalizedPerson (name) VALUES ("O D. McAlister");
INSERT INTO NormalizedPerson (name) VALUES ("O. Halsted");
INSERT INTO NormalizedPerson (name) VALUES ('Oliver Jones');
INSERT INTO NormalizedPerson (name) VALUES ("Owen H. Stout");
INSERT INTO NormalizedPerson (name) VALUES ("Padre Muldoon");
INSERT INTO NormalizedPerson (name) VALUES ("Parker");
INSERT INTO NormalizedPerson (name) VALUES ("Parrott");
INSERT INTO NormalizedPerson (name) VALUES ('Pascal Detchemendy');
INSERT INTO NormalizedPerson (name) VALUES ('Patick and Lindsay Clopper');
INSERT INTO NormalizedPerson (name) VALUES ("Patrick Dowling");
INSERT INTO NormalizedPerson (name) VALUES ("Patrick Jack");
INSERT INTO NormalizedPerson (name) VALUES ('Paul Dimmitt');
INSERT INTO NormalizedPerson (name) VALUES ("P. B. Irvine");
INSERT INTO NormalizedPerson (name) VALUES ("Penrose");
INSERT INTO NormalizedPerson (name) VALUES ('People');
INSERT INTO NormalizedPerson (name) VALUES ('People of Colony');
INSERT INTO NormalizedPerson (name) VALUES ('People of Texas');
INSERT INTO NormalizedPerson (name) VALUES ('People of the Colony');
INSERT INTO NormalizedPerson (name) VALUES ('Permanent Council');
INSERT INTO NormalizedPerson (name) VALUES ("Peter De Moss");
INSERT INTO NormalizedPerson (name) VALUES ("Peter E. Bean");
INSERT INTO NormalizedPerson (name) VALUES ("Peter Powell");
INSERT INTO NormalizedPerson (name) VALUES ("Peter W. Grayson");
INSERT INTO NormalizedPerson (name) VALUES ("P. Gilbert");
INSERT INTO NormalizedPerson (name) VALUES ("P Green");
INSERT INTO NormalizedPerson (name) VALUES ("Philadelphian");
INSERT INTO NormalizedPerson (name) VALUES ("Phillip Redinger");
INSERT INTO NormalizedPerson (name) VALUES ("Phillip T Dimmit");
INSERT INTO NormalizedPerson (name) VALUES ('Pierre Delassus De Luziere');
INSERT INTO NormalizedPerson (name) VALUES ('Pierre Laforge');
INSERT INTO NormalizedPerson (name) VALUES ("Poinsett");
INSERT INTO NormalizedPerson (name) VALUES ("Powell");
INSERT INTO NormalizedPerson (name) VALUES ("Powers");
INSERT INTO NormalizedPerson (name) VALUES ('Powers of Commissioners to Waco Indians');
INSERT INTO NormalizedPerson (name) VALUES ("President Jackson");
INSERT INTO NormalizedPerson (name) VALUES ('President of the Consultation');
INSERT INTO NormalizedPerson (name) VALUES ('President of the Provisional Government of Texas');
INSERT INTO NormalizedPerson (name) VALUES ('Provincial Deputation');
INSERT INTO NormalizedPerson (name) VALUES ('Provisional Government');
INSERT INTO NormalizedPerson (name) VALUES ('Provisional Government of Texas');
INSERT INTO NormalizedPerson (name) VALUES ('Provisional Governor');
INSERT INTO NormalizedPerson (name) VALUES ("P R Splane");
INSERT INTO NormalizedPerson (name) VALUES ('P S le Hicks');
INSERT INTO NormalizedPerson (name) VALUES ("P. S. McNeil");
INSERT INTO NormalizedPerson (name) VALUES ('P. S. Slocum');
INSERT INTO NormalizedPerson (name) VALUES ('Public');
INSERT INTO NormalizedPerson (name) VALUES ("Rafael Gonzalez");
INSERT INTO NormalizedPerson (name) VALUES ('Rafae Llanos');
INSERT INTO NormalizedPerson (name) VALUES ('Raleigh');
INSERT INTO NormalizedPerson (name) VALUES ("Ramey");
INSERT INTO NormalizedPerson (name) VALUES ('Ramon Musquiz');
INSERT INTO NormalizedPerson (name) VALUES ('Randall Jones');
INSERT INTO NormalizedPerson (name) VALUES ("Rawson Alley");
INSERT INTO NormalizedPerson (name) VALUES ("R. C. Langdon.");
INSERT INTO NormalizedPerson (name) VALUES ("R Easton");
INSERT INTO NormalizedPerson (name) VALUES ("Renaut Clame");
INSERT INTO NormalizedPerson (name) VALUES ('Residents of Texas');
INSERT INTO NormalizedPerson (name) VALUES ("Reynolds");
INSERT INTO NormalizedPerson (name) VALUES ("R. H. Williams");
INSERT INTO NormalizedPerson (name) VALUES ("Richard Lovelace");
INSERT INTO NormalizedPerson (name) VALUES ("Richard R Royall");
INSERT INTO NormalizedPerson (name) VALUES ("Richd Thurmond");
INSERT INTO NormalizedPerson (name) VALUES ("Richot Barrott");
INSERT INTO NormalizedPerson (name) VALUES ("Risdon H Price");
INSERT INTO NormalizedPerson (name) VALUES ("R. L. Kinny");
INSERT INTO NormalizedPerson (name) VALUES ("Robert Andrews");
INSERT INTO NormalizedPerson (name) VALUES ("Robert Cartwright");
INSERT INTO NormalizedPerson (name) VALUES ('Robert Leftwich or Haden Edwards');
INSERT INTO NormalizedPerson (name) VALUES ("Robert Martin");
INSERT INTO NormalizedPerson (name) VALUES ("Robert M. Williamson");
INSERT INTO NormalizedPerson (name) VALUES ("Robertson");
INSERT INTO NormalizedPerson (name) VALUES ("Robinson");
INSERT INTO NormalizedPerson (name) VALUES ("Robt. Brotherton");
INSERT INTO NormalizedPerson (name) VALUES ("Robt. Desha");
INSERT INTO NormalizedPerson (name) VALUES ("Robt. Millican");
INSERT INTO NormalizedPerson (name) VALUES ("Robt Robinson");
INSERT INTO NormalizedPerson (name) VALUES ('Roswell Mills');
INSERT INTO NormalizedPerson (name) VALUES ('R. P. Guyard');
INSERT INTO NormalizedPerson (name) VALUES ("R Price");
INSERT INTO NormalizedPerson (name) VALUES ("R. R. Royall, Presd Genl Council.");
INSERT INTO NormalizedPerson (name) VALUES ("R. Thirmond");
INSERT INTO NormalizedPerson (name) VALUES ("Ruggles");
INSERT INTO NormalizedPerson (name) VALUES ("Russians");
INSERT INTO NormalizedPerson (name) VALUES ("R W Dunlap");
INSERT INTO NormalizedPerson (name) VALUES ("Sam Houston");
INSERT INTO NormalizedPerson (name) VALUES ("Saml. Gates");
INSERT INTO NormalizedPerson (name) VALUES ("Saml. Kennedy");
INSERT INTO NormalizedPerson (name) VALUES ('Sam McCraw');
INSERT INTO NormalizedPerson (name) VALUES ("Samuel May");
INSERT INTO NormalizedPerson (name) VALUES ("Samuel M. Williams");
INSERT INTO NormalizedPerson (name) VALUES ("Samuel Parkman");
INSERT INTO NormalizedPerson (name) VALUES ("Samuel Patterson");
INSERT INTO NormalizedPerson (name) VALUES ("Samuel Pharr");
INSERT INTO NormalizedPerson (name) VALUES ("Samuel Sexton");
INSERT INTO NormalizedPerson (name) VALUES ("Samuel S Pearson");
INSERT INTO NormalizedPerson (name) VALUES ("Samuel Staples");
INSERT INTO NormalizedPerson (name) VALUES ("Samuel Swartwout");
INSERT INTO NormalizedPerson (name) VALUES ("Santiago Austin");
INSERT INTO NormalizedPerson (name) VALUES ("Savages");
INSERT INTO NormalizedPerson (name) VALUES ("S Bacon");
INSERT INTO NormalizedPerson (name) VALUES ('Schooner Lively');
INSERT INTO NormalizedPerson (name) VALUES ("scoundrels");
INSERT INTO NormalizedPerson (name) VALUES ('Secretary of Relations');
INSERT INTO NormalizedPerson (name) VALUES ("Sen Placido Venevedas");
INSERT INTO NormalizedPerson (name) VALUES ('Seth Hunt');
INSERT INTO NormalizedPerson (name) VALUES ("Seth Ingram");
INSERT INTO NormalizedPerson (name) VALUES ("Sexton Morgan");
INSERT INTO NormalizedPerson (name) VALUES ('S Hatch');
INSERT INTO NormalizedPerson (name) VALUES ("Shawnees");
INSERT INTO NormalizedPerson (name) VALUES ('Sheriff of Colony');
INSERT INTO NormalizedPerson (name) VALUES ('Sheriff of the Colony');
INSERT INTO NormalizedPerson (name) VALUES ("Shields");
INSERT INTO NormalizedPerson (name) VALUES ("Silas M. Stilwell");
INSERT INTO NormalizedPerson (name) VALUES ("Solomon Brown");
INSERT INTO NormalizedPerson (name) VALUES ("Sor Jose Luis");
INSERT INTO NormalizedPerson (name) VALUES ("Sor Porter");
INSERT INTO NormalizedPerson (name) VALUES ('S. T. Angier');
INSERT INTO NormalizedPerson (name) VALUES ('State Congress');
INSERT INTO NormalizedPerson (name) VALUES ('State of Kentucky');
INSERT INTO NormalizedPerson (name) VALUES ('State of Missouri');
INSERT INTO NormalizedPerson (name) VALUES ("Stephen F. Austin");
INSERT INTO NormalizedPerson (name) VALUES ("Sterling Robertson");
INSERT INTO NormalizedPerson (name) VALUES ("Sub Deacon Don Juan Manuel Sambrano");
INSERT INTO NormalizedPerson (name) VALUES ("Susan. W. Maxwell");
INSERT INTO NormalizedPerson (name) VALUES ("Swiss Gentlemen");
INSERT INTO NormalizedPerson (name) VALUES ("Sylvanus Castleman");
INSERT INTO NormalizedPerson (name) VALUES ('Sylvester Murphy');
INSERT INTO NormalizedPerson (name) VALUES ('Tacitus Clay');
INSERT INTO NormalizedPerson (name) VALUES ("Tancahue Indians");
INSERT INTO NormalizedPerson (name) VALUES ("Tawakanies");
INSERT INTO NormalizedPerson (name) VALUES ("T. Douglass");
INSERT INTO NormalizedPerson (name) VALUES ("T. Evans");
INSERT INTO NormalizedPerson (name) VALUES ('Texas Army');
INSERT INTO NormalizedPerson (name) VALUES ('Texas Gazette');
INSERT INTO NormalizedPerson (name) VALUES ("Texians");
INSERT INTO NormalizedPerson (name) VALUES ('T. Farelly');
INSERT INTO NormalizedPerson (name) VALUES ("T. H. Benton");
INSERT INTO NormalizedPerson (name) VALUES ("Thomas Bibb");
INSERT INTO NormalizedPerson (name) VALUES ("Thomas C. Scott");
INSERT INTO NormalizedPerson (name) VALUES ("Thomas E. Davis");
INSERT INTO NormalizedPerson (name) VALUES ("Thomas F. Learning");
INSERT INTO NormalizedPerson (name) VALUES ("Thomas F. McKinney");
INSERT INTO NormalizedPerson (name) VALUES ("Thomas Jefferson Chambers");
INSERT INTO NormalizedPerson (name) VALUES ("Thomas Norvell");
INSERT INTO NormalizedPerson (name) VALUES ("Thomas Oliver");
INSERT INTO NormalizedPerson (name) VALUES ("Thomas Rabb");
INSERT INTO NormalizedPerson (name) VALUES ("Thomas V. Alley");
INSERT INTO NormalizedPerson (name) VALUES ("Thomas Westall");
INSERT INTO NormalizedPerson (name) VALUES ("Thomas Williams");
INSERT INTO NormalizedPerson (name) VALUES ("Thompson");
INSERT INTO NormalizedPerson (name) VALUES ("Thos A. Smith");
INSERT INTO NormalizedPerson (name) VALUES ("Thos. Barnett");
INSERT INTO NormalizedPerson (name) VALUES ("Thos. Boatwright");
INSERT INTO NormalizedPerson (name) VALUES ("Thos Earle");
INSERT INTO NormalizedPerson (name) VALUES ("Thos. Gray");
INSERT INTO NormalizedPerson (name) VALUES ("Thos. H Borden");
INSERT INTO NormalizedPerson (name) VALUES ("Thos. Hill");
INSERT INTO NormalizedPerson (name) VALUES ("Thos. Hockley");
INSERT INTO NormalizedPerson (name) VALUES ("Thos. M. Duke");
INSERT INTO NormalizedPerson (name) VALUES ("Thos. P. Gazsley");
INSERT INTO NormalizedPerson (name) VALUES ("Timothy Mullins");
INSERT INTO NormalizedPerson (name) VALUES ("Timothy Phelps");
INSERT INTO NormalizedPerson (name) VALUES ("T. Jamison");
INSERT INTO NormalizedPerson (name) VALUES ("T. Newberry");
INSERT INTO NormalizedPerson (name) VALUES ("Tonkawa Indians");
INSERT INTO NormalizedPerson (name) VALUES ('T. [or J.] Reilly');
INSERT INTO NormalizedPerson (name) VALUES ("T. Rector");
INSERT INTO NormalizedPerson (name) VALUES ('Unknown');
INSERT INTO NormalizedPerson (name) VALUES ('Unsent');
INSERT INTO NormalizedPerson (name) VALUES ('U. S. Consul');
INSERT INTO NormalizedPerson (name) VALUES ("Van Buren");
INSERT INTO NormalizedPerson (name) VALUES ('Various New Orleans firms');
INSERT INTO NormalizedPerson (name) VALUES ("Varner");
INSERT INTO NormalizedPerson (name) VALUES ("Vaughn");
INSERT INTO NormalizedPerson (name) VALUES ("V. Fernandez");
INSERT INTO NormalizedPerson (name) VALUES ("Victor Blanco");
INSERT INTO NormalizedPerson (name) VALUES ('Volunteers at Bexar');
INSERT INTO NormalizedPerson (name) VALUES ("Waco Indians");
INSERT INTO NormalizedPerson (name) VALUES ("Walter Hogan");
INSERT INTO NormalizedPerson (name) VALUES ("Walter Sutherland");
INSERT INTO NormalizedPerson (name) VALUES ("Walter Wilinson");
INSERT INTO NormalizedPerson (name) VALUES ('Warren Buford');
INSERT INTO NormalizedPerson (name) VALUES ("Warren D. C. Hall");
INSERT INTO NormalizedPerson (name) VALUES ('Washington Hotel');
INSERT INTO NormalizedPerson (name) VALUES ("Wawfield");
INSERT INTO NormalizedPerson (name) VALUES ("W. B. Travis");
INSERT INTO NormalizedPerson (name) VALUES ("W Bullock");
INSERT INTO NormalizedPerson (name) VALUES ("W. C. White");
INSERT INTO NormalizedPerson (name) VALUES ('W D C Hall');
INSERT INTO NormalizedPerson (name) VALUES ("W. Dewees");
INSERT INTO NormalizedPerson (name) VALUES ("Westover");
INSERT INTO NormalizedPerson (name) VALUES ("Wheeler");
INSERT INTO NormalizedPerson (name) VALUES ("Whitlock");
INSERT INTO NormalizedPerson (name) VALUES ("W H Whitaker");
INSERT INTO NormalizedPerson (name) VALUES ("Wiggins");
INSERT INTO NormalizedPerson (name) VALUES ("Wilkinson");
INSERT INTO NormalizedPerson (name) VALUES ("Will C. Carr");
INSERT INTO NormalizedPerson (name) VALUES ("William Bates");
INSERT INTO NormalizedPerson (name) VALUES ("William Bryan");
INSERT INTO NormalizedPerson (name) VALUES ("William Cooper");
INSERT INTO NormalizedPerson (name) VALUES ("William D. Horton");
INSERT INTO NormalizedPerson (name) VALUES ("William F. Gibbons");
INSERT INTO NormalizedPerson (name) VALUES ("William Gilmore");
INSERT INTO NormalizedPerson (name) VALUES ("William Jack");
INSERT INTO NormalizedPerson (name) VALUES ("William Kincheloe");
INSERT INTO NormalizedPerson (name) VALUES ("William Laughlin");
INSERT INTO NormalizedPerson (name) VALUES ("William Little");
INSERT INTO NormalizedPerson (name) VALUES ("William Millican");
INSERT INTO NormalizedPerson (name) VALUES ("William M Ohara");
INSERT INTO NormalizedPerson (name) VALUES ("William Moss");
INSERT INTO NormalizedPerson (name) VALUES ("William Murraysole");
INSERT INTO NormalizedPerson (name) VALUES ("William Perry");
INSERT INTO NormalizedPerson (name) VALUES ("William Pettus");
INSERT INTO NormalizedPerson (name) VALUES ("William Rabb");
INSERT INTO NormalizedPerson (name) VALUES ("William Russell");
INSERT INTO NormalizedPerson (name) VALUES ("Williams");
INSERT INTO NormalizedPerson (name) VALUES ("William S Brown");
INSERT INTO NormalizedPerson (name) VALUES ("William Shreve");
INSERT INTO NormalizedPerson (name) VALUES ("William Smethers");
INSERT INTO NormalizedPerson (name) VALUES ("William Smith");
INSERT INTO NormalizedPerson (name) VALUES ("Williamson");
INSERT INTO NormalizedPerson (name) VALUES ("William Spence");
INSERT INTO NormalizedPerson (name) VALUES ("William Taylor");
INSERT INTO NormalizedPerson (name) VALUES ("William Vince");
INSERT INTO NormalizedPerson (name) VALUES ("William Waters");
INSERT INTO NormalizedPerson (name) VALUES ("Willis J. Powell");
INSERT INTO NormalizedPerson (name) VALUES ("W J Offutt");
INSERT INTO NormalizedPerson (name) VALUES ("Wm. Anderson");
INSERT INTO NormalizedPerson (name) VALUES ("Wm Ashbrook");
INSERT INTO NormalizedPerson (name) VALUES ("Wm Butler");
INSERT INTO NormalizedPerson (name) VALUES ("Wm Ficklin");
INSERT INTO NormalizedPerson (name) VALUES ("Wm. G. Hill");
INSERT INTO NormalizedPerson (name) VALUES ("Wm Griffin Senr");
INSERT INTO NormalizedPerson (name) VALUES ("Wm H. McCurdy");
INSERT INTO NormalizedPerson (name) VALUES ("Wm. H. Smith");
INSERT INTO NormalizedPerson (name) VALUES ("Wm. H. Wharton");
INSERT INTO NormalizedPerson (name) VALUES ("Wm. Laughlin");
INSERT INTO NormalizedPerson (name) VALUES ("Wm. N. Henderson");
INSERT INTO NormalizedPerson (name) VALUES ("Wm. Perry");
INSERT INTO NormalizedPerson (name) VALUES ("Wm. P. Harris");
INSERT INTO NormalizedPerson (name) VALUES ("Wm. P Scott");
INSERT INTO NormalizedPerson (name) VALUES ("Wm. Purkins");
INSERT INTO NormalizedPerson (name) VALUES ("Wm Reese");
INSERT INTO NormalizedPerson (name) VALUES ("Wm. R. Leckie");
INSERT INTO NormalizedPerson (name) VALUES ("Wm. Roberts");
INSERT INTO NormalizedPerson (name) VALUES ("Wm. Robins,");
INSERT INTO NormalizedPerson (name) VALUES ("Wm. S. Archer");
INSERT INTO NormalizedPerson (name) VALUES ("Wm. Shreve");
INSERT INTO NormalizedPerson (name) VALUES ("Wm Singer");
INSERT INTO NormalizedPerson (name) VALUES ("Wm. S. Lewis");
INSERT INTO NormalizedPerson (name) VALUES ("Wm Stafford");
INSERT INTO NormalizedPerson (name) VALUES ("Wm. T. Austin");
INSERT INTO NormalizedPerson (name) VALUES ("Wm. W. Hunter");
INSERT INTO NormalizedPerson (name) VALUES ("Wm. Williamson");
INSERT INTO NormalizedPerson (name) VALUES ("Wm. W. Lea.");
INSERT INTO NormalizedPerson (name) VALUES ("Woodbury");
INSERT INTO NormalizedPerson (name) VALUES ("Wra Scott");
INSERT INTO NormalizedPerson (name) VALUES ("W Stevenson");
INSERT INTO NormalizedPerson (name) VALUES ("W. Wilson");
INSERT INTO NormalizedPerson (name) VALUES ('Wyatt Hanks');
INSERT INTO NormalizedPerson (name) VALUES ("Wyly Martin");
INSERT INTO NormalizedPerson (name) VALUES ("Y. E.");
INSERT INTO NormalizedPerson (name) VALUES ("Ylario de la Garza");
INSERT INTO NormalizedPerson (name) VALUES ("Yorkino");
INSERT INTO NormalizedPerson (name) VALUES ("young men");
INSERT INTO NormalizedPerson (name) VALUES ("Zadock Woods");
INSERT INTO NormalizedPerson (name) VALUES ('Zenas Priest');
INSERT INTO NormalizedPerson (name) VALUES ('Zeno Phillips');
INSERT INTO NormalizedPerson (name) VALUES ("Zenteno");
