INSERT INTO NormalizedPerson (name) VALUES ('Aaron Elliot');
INSERT INTO NormalizedPerson (name) VALUES ('Abiel P Mead');
INSERT INTO NormalizedPerson (name) VALUES ('Abraham Armstrong');
INSERT INTO NormalizedPerson (name) VALUES ('Absolom Johnson');
INSERT INTO NormalizedPerson (name) VALUES ('A. C. Ainsworth');
INSERT INTO NormalizedPerson (name) VALUES ('A. Carnahan');
INSERT INTO NormalizedPerson (name) VALUES ('A. C. Taylor');
INSERT INTO NormalizedPerson (name) VALUES ('Adam Brown');
INSERT INTO NormalizedPerson (name) VALUES ('Adam Trinno');
INSERT INTO NormalizedPerson (name) VALUES ('A. Dilliar');
INSERT INTO NormalizedPerson (name) VALUES ('Adner Kuykendall');
INSERT INTO NormalizedPerson (name) VALUES ('A. Gamble');
INSERT INTO NormalizedPerson (name) VALUES ('A. G. Wavell');
INSERT INTO NormalizedPerson (name) VALUES ('A. H. Adams');
INSERT INTO NormalizedPerson (name) VALUES ('A Holdridge');
INSERT INTO NormalizedPerson (name) VALUES ('A Huston');
INSERT INTO NormalizedPerson (name) VALUES ('A J Harris');
INSERT INTO NormalizedPerson (name) VALUES ('A J Yates');
INSERT INTO NormalizedPerson (name) VALUES ('Alaman');
INSERT INTO NormalizedPerson (name) VALUES ('Albert Gallatin');
INSERT INTO NormalizedPerson (name) VALUES ('Alcade of San Felipe');
INSERT INTO NormalizedPerson (name) VALUES ('Alcalde');
INSERT INTO NormalizedPerson (name) VALUES ('Alcalde of Gonzales');
INSERT INTO NormalizedPerson (name) VALUES ('Alcalde of San Felipe');
INSERT INTO NormalizedPerson (name) VALUES ('Alexander Calvit');
INSERT INTO NormalizedPerson (name) VALUES ('Alexander Curcier');
INSERT INTO NormalizedPerson (name) VALUES ('Alexander Frazer');
INSERT INTO NormalizedPerson (name) VALUES ('Alexander Hodge');
INSERT INTO NormalizedPerson (name) VALUES ('Alexander Jackson');
INSERT INTO NormalizedPerson (name) VALUES ('Alexander Thomson');
INSERT INTO NormalizedPerson (name) VALUES ('Alex McNair');
INSERT INTO NormalizedPerson (name) VALUES ('Alijah Hull');
INSERT INTO NormalizedPerson (name) VALUES ('A. McNair');
INSERT INTO NormalizedPerson (name) VALUES ('American Hotel');
INSERT INTO NormalizedPerson (name) VALUES ('A. Miller');
INSERT INTO NormalizedPerson (name) VALUES ('Amos Edwards');
INSERT INTO NormalizedPerson (name) VALUES ('Amos Rawls');
INSERT INTO NormalizedPerson (name) VALUES ('Amy White');
INSERT INTO NormalizedPerson (name) VALUES ('Anastacio Bustamante');
INSERT INTO NormalizedPerson (name) VALUES ('Andrew Boggs');
INSERT INTO NormalizedPerson (name) VALUES ('Andrew Erwin');
INSERT INTO NormalizedPerson (name) VALUES ('Andrew Henry');
INSERT INTO NormalizedPerson (name) VALUES ('Andrew Jackson');
INSERT INTO NormalizedPerson (name) VALUES ('Andrew Mitchell');
INSERT INTO NormalizedPerson (name) VALUES ('Andrew Robertson');
INSERT INTO NormalizedPerson (name) VALUES ('Andrew Scott');
INSERT INTO NormalizedPerson (name) VALUES ('Anthony Butler');
INSERT INTO NormalizedPerson (name) VALUES ('Anthony Dey and George Curtis');
INSERT INTO NormalizedPerson (name) VALUES ('Anthony R. Clarke');
INSERT INTO NormalizedPerson (name) VALUES ('Antoine Soulard');
INSERT INTO NormalizedPerson (name) VALUES ('Antonio Martinez');
INSERT INTO NormalizedPerson (name) VALUES ('Archibald Austin');
INSERT INTO NormalizedPerson (name) VALUES ('A. R. McNair');
INSERT INTO NormalizedPerson (name) VALUES ('Armistead Moore');
INSERT INTO NormalizedPerson (name) VALUES ('A. Robinson');
INSERT INTO NormalizedPerson (name) VALUES ('Arthur G. Wavell');
INSERT INTO NormalizedPerson (name) VALUES ('Arthur McCormick, John R. Harris');
INSERT INTO NormalizedPerson (name) VALUES ('Asa Brigham');
INSERT INTO NormalizedPerson (name) VALUES ('Asahel Langworthy');
INSERT INTO NormalizedPerson (name) VALUES ('Asa Hoxey');
INSERT INTO NormalizedPerson (name) VALUES ('Asa Mitchell');
INSERT INTO NormalizedPerson (name) VALUES ('A. Sampyrac');
INSERT INTO NormalizedPerson (name) VALUES ('Austin');
INSERT INTO NormalizedPerson (name) VALUES ('Authorities of La Bahia');
INSERT INTO NormalizedPerson (name) VALUES ('A. W. McClain');
INSERT INTO NormalizedPerson (name) VALUES ('Aylett C. Buckner');
INSERT INTO NormalizedPerson (name) VALUES ('Ayunatmiento of San Felipe');
INSERT INTO NormalizedPerson (name) VALUES ('Ayuntamiento of Bexar');
INSERT INTO NormalizedPerson (name) VALUES ('Ayuntamiento of Brazoria');
INSERT INTO NormalizedPerson (name) VALUES ('Ayuntamiento of Matagorda');
INSERT INTO NormalizedPerson (name) VALUES ('Ayuntamiento of San Felipe');
INSERT INTO NormalizedPerson (name) VALUES ('Ayuntamineto of Nacogdoches');
INSERT INTO NormalizedPerson (name) VALUES ('Bank of St Louis');
INSERT INTO NormalizedPerson (name) VALUES ('Barnard E. Bee');
INSERT INTO NormalizedPerson (name) VALUES ('Baron de Bastrop');
INSERT INTO NormalizedPerson (name) VALUES ('Bartlett Sims');
INSERT INTO NormalizedPerson (name) VALUES ('Bellows and Cochran');
INSERT INTO NormalizedPerson (name) VALUES ('Benjamin Carrico');
INSERT INTO NormalizedPerson (name) VALUES ('Benjamin Deckerd');
INSERT INTO NormalizedPerson (name) VALUES ('Benjamin Elliott');
INSERT INTO NormalizedPerson (name) VALUES ('Benjamin Fowler');
INSERT INTO NormalizedPerson (name) VALUES ('Benjamin F. Smith');
INSERT INTO NormalizedPerson (name) VALUES ('Benjamin Gilman');
INSERT INTO NormalizedPerson (name) VALUES ('Benjamin Johnston');
INSERT INTO NormalizedPerson (name) VALUES ('Benjamin Lindsey');
INSERT INTO NormalizedPerson (name) VALUES ('Benjamin Long');
INSERT INTO NormalizedPerson (name) VALUES ('Benjamin R. Milam');
INSERT INTO NormalizedPerson (name) VALUES ('Benjamin W. Edwards');
INSERT INTO NormalizedPerson (name) VALUES ('Ben J. Shakelford');
INSERT INTO NormalizedPerson (name) VALUES ('Berry and Battle Dr.');
INSERT INTO NormalizedPerson (name) VALUES ('B. J. Thompson');
INSERT INTO NormalizedPerson (name) VALUES ('B J White');
INSERT INTO NormalizedPerson (name) VALUES ('Bogart');
INSERT INTO NormalizedPerson (name) VALUES ('Boone Whiteside');
INSERT INTO NormalizedPerson (name) VALUES ('Branch T Archer');
INSERT INTO NormalizedPerson (name) VALUES ('Bryan and Morrison');
INSERT INTO NormalizedPerson (name) VALUES ('Bryrd Lockhart, Green De Witt, James Kerr');
INSERT INTO NormalizedPerson (name) VALUES ('B T Jacques');
INSERT INTO NormalizedPerson (name) VALUES ('Burril J. Thompson');
INSERT INTO NormalizedPerson (name) VALUES ('Bustamente');
INSERT INTO NormalizedPerson (name) VALUES ('B. W. Edwards');
INSERT INTO NormalizedPerson (name) VALUES ('Captain Dillard');
INSERT INTO NormalizedPerson (name) VALUES ('Captain Dixon');
INSERT INTO NormalizedPerson (name) VALUES ('Captains');
INSERT INTO NormalizedPerson (name) VALUES ('Captian Richard Fields');
INSERT INTO NormalizedPerson (name) VALUES ('Carbajal\'s Mother');
INSERT INTO NormalizedPerson (name) VALUES ('Carlos Garcia');
INSERT INTO NormalizedPerson (name) VALUES ('Cartwright');
INSERT INTO NormalizedPerson (name) VALUES ('C. B. Penrose');
INSERT INTO NormalizedPerson (name) VALUES ('C B Stewart');
INSERT INTO NormalizedPerson (name) VALUES ('Central Committee');
INSERT INTO NormalizedPerson (name) VALUES ('Chapman');
INSERT INTO NormalizedPerson (name) VALUES ('Charles Austin');
INSERT INTO NormalizedPerson (name) VALUES ('Charles Boyer');
INSERT INTO NormalizedPerson (name) VALUES ('Charles Douglas');
INSERT INTO NormalizedPerson (name) VALUES ('Charles Elliot');
INSERT INTO NormalizedPerson (name) VALUES ('Charles McDormitt');
INSERT INTO NormalizedPerson (name) VALUES ('Charles Staples');
INSERT INTO NormalizedPerson (name) VALUES ('Charles W Webber');
INSERT INTO NormalizedPerson (name) VALUES ('Cherokee Chiefs');
INSERT INTO NormalizedPerson (name) VALUES ('Christian Wilt');
INSERT INTO NormalizedPerson (name) VALUES ('Churchill Fulshear');
INSERT INTO NormalizedPerson (name) VALUES ('Citizens of Jefferson County');
INSERT INTO NormalizedPerson (name) VALUES ('Citizens of Mina');
INSERT INTO NormalizedPerson (name) VALUES ('City Hotel');
INSERT INTO NormalizedPerson (name) VALUES ('Clopper and Co');
INSERT INTO NormalizedPerson (name) VALUES ('Collinsworth and Grayson');
INSERT INTO NormalizedPerson (name) VALUES ('Colonel Charles Caldwell');
INSERT INTO NormalizedPerson (name) VALUES ('Colonel Lewis');
INSERT INTO NormalizedPerson (name) VALUES ('Colonel Scriggins');
INSERT INTO NormalizedPerson (name) VALUES ('Colonists');
INSERT INTO NormalizedPerson (name) VALUES ('Colonlists');
INSERT INTO NormalizedPerson (name) VALUES ('Colony');
INSERT INTO NormalizedPerson (name) VALUES ('Colorado District');
INSERT INTO NormalizedPerson (name) VALUES ('Columbia Committee');
INSERT INTO NormalizedPerson (name) VALUES ('Comittee of Safety of San Felipe');
INSERT INTO NormalizedPerson (name) VALUES ('Committee at Convention');
INSERT INTO NormalizedPerson (name) VALUES ('Committee of Harrisburgh');
INSERT INTO NormalizedPerson (name) VALUES ('Committee of San Augustine');
INSERT INTO NormalizedPerson (name) VALUES ('Committee of San Felipe');
INSERT INTO NormalizedPerson (name) VALUES ('Committees of Nacogdoches and San Augustine');
INSERT INTO NormalizedPerson (name) VALUES ('Commodore David Porter');
INSERT INTO NormalizedPerson (name) VALUES ('Congress');
INSERT INTO NormalizedPerson (name) VALUES ('Convention');
INSERT INTO NormalizedPerson (name) VALUES ('Council of War');
INSERT INTO NormalizedPerson (name) VALUES ('Dan Bissell');
INSERT INTO NormalizedPerson (name) VALUES ('Dan Black');
INSERT INTO NormalizedPerson (name) VALUES ('Daniel Ayers');
INSERT INTO NormalizedPerson (name) VALUES ('Daniel Draper');
INSERT INTO NormalizedPerson (name) VALUES ('Daniel Dunklin');
INSERT INTO NormalizedPerson (name) VALUES ('Daniel E. Bayles');
INSERT INTO NormalizedPerson (name) VALUES ('Daniel Phelps');
INSERT INTO NormalizedPerson (name) VALUES ('Darius Shaw');
INSERT INTO NormalizedPerson (name) VALUES ('David Bright');
INSERT INTO NormalizedPerson (name) VALUES ('David Gallaher');
INSERT INTO NormalizedPerson (name) VALUES ('David G. Burnet');
INSERT INTO NormalizedPerson (name) VALUES ('David H. Holstein');
INSERT INTO NormalizedPerson (name) VALUES ('David J. Marple');
INSERT INTO NormalizedPerson (name) VALUES ('David Mills');
INSERT INTO NormalizedPerson (name) VALUES ('David M. McCormick');
INSERT INTO NormalizedPerson (name) VALUES ('David T. W. Cook');
INSERT INTO NormalizedPerson (name) VALUES ('David W Price');
INSERT INTO NormalizedPerson (name) VALUES ('D. B. Dameron');
INSERT INTO NormalizedPerson (name) VALUES ('D. C. Barrett');
INSERT INTO NormalizedPerson (name) VALUES ('D. Crozer');
INSERT INTO NormalizedPerson (name) VALUES ('Deaf Smith');
INSERT INTO NormalizedPerson (name) VALUES ('Dexter C. Gunn and David Bucklin');
INSERT INTO NormalizedPerson (name) VALUES ('Dillard');
INSERT INTO NormalizedPerson (name) VALUES ('District of Bravo settlers');
INSERT INTO NormalizedPerson (name) VALUES ('Doctors Wiliam P Smith, Thomas P Gazley et Al');
INSERT INTO NormalizedPerson (name) VALUES ('Document not sent');
INSERT INTO NormalizedPerson (name) VALUES ('Domingo de Ugartechea');
INSERT INTO NormalizedPerson (name) VALUES ('Douglas Forsythe');
INSERT INTO NormalizedPerson (name) VALUES ('D R Hopkins');
INSERT INTO NormalizedPerson (name) VALUES ('Dr. John Sibley');
INSERT INTO NormalizedPerson (name) VALUES ('Dr. Joseph Bowers');
INSERT INTO NormalizedPerson (name) VALUES ('Dr. Wells');
INSERT INTO NormalizedPerson (name) VALUES ('D T Fitchett');
INSERT INTO NormalizedPerson (name) VALUES ('Dudley R. Tinker');
INSERT INTO NormalizedPerson (name) VALUES ('Duff Chadwell');
INSERT INTO NormalizedPerson (name) VALUES ('D. W. Anthony');
INSERT INTO NormalizedPerson (name) VALUES ('D. W. Smith');
INSERT INTO NormalizedPerson (name) VALUES ('E. A. Elliott');
INSERT INTO NormalizedPerson (name) VALUES ('E B Birdsall');
INSERT INTO NormalizedPerson (name) VALUES ('Ebel Miton,Ranford Berry, F. Smith, Wm. H Smith, John Teal, and Thomas ?');
INSERT INTO NormalizedPerson (name) VALUES ('Editor of the Telegraph and Texas Register');
INSERT INTO NormalizedPerson (name) VALUES ('Edmund Andrews');
INSERT INTO NormalizedPerson (name) VALUES ('Edmund St. John Hawkins');
INSERT INTO NormalizedPerson (name) VALUES ('Edward and John Lovelace');
INSERT INTO NormalizedPerson (name) VALUES ('Edward Burleson');
INSERT INTO NormalizedPerson (name) VALUES ('Edward Burleson and Ben Milam');
INSERT INTO NormalizedPerson (name) VALUES ('Edward Gritten');
INSERT INTO NormalizedPerson (name) VALUES ('[Edward Livingston?]');
INSERT INTO NormalizedPerson (name) VALUES ('Edward Lovelace');
INSERT INTO NormalizedPerson (name) VALUES ('Edward McDonald');
INSERT INTO NormalizedPerson (name) VALUES ('Edward Sharp');
INSERT INTO NormalizedPerson (name) VALUES ('Edwin L Pettit');
INSERT INTO NormalizedPerson (name) VALUES ('E. Lewis');
INSERT INTO NormalizedPerson (name) VALUES ('Elias Austin Elliot');
INSERT INTO NormalizedPerson (name) VALUES ('Elias Bates');
INSERT INTO NormalizedPerson (name) VALUES ('Elias R. Wightman');
INSERT INTO NormalizedPerson (name) VALUES ('Elijah Allcorn');
INSERT INTO NormalizedPerson (name) VALUES ('Elijah Noble');
INSERT INTO NormalizedPerson (name) VALUES ('Eli Mercer');
INSERT INTO NormalizedPerson (name) VALUES ('Elisha Roberts');
INSERT INTO NormalizedPerson (name) VALUES ('Eliza W Austin');
INSERT INTO NormalizedPerson (name) VALUES ('Ellis H. Bean');
INSERT INTO NormalizedPerson (name) VALUES ('Emigrants');
INSERT INTO NormalizedPerson (name) VALUES ('Emily Austin');
INSERT INTO NormalizedPerson (name) VALUES ('Emily Bryan');
INSERT INTO NormalizedPerson (name) VALUES ('Emily Perry');
INSERT INTO NormalizedPerson (name) VALUES ('Emperor Iturbide');
INSERT INTO NormalizedPerson (name) VALUES ('E. N. Bradley');
INSERT INTO NormalizedPerson (name) VALUES ('Enoch Brenson');
INSERT INTO NormalizedPerson (name) VALUES ('Erasmus Ellis');
INSERT INTO NormalizedPerson (name) VALUES ('E. R. Wightman');
INSERT INTO NormalizedPerson (name) VALUES ('Estate of Moses Austin');
INSERT INTO NormalizedPerson (name) VALUES ('E. St John Hawkins');
INSERT INTO NormalizedPerson (name) VALUES ('Evans and Shields');
INSERT INTO NormalizedPerson (name) VALUES ('E. W. Gregory');
INSERT INTO NormalizedPerson (name) VALUES ('Falconer and Comegys');
INSERT INTO NormalizedPerson (name) VALUES ('Faris and White');
INSERT INTO NormalizedPerson (name) VALUES ('F. Durcy');
INSERT INTO NormalizedPerson (name) VALUES ('Federal Congress');
INSERT INTO NormalizedPerson (name) VALUES ('Felipe de la Garza');
INSERT INTO NormalizedPerson (name) VALUES ('Felix H. Walker');
INSERT INTO NormalizedPerson (name) VALUES ('Felix Robertson');
INSERT INTO NormalizedPerson (name) VALUES ('Felix Trudeau');
INSERT INTO NormalizedPerson (name) VALUES ('F. H. Rankin');
INSERT INTO NormalizedPerson (name) VALUES ('FranÃ§ois Grapp');
INSERT INTO NormalizedPerson (name) VALUES ('Francis Baldwin');
INSERT INTO NormalizedPerson (name) VALUES ('Francis Bigham');
INSERT INTO NormalizedPerson (name) VALUES ('Francis Keller');
INSERT INTO NormalizedPerson (name) VALUES ('Francis Major');
INSERT INTO NormalizedPerson (name) VALUES ('Francis P. Wall');
INSERT INTO NormalizedPerson (name) VALUES ('Francis Smith');
INSERT INTO NormalizedPerson (name) VALUES ('Francis W. Johnson');
INSERT INTO NormalizedPerson (name) VALUES ('Frederick Bates');
INSERT INTO NormalizedPerson (name) VALUES ('Freeman Pettus');
INSERT INTO NormalizedPerson (name) VALUES ('Frost Thorn');
INSERT INTO NormalizedPerson (name) VALUES ('F. W. Johnson');
INSERT INTO NormalizedPerson (name) VALUES ('Gail Borden, Jr.');
INSERT INTO NormalizedPerson (name) VALUES ('G B Cotten');
INSERT INTO NormalizedPerson (name) VALUES ('G Edwards');
INSERT INTO NormalizedPerson (name) VALUES ('General Fernandez');
INSERT INTO NormalizedPerson (name) VALUES ('General Gaines');
INSERT INTO NormalizedPerson (name) VALUES ('general public');
INSERT INTO NormalizedPerson (name) VALUES ('General Wilkinson');
INSERT INTO NormalizedPerson (name) VALUES ('General William H Ashley');
INSERT INTO NormalizedPerson (name) VALUES ('George Antonio Nixon');
INSERT INTO NormalizedPerson (name) VALUES ('George B McKinstry');
INSERT INTO NormalizedPerson (name) VALUES ('George Duty');
INSERT INTO NormalizedPerson (name) VALUES ('George English');
INSERT INTO NormalizedPerson (name) VALUES ('George Fisher');
INSERT INTO NormalizedPerson (name) VALUES ('George Hammond');
INSERT INTO NormalizedPerson (name) VALUES ('George H. Robb');
INSERT INTO NormalizedPerson (name) VALUES ('George Huff');
INSERT INTO NormalizedPerson (name) VALUES ('George L Hammeken');
INSERT INTO NormalizedPerson (name) VALUES ('George Nixon');
INSERT INTO NormalizedPerson (name) VALUES ('George Orr');
INSERT INTO NormalizedPerson (name) VALUES ('George P Digges');
INSERT INTO NormalizedPerson (name) VALUES ('George Poindexter');
INSERT INTO NormalizedPerson (name) VALUES ('George Robinson');
INSERT INTO NormalizedPerson (name) VALUES ('George Shannon');
INSERT INTO NormalizedPerson (name) VALUES ('George S. Pentacost');
INSERT INTO NormalizedPerson (name) VALUES ('George Tennille');
INSERT INTO NormalizedPerson (name) VALUES ('George W. Poe');
INSERT INTO NormalizedPerson (name) VALUES ('George Y Bright');
INSERT INTO NormalizedPerson (name) VALUES ('Gideon Blackburn');
INSERT INTO NormalizedPerson (name) VALUES ('Gilbert');
INSERT INTO NormalizedPerson (name) VALUES ('G M Collinsworth');
INSERT INTO NormalizedPerson (name) VALUES ('Government of the Province of Texas');
INSERT INTO NormalizedPerson (name) VALUES ('Governor H. Johnson');
INSERT INTO NormalizedPerson (name) VALUES ('Governor Martinez');
INSERT INTO NormalizedPerson (name) VALUES ('Governor of Coahuila and Texas');
INSERT INTO NormalizedPerson (name) VALUES ('Governor Rafael Gonzales');
INSERT INTO NormalizedPerson (name) VALUES ('Governor Viesca');
INSERT INTO NormalizedPerson (name) VALUES ('G. Pearce');
INSERT INTO NormalizedPerson (name) VALUES ('Grayson and Jack');
INSERT INTO NormalizedPerson (name) VALUES ('Green DeWitt');
INSERT INTO NormalizedPerson (name) VALUES ('G. W. and W. H. Whitaker');
INSERT INTO NormalizedPerson (name) VALUES ('G W Lovelace');
INSERT INTO NormalizedPerson (name) VALUES ('G. W. Treat');
INSERT INTO NormalizedPerson (name) VALUES ('H. A. Bullard');
INSERT INTO NormalizedPerson (name) VALUES ('Haden Edwards');
INSERT INTO NormalizedPerson (name) VALUES ('Hamiton N Yett and Alexr Calvit');
INSERT INTO NormalizedPerson (name) VALUES ('Hanna and Hawkins');
INSERT INTO NormalizedPerson (name) VALUES ('Hanson Alsbury');
INSERT INTO NormalizedPerson (name) VALUES ('Harrison and Hopkins');
INSERT INTO NormalizedPerson (name) VALUES ('Hart');
INSERT INTO NormalizedPerson (name) VALUES ('Hart, Barton and Hart');
INSERT INTO NormalizedPerson (name) VALUES ('H. Austin');
INSERT INTO NormalizedPerson (name) VALUES ('H. Connell');
INSERT INTO NormalizedPerson (name) VALUES ('H D Thompson');
INSERT INTO NormalizedPerson (name) VALUES ('Heerl and Pogue');
INSERT INTO NormalizedPerson (name) VALUES ('Henry Austin');
INSERT INTO NormalizedPerson (name) VALUES ('Henry Clay');
INSERT INTO NormalizedPerson (name) VALUES ('Henry Dodge');
INSERT INTO NormalizedPerson (name) VALUES ('Henry Elliot');
INSERT INTO NormalizedPerson (name) VALUES ('Henry Frost');
INSERT INTO NormalizedPerson (name) VALUES ('Henry Goold Shannon');
INSERT INTO NormalizedPerson (name) VALUES ('Henry Holstein');
INSERT INTO NormalizedPerson (name) VALUES ('Henry L Webb');
INSERT INTO NormalizedPerson (name) VALUES ('Henry Meigs');
INSERT INTO NormalizedPerson (name) VALUES ('Henry Morse');
INSERT INTO NormalizedPerson (name) VALUES ('Henry S. Brown');
INSERT INTO NormalizedPerson (name) VALUES ('Henry Smith');
INSERT INTO NormalizedPerson (name) VALUES ('Henry W. Munson');
INSERT INTO NormalizedPerson (name) VALUES ('H. H. League');
INSERT INTO NormalizedPerson (name) VALUES ('Hinton Curtis');
INSERT INTO NormalizedPerson (name) VALUES ('His mother and Sister');
INSERT INTO NormalizedPerson (name) VALUES ('H. J. Offutt');
INSERT INTO NormalizedPerson (name) VALUES ('H. Johnson');
INSERT INTO NormalizedPerson (name) VALUES ('H. Meigs');
INSERT INTO NormalizedPerson (name) VALUES ('Hockley and Bee');
INSERT INTO NormalizedPerson (name) VALUES ('Honey and Bates');
INSERT INTO NormalizedPerson (name) VALUES ('Horace Austin');
INSERT INTO NormalizedPerson (name) VALUES ('Horace Chrisman');
INSERT INTO NormalizedPerson (name) VALUES ('Horatio Alsberry');
INSERT INTO NormalizedPerson (name) VALUES ('Horatio Chriesman');
INSERT INTO NormalizedPerson (name) VALUES ('Horatio Reynolds');
INSERT INTO NormalizedPerson (name) VALUES ('Hotchkiss & Co');
INSERT INTO NormalizedPerson (name) VALUES ('Hugh B Johnston');
INSERT INTO NormalizedPerson (name) VALUES ('Hugh McGuffin');
INSERT INTO NormalizedPerson (name) VALUES ('Humphrey Jackson');
INSERT INTO NormalizedPerson (name) VALUES ('Humphry Fullerton');
INSERT INTO NormalizedPerson (name) VALUES ('Hyde and Merit');
INSERT INTO NormalizedPerson (name) VALUES ('Ignacio de Arispe');
INSERT INTO NormalizedPerson (name) VALUES ('Imla Keep, et. al.');
INSERT INTO NormalizedPerson (name) VALUES ('Inhabitants of Colony');
INSERT INTO NormalizedPerson (name) VALUES ('Inhabitants of Lavaca');
INSERT INTO NormalizedPerson (name) VALUES ('Inhabitants of Pecan Point');
INSERT INTO NormalizedPerson (name) VALUES ('Ira Ingram');
INSERT INTO NormalizedPerson (name) VALUES ('Ira R. Lewis');
INSERT INTO NormalizedPerson (name) VALUES ('Ireston C. Devan');
INSERT INTO NormalizedPerson (name) VALUES ('Isaac C. Oglem');
INSERT INTO NormalizedPerson (name) VALUES ('Isaac Jesses');
INSERT INTO NormalizedPerson (name) VALUES ('Isaac L. Baker');
INSERT INTO NormalizedPerson (name) VALUES ('Isaac Mathews');
INSERT INTO NormalizedPerson (name) VALUES ('Israel McGready');
INSERT INTO NormalizedPerson (name) VALUES ('Israel Waters');
INSERT INTO NormalizedPerson (name) VALUES ('Jacob Betts');
INSERT INTO NormalizedPerson (name) VALUES ('J. Allcorn');
INSERT INTO NormalizedPerson (name) VALUES ('James A. E. Phelps');
INSERT INTO NormalizedPerson (name) VALUES ('James Allcorn');
INSERT INTO NormalizedPerson (name) VALUES ('James and John Austin');
INSERT INTO NormalizedPerson (name) VALUES ('James Austin');
INSERT INTO NormalizedPerson (name) VALUES ('James Baird');
INSERT INTO NormalizedPerson (name) VALUES ('James Barnett');
INSERT INTO NormalizedPerson (name) VALUES ('James Beatty');
INSERT INTO NormalizedPerson (name) VALUES ('James Blythe');
INSERT INTO NormalizedPerson (name) VALUES ('James Bowie');
INSERT INTO NormalizedPerson (name) VALUES ('James Bowie and James Fannin');
INSERT INTO NormalizedPerson (name) VALUES ('James Bryan');
INSERT INTO NormalizedPerson (name) VALUES ('James Bryan and Mrs. Mary Austin');
INSERT INTO NormalizedPerson (name) VALUES ('James C. Carr');
INSERT INTO NormalizedPerson (name) VALUES ('James Clark');
INSERT INTO NormalizedPerson (name) VALUES ('James Collinsworth');
INSERT INTO NormalizedPerson (name) VALUES ('James Cox, Jr.');
INSERT INTO NormalizedPerson (name) VALUES ('James C. Shields');
INSERT INTO NormalizedPerson (name) VALUES ('James Cummins');
INSERT INTO NormalizedPerson (name) VALUES ('James Dill');
INSERT INTO NormalizedPerson (name) VALUES ('James E. B. Austin');
INSERT INTO NormalizedPerson (name) VALUES ('James E. B. Austin and John Austin');
INSERT INTO NormalizedPerson (name) VALUES ('James Evans');
INSERT INTO NormalizedPerson (name) VALUES ('James F and Emily Perry');
INSERT INTO NormalizedPerson (name) VALUES ('James Fannin');
INSERT INTO NormalizedPerson (name) VALUES ('James Farris');
INSERT INTO NormalizedPerson (name) VALUES ('James Fort Muse');
INSERT INTO NormalizedPerson (name) VALUES ('James F. Perry');
INSERT INTO NormalizedPerson (name) VALUES ('James Gaines');
INSERT INTO NormalizedPerson (name) VALUES ('James Gaines and J. E. B. Austin');
INSERT INTO NormalizedPerson (name) VALUES ('James Gallagher and Sons');
INSERT INTO NormalizedPerson (name) VALUES ('James Grant');
INSERT INTO NormalizedPerson (name) VALUES ('James Hamilton');
INSERT INTO NormalizedPerson (name) VALUES ('James Hepburn');
INSERT INTO NormalizedPerson (name) VALUES ('James Hewitson');
INSERT INTO NormalizedPerson (name) VALUES ('James Holloway');
INSERT INTO NormalizedPerson (name) VALUES ('James Hope');
INSERT INTO NormalizedPerson (name) VALUES ('James H. Penrose');
INSERT INTO NormalizedPerson (name) VALUES ('James Irwin');
INSERT INTO NormalizedPerson (name) VALUES ('James J. Ross');
INSERT INTO NormalizedPerson (name) VALUES ('James Kennerly');
INSERT INTO NormalizedPerson (name) VALUES ('James Kerr');
INSERT INTO NormalizedPerson (name) VALUES ('James Kerr and John Alley');
INSERT INTO NormalizedPerson (name) VALUES ('James Ladd');
INSERT INTO NormalizedPerson (name) VALUES ('James Maya and Company');
INSERT INTO NormalizedPerson (name) VALUES ('James Miller');
INSERT INTO NormalizedPerson (name) VALUES ('James Morgan');
INSERT INTO NormalizedPerson (name) VALUES ('James Nelson');
INSERT INTO NormalizedPerson (name) VALUES ('James Newell');
INSERT INTO NormalizedPerson (name) VALUES ('James Norton');
INSERT INTO NormalizedPerson (name) VALUES ('James P. Caldwell');
INSERT INTO NormalizedPerson (name) VALUES ('James Ramage');
INSERT INTO NormalizedPerson (name) VALUES ('James Ray');
INSERT INTO NormalizedPerson (name) VALUES ('James Richardson');
INSERT INTO NormalizedPerson (name) VALUES ('James R. Perry');
INSERT INTO NormalizedPerson (name) VALUES ('James Small');
INSERT INTO NormalizedPerson (name) VALUES ('James S. Ray');
INSERT INTO NormalizedPerson (name) VALUES ('James Staples');
INSERT INTO NormalizedPerson (name) VALUES ('James T. Dunbar and Others');
INSERT INTO NormalizedPerson (name) VALUES ('James Treat [?]');
INSERT INTO NormalizedPerson (name) VALUES ('James Treat');
INSERT INTO NormalizedPerson (name) VALUES ('James Tumlinson');
INSERT INTO NormalizedPerson (name) VALUES ('James W. Breedlove');
INSERT INTO NormalizedPerson (name) VALUES ('James W Fannin');
INSERT INTO NormalizedPerson (name) VALUES ('James Whiteside');
INSERT INTO NormalizedPerson (name) VALUES ('James Wilkinson');
INSERT INTO NormalizedPerson (name) VALUES ('James W. Jones');
INSERT INTO NormalizedPerson (name) VALUES ('J A Nixon');
INSERT INTO NormalizedPerson (name) VALUES ('Jared D Groce');
INSERT INTO NormalizedPerson (name) VALUES ('Jared E. Groce');
INSERT INTO NormalizedPerson (name) VALUES ('J. Austin');
INSERT INTO NormalizedPerson (name) VALUES ('J. A. Wharton et Al.');
INSERT INTO NormalizedPerson (name) VALUES ('J. B. Bailey');
INSERT INTO NormalizedPerson (name) VALUES ('J. Blair');
INSERT INTO NormalizedPerson (name) VALUES ('J. B. Miller');
INSERT INTO NormalizedPerson (name) VALUES ('J. Botts');
INSERT INTO NormalizedPerson (name) VALUES ('J. Bryant');
INSERT INTO NormalizedPerson (name) VALUES ('J. Cable');
INSERT INTO NormalizedPerson (name) VALUES ('J. Child');
INSERT INTO NormalizedPerson (name) VALUES ('J. C. Peyton');
INSERT INTO NormalizedPerson (name) VALUES ('J. D. Bludworth');
INSERT INTO NormalizedPerson (name) VALUES ('J.E.B. Austin and Stephen F. Austin');
INSERT INTO NormalizedPerson (name) VALUES ('J. Erwin');
INSERT INTO NormalizedPerson (name) VALUES ('Jessee Grimes');
INSERT INTO NormalizedPerson (name) VALUES ('Jesse Thompson');
INSERT INTO NormalizedPerson (name) VALUES ('Jesse Thompson and J. C. Payton');
INSERT INTO NormalizedPerson (name) VALUES ('Jesse Woodbury');
INSERT INTO NormalizedPerson (name) VALUES ('Jess Thompson');
INSERT INTO NormalizedPerson (name) VALUES ('J. F. Buchetti');
INSERT INTO NormalizedPerson (name) VALUES ('J. F. Perry');
INSERT INTO NormalizedPerson (name) VALUES ('J. G. McNeel');
INSERT INTO NormalizedPerson (name) VALUES ('J G Wright');
INSERT INTO NormalizedPerson (name) VALUES ('J H Bell');
INSERT INTO NormalizedPerson (name) VALUES ('J. H. Bell');
INSERT INTO NormalizedPerson (name) VALUES ('J. H. Hawkins');
INSERT INTO NormalizedPerson (name) VALUES ('J. H. Polley');
INSERT INTO NormalizedPerson (name) VALUES ('J. Hunter');
INSERT INTO NormalizedPerson (name) VALUES ('J. Iams');
INSERT INTO NormalizedPerson (name) VALUES ('J. Iiams');
INSERT INTO NormalizedPerson (name) VALUES ('J. J. Ross and A. C. Buckner');
INSERT INTO NormalizedPerson (name) VALUES ('J. J. Smith Jr. and Company');
INSERT INTO NormalizedPerson (name) VALUES ('J. L. Dumanday');
INSERT INTO NormalizedPerson (name) VALUES ('J. L Phillips');
INSERT INTO NormalizedPerson (name) VALUES ('J L Woodbuy');
INSERT INTO NormalizedPerson (name) VALUES ('J Mariano Guerra');
INSERT INTO NormalizedPerson (name) VALUES ('J. M. Arthur');
INSERT INTO NormalizedPerson (name) VALUES ('J. Meigs');
INSERT INTO NormalizedPerson (name) VALUES ('J Morgan');
INSERT INTO NormalizedPerson (name) VALUES ('J M Wolfe');
INSERT INTO NormalizedPerson (name) VALUES ('Joel R. Poinsett');
INSERT INTO NormalizedPerson (name) VALUES ('Joel Tatum');
INSERT INTO NormalizedPerson (name) VALUES ('John Adams');
INSERT INTO NormalizedPerson (name) VALUES ('John Andrews');
INSERT INTO NormalizedPerson (name) VALUES ('John A Storch');
INSERT INTO NormalizedPerson (name) VALUES ('John Austin');
INSERT INTO NormalizedPerson (name) VALUES ('John Austin and William Pettus');
INSERT INTO NormalizedPerson (name) VALUES ('John A Wharton');
INSERT INTO NormalizedPerson (name) VALUES ('John A. Williams');
INSERT INTO NormalizedPerson (name) VALUES ('John Beadbetter');
INSERT INTO NormalizedPerson (name) VALUES ('John Bigby');
INSERT INTO NormalizedPerson (name) VALUES ('John Blanchard and George Lauman');
INSERT INTO NormalizedPerson (name) VALUES ('John Botts');
INSERT INTO NormalizedPerson (name) VALUES ('John Bowman');
INSERT INTO NormalizedPerson (name) VALUES ('John Bradley');
INSERT INTO NormalizedPerson (name) VALUES ('John Brickey');
INSERT INTO NormalizedPerson (name) VALUES ('John Butler');
INSERT INTO NormalizedPerson (name) VALUES ('John B. Weller');
INSERT INTO NormalizedPerson (name) VALUES ('John Carr/ John Strowl');
INSERT INTO NormalizedPerson (name) VALUES ('John Castleman');
INSERT INTO NormalizedPerson (name) VALUES ('John C. Brickey');
INSERT INTO NormalizedPerson (name) VALUES ('John C. Harbison');
INSERT INTO NormalizedPerson (name) VALUES ('John Clark');
INSERT INTO NormalizedPerson (name) VALUES ('John Cooke');
INSERT INTO NormalizedPerson (name) VALUES ('John Crownover and Nancy Castleman');
INSERT INTO NormalizedPerson (name) VALUES ('John Cummings');
INSERT INTO NormalizedPerson (name) VALUES ('John C Walker');
INSERT INTO NormalizedPerson (name) VALUES ('John C. Walker');
INSERT INTO NormalizedPerson (name) VALUES ('John Davis Bradburn');
INSERT INTO NormalizedPerson (name) VALUES ('John D. Blanchard');
INSERT INTO NormalizedPerson (name) VALUES ('John D. Martin');
INSERT INTO NormalizedPerson (name) VALUES ('John Durst');
INSERT INTO NormalizedPerson (name) VALUES ('John F Guyard');
INSERT INTO NormalizedPerson (name) VALUES ('John Fisher');
INSERT INTO NormalizedPerson (name) VALUES ('John Fitzpatrick');
INSERT INTO NormalizedPerson (name) VALUES ('John Foster');
INSERT INTO NormalizedPerson (name) VALUES ('John Francis Merieult');
INSERT INTO NormalizedPerson (name) VALUES ('John G. Bond');
INSERT INTO NormalizedPerson (name) VALUES ('John Gibson');
INSERT INTO NormalizedPerson (name) VALUES ('John G. Purnell');
INSERT INTO NormalizedPerson (name) VALUES ('John Greig');
INSERT INTO NormalizedPerson (name) VALUES ('John Hawkins');
INSERT INTO NormalizedPerson (name) VALUES ('John H. Folwer, Jr.');
INSERT INTO NormalizedPerson (name) VALUES ('John H. Fowler');
INSERT INTO NormalizedPerson (name) VALUES ('John Hinkson');
INSERT INTO NormalizedPerson (name) VALUES ('John Iiams');
INSERT INTO NormalizedPerson (name) VALUES ('John Ingram');
INSERT INTO NormalizedPerson (name) VALUES ('John Irwin');
INSERT INTO NormalizedPerson (name) VALUES ('John J. Clarke');
INSERT INTO NormalizedPerson (name) VALUES ('John J Linn');
INSERT INTO NormalizedPerson (name) VALUES ('John K. Williams');
INSERT INTO NormalizedPerson (name) VALUES ('John L. Brickey');
INSERT INTO NormalizedPerson (name) VALUES ('John M. Arthur');
INSERT INTO NormalizedPerson (name) VALUES ('John M. Bernhisel');
INSERT INTO NormalizedPerson (name) VALUES ('John McArthur');
INSERT INTO NormalizedPerson (name) VALUES ('John McGaffey');
INSERT INTO NormalizedPerson (name) VALUES ('John McIntire');
INSERT INTO NormalizedPerson (name) VALUES ('John McNeel');
INSERT INTO NormalizedPerson (name) VALUES ('John M McCalla');
INSERT INTO NormalizedPerson (name) VALUES ('John P Austin');
INSERT INTO NormalizedPerson (name) VALUES ('John P. Coles');
INSERT INTO NormalizedPerson (name) VALUES ('John P. Sheldon');
INSERT INTO NormalizedPerson (name) VALUES ('John Randon');
INSERT INTO NormalizedPerson (name) VALUES ('John R. Harris');
INSERT INTO NormalizedPerson (name) VALUES ('John Rice Jones');
INSERT INTO NormalizedPerson (name) VALUES ('John R. Jones, Jr');
INSERT INTO NormalizedPerson (name) VALUES ('John Roe');
INSERT INTO NormalizedPerson (name) VALUES ('John R Starks');
INSERT INTO NormalizedPerson (name) VALUES ('John Ruland');
INSERT INTO NormalizedPerson (name) VALUES ('John S Brickley');
INSERT INTO NormalizedPerson (name) VALUES ('John Scott');
INSERT INTO NormalizedPerson (name) VALUES ('John Sibley');
INSERT INTO NormalizedPerson (name) VALUES ('John Smith');
INSERT INTO NormalizedPerson (name) VALUES ('John Smith T');
INSERT INTO NormalizedPerson (name) VALUES ('John Sprowl');
INSERT INTO NormalizedPerson (name) VALUES ('John Sprowl/ J T Gross');
INSERT INTO NormalizedPerson (name) VALUES ('John Stuart');
INSERT INTO NormalizedPerson (name) VALUES ('John S. Wills');
INSERT INTO NormalizedPerson (name) VALUES ('John T Criswell');
INSERT INTO NormalizedPerson (name) VALUES ('John T Mason');
INSERT INTO NormalizedPerson (name) VALUES ('John T. Mason');
INSERT INTO NormalizedPerson (name) VALUES ('John Tumlinson');
INSERT INTO NormalizedPerson (name) VALUES ('John W Faulkner');
INSERT INTO NormalizedPerson (name) VALUES ('John W. Hall');
INSERT INTO NormalizedPerson (name) VALUES ('John Woodruff');
INSERT INTO NormalizedPerson (name) VALUES ('John Woolsey');
INSERT INTO NormalizedPerson (name) VALUES ('Jonas Harrison');
INSERT INTO NormalizedPerson (name) VALUES ('Jonathan Rice Jones');
INSERT INTO NormalizedPerson (name) VALUES ('Jonathan Taylor and Company');
INSERT INTO NormalizedPerson (name) VALUES ('Jose Antonio Mexia');
INSERT INTO NormalizedPerson (name) VALUES ('Jose Antonio Navarro');
INSERT INTO NormalizedPerson (name) VALUES ('Jose Antonio Saucedo');
INSERT INTO NormalizedPerson (name) VALUES ('Jose Felix Trespalacios');
INSERT INTO NormalizedPerson (name) VALUES ('Joseph Burr');
INSERT INTO NormalizedPerson (name) VALUES ('Joseph D Grafton');
INSERT INTO NormalizedPerson (name) VALUES ('Joseph D\'uelle');
INSERT INTO NormalizedPerson (name) VALUES ('Joseph Ficklin');
INSERT INTO NormalizedPerson (name) VALUES ('Joseph Hertich');
INSERT INTO NormalizedPerson (name) VALUES ('Joseph H. Hawkins');
INSERT INTO NormalizedPerson (name) VALUES ('Joseph Kuykendall');
INSERT INTO NormalizedPerson (name) VALUES ('Joseph Maria D. Carbajal');
INSERT INTO NormalizedPerson (name) VALUES ('Joseph Nye and Sons');
INSERT INTO NormalizedPerson (name) VALUES ('Joseph Servison');
INSERT INTO NormalizedPerson (name) VALUES ('Joseph T. Montgomery');
INSERT INTO NormalizedPerson (name) VALUES ('Joseph W. Brown');
INSERT INTO NormalizedPerson (name) VALUES ('Joshua Marsh');
INSERT INTO NormalizedPerson (name) VALUES ('Joshua Pilcher');
INSERT INTO NormalizedPerson (name) VALUES ('Josiah Bell');
INSERT INTO NormalizedPerson (name) VALUES ('Josiah H Bell');
INSERT INTO NormalizedPerson (name) VALUES ('Josiah H. Bell');
INSERT INTO NormalizedPerson (name) VALUES ('Josiah H. Bell et al');
INSERT INTO NormalizedPerson (name) VALUES ('J. Pettit');
INSERT INTO NormalizedPerson (name) VALUES ('J R Bedford');
INSERT INTO NormalizedPerson (name) VALUES ('J. R. Poinsett');
INSERT INTO NormalizedPerson (name) VALUES ('J. Sargeant');
INSERT INTO NormalizedPerson (name) VALUES ('J. Tate');
INSERT INTO NormalizedPerson (name) VALUES ('J. Thomas');
INSERT INTO NormalizedPerson (name) VALUES ('Juan Davis Bradburn');
INSERT INTO NormalizedPerson (name) VALUES ('Juan Francicso Buchetti');
INSERT INTO NormalizedPerson (name) VALUES ('Juan Martin de Beramendi');
INSERT INTO NormalizedPerson (name) VALUES ('Junta Gobernativa');
INSERT INTO NormalizedPerson (name) VALUES ('Junta Instituyente');
INSERT INTO NormalizedPerson (name) VALUES ('J W Colliins');
INSERT INTO NormalizedPerson (name) VALUES ('J. W. Cooper');
INSERT INTO NormalizedPerson (name) VALUES ('J. W. Gready');
INSERT INTO NormalizedPerson (name) VALUES ('Keep, Groce, Stephen F Austin');
INSERT INTO NormalizedPerson (name) VALUES ('Kendall and Bates');
INSERT INTO NormalizedPerson (name) VALUES ('Kinchen Holliman');
INSERT INTO NormalizedPerson (name) VALUES ('Knight and White');
INSERT INTO NormalizedPerson (name) VALUES ('Lastraps and Desmare');
INSERT INTO NormalizedPerson (name) VALUES ('Lawrence Richard Kenny');
INSERT INTO NormalizedPerson (name) VALUES ('L. B. Hawkins');
INSERT INTO NormalizedPerson (name) VALUES ('L Brown');
INSERT INTO NormalizedPerson (name) VALUES ('Leander H McNeil');
INSERT INTO NormalizedPerson (name) VALUES ('Legislature');
INSERT INTO NormalizedPerson (name) VALUES ('Leonidas W. Baker');
INSERT INTO NormalizedPerson (name) VALUES ('Leroy Ferguson');
INSERT INTO NormalizedPerson (name) VALUES ('Lieutenant Governor DeLassus');
INSERT INTO NormalizedPerson (name) VALUES ('Littleberry Hawkins');
INSERT INTO NormalizedPerson (name) VALUES ('Louisiana Advertiser');
INSERT INTO NormalizedPerson (name) VALUES ('L. R. Kenney');
INSERT INTO NormalizedPerson (name) VALUES ('L Smither');
INSERT INTO NormalizedPerson (name) VALUES ('Lucas Alaman');
INSERT INTO NormalizedPerson (name) VALUES ('Lucas Van Buskirk');
INSERT INTO NormalizedPerson (name) VALUES ('Luciano Garcia');
INSERT INTO NormalizedPerson (name) VALUES ('Luke Lesassier');
INSERT INTO NormalizedPerson (name) VALUES ('L. V. Hawkins');
INSERT INTO NormalizedPerson (name) VALUES ('M A Bryan');
INSERT INTO NormalizedPerson (name) VALUES ('M. A. Bryan');
INSERT INTO NormalizedPerson (name) VALUES ('Maria Austin');
INSERT INTO NormalizedPerson (name) VALUES ('Martha Marple');
INSERT INTO NormalizedPerson (name) VALUES ('Martin');
INSERT INTO NormalizedPerson (name) VALUES ('Martin Allen');
INSERT INTO NormalizedPerson (name) VALUES ('Martin C. Allen');
INSERT INTO NormalizedPerson (name) VALUES ('Martin F Maher');
INSERT INTO NormalizedPerson (name) VALUES ('Martin F Maher and Company');
INSERT INTO NormalizedPerson (name) VALUES ('Mary Austin Holley');
INSERT INTO NormalizedPerson (name) VALUES ('Mary W. Ellis');
INSERT INTO NormalizedPerson (name) VALUES ('Mateo Ahumada');
INSERT INTO NormalizedPerson (name) VALUES ('Mathew Scobey');
INSERT INTO NormalizedPerson (name) VALUES ('Mathew Wilson');
INSERT INTO NormalizedPerson (name) VALUES ('Matthew G White');
INSERT INTO NormalizedPerson (name) VALUES ('Matthew Kerr');
INSERT INTO NormalizedPerson (name) VALUES ('M B Menard');
INSERT INTO NormalizedPerson (name) VALUES ('M B Nuckols');
INSERT INTO NormalizedPerson (name) VALUES ('McCormick');
INSERT INTO NormalizedPerson (name) VALUES ('McCoy and Scanlan');
INSERT INTO NormalizedPerson (name) VALUES ('McKinney and Williams');
INSERT INTO NormalizedPerson (name) VALUES ('McKinstry and Austin');
INSERT INTO NormalizedPerson (name) VALUES ('McNeil');
INSERT INTO NormalizedPerson (name) VALUES ('Members of Consultation');
INSERT INTO NormalizedPerson (name) VALUES ('Merle and Company');
INSERT INTO NormalizedPerson (name) VALUES ('Micajah Morris');
INSERT INTO NormalizedPerson (name) VALUES ('Michael Hart');
INSERT INTO NormalizedPerson (name) VALUES ('Miguel Arciniega');
INSERT INTO NormalizedPerson (name) VALUES ('Military Commandant');
INSERT INTO NormalizedPerson (name) VALUES ('Militia');
INSERT INTO NormalizedPerson (name) VALUES ('Militiamen');
INSERT INTO NormalizedPerson (name) VALUES ('Mills M Battle');
INSERT INTO NormalizedPerson (name) VALUES ('Mirabeau B. Lamar');
INSERT INTO NormalizedPerson (name) VALUES ('Missouri Legislature');
INSERT INTO NormalizedPerson (name) VALUES ('Missouri Territory Legislature');
INSERT INTO NormalizedPerson (name) VALUES ('M. M. Battle');
INSERT INTO NormalizedPerson (name) VALUES ('Morgan A Heard');
INSERT INTO NormalizedPerson (name) VALUES ('Morgan and Overton');
INSERT INTO NormalizedPerson (name) VALUES ('Morgan and Reed');
INSERT INTO NormalizedPerson (name) VALUES ('Moses and James Austin');
INSERT INTO NormalizedPerson (name) VALUES ('Moses and Stephen Austin');
INSERT INTO NormalizedPerson (name) VALUES ('Moses and Stephen F. Austin');
INSERT INTO NormalizedPerson (name) VALUES ('Moses Austin');
INSERT INTO NormalizedPerson (name) VALUES ('Moses Austin and George Lauman');
INSERT INTO NormalizedPerson (name) VALUES ('Moses Austin and Stephen F. Austin');
INSERT INTO NormalizedPerson (name) VALUES ('Moses Austin and William Shreve');
INSERT INTO NormalizedPerson (name) VALUES ('Moses Austin Bryan');
INSERT INTO NormalizedPerson (name) VALUES ('Moses Austin, John Blanchard, and Joe Lauman');
INSERT INTO NormalizedPerson (name) VALUES ('Moses Austin, Thomas Norvell, and Parsons Bates');
INSERT INTO NormalizedPerson (name) VALUES ('Moses Morrison');
INSERT INTO NormalizedPerson (name) VALUES ('Mozea Tousseau');
INSERT INTO NormalizedPerson (name) VALUES ('Mr Gray');
INSERT INTO NormalizedPerson (name) VALUES ('Mr Jinkins');
INSERT INTO NormalizedPerson (name) VALUES ('Mr Paskall');
INSERT INTO NormalizedPerson (name) VALUES ('Mrs. Emily Perry');
INSERT INTO NormalizedPerson (name) VALUES ('Mrs. G. A. Hawkins');
INSERT INTO NormalizedPerson (name) VALUES ('Mrs. James F. Perry');
INSERT INTO NormalizedPerson (name) VALUES ('Mrs J E B Austin');
INSERT INTO NormalizedPerson (name) VALUES ('Mrs. J. H. Hawkins [George Ann Hawkins]');
INSERT INTO NormalizedPerson (name) VALUES ('Mrs John Hall');
INSERT INTO NormalizedPerson (name) VALUES ('Mrs. Joseph H. Hawkins');
INSERT INTO NormalizedPerson (name) VALUES ('Mrs Mary Austin Holley');
INSERT INTO NormalizedPerson (name) VALUES ('M R Wiggington');
INSERT INTO NormalizedPerson (name) VALUES ('M. Slocum');
INSERT INTO NormalizedPerson (name) VALUES ('M. Wilkinson');
INSERT INTO NormalizedPerson (name) VALUES ('Nathaniel Cox');
INSERT INTO NormalizedPerson (name) VALUES ('Nathan Pusey');
INSERT INTO NormalizedPerson (name) VALUES ('N A Ware');
INSERT INTO NormalizedPerson (name) VALUES ('Nicholas Biddle');
INSERT INTO NormalizedPerson (name) VALUES ('Nicholas Clopper');
INSERT INTO NormalizedPerson (name) VALUES ('Nicholas Rightor');
INSERT INTO NormalizedPerson (name) VALUES ('Nicholas Whitehead');
INSERT INTO NormalizedPerson (name) VALUES ('none');
INSERT INTO NormalizedPerson (name) VALUES ('no recipient');
INSERT INTO NormalizedPerson (name) VALUES ('N. Rightor');
INSERT INTO NormalizedPerson (name) VALUES ('Oliver Hones');
INSERT INTO NormalizedPerson (name) VALUES ('Oliver Jones');
INSERT INTO NormalizedPerson (name) VALUES ('Oliver P Jackson');
INSERT INTO NormalizedPerson (name) VALUES ('Parish Gasquet and Company');
INSERT INTO NormalizedPerson (name) VALUES ('Pascal Detchemendy');
INSERT INTO NormalizedPerson (name) VALUES ('Patick and Lindsay Clopper');
INSERT INTO NormalizedPerson (name) VALUES ('Paul Dimmitt');
INSERT INTO NormalizedPerson (name) VALUES ('People');
INSERT INTO NormalizedPerson (name) VALUES ('People of Texas');
INSERT INTO NormalizedPerson (name) VALUES ('People of the Colony');
INSERT INTO NormalizedPerson (name) VALUES ('Permanent Council');
INSERT INTO NormalizedPerson (name) VALUES ('Perry and Hunter');
INSERT INTO NormalizedPerson (name) VALUES ('Perry and Somervell');
INSERT INTO NormalizedPerson (name) VALUES ('Perter J Menard');
INSERT INTO NormalizedPerson (name) VALUES ('Peter and Joseph Powell');
INSERT INTO NormalizedPerson (name) VALUES ('Peter Ellis Bean');
INSERT INTO NormalizedPerson (name) VALUES ('Peter Le Croix');
INSERT INTO NormalizedPerson (name) VALUES ('Peter Love');
INSERT INTO NormalizedPerson (name) VALUES ('Peter Menard');
INSERT INTO NormalizedPerson (name) VALUES ('Peter W. Love');
INSERT INTO NormalizedPerson (name) VALUES ('Petter Menard');
INSERT INTO NormalizedPerson (name) VALUES ('Philip T. Dimmitt');
INSERT INTO NormalizedPerson (name) VALUES ('Phillip Reddinger');
INSERT INTO NormalizedPerson (name) VALUES ('Phineas Smith');
INSERT INTO NormalizedPerson (name) VALUES ('Pierre Delassus De Luziere');
INSERT INTO NormalizedPerson (name) VALUES ('Pierre Laforge');
INSERT INTO NormalizedPerson (name) VALUES ('P. M. Guin');
INSERT INTO NormalizedPerson (name) VALUES ('Powers of Commissioners to Waco Indians');
INSERT INTO NormalizedPerson (name) VALUES ('P Powell');
INSERT INTO NormalizedPerson (name) VALUES ('President of the Consultation');
INSERT INTO NormalizedPerson (name) VALUES ('President of the Provisional Government of Texas');
INSERT INTO NormalizedPerson (name) VALUES ('Provincial Deputation');
INSERT INTO NormalizedPerson (name) VALUES ('Provisional Government of Texas');
INSERT INTO NormalizedPerson (name) VALUES ('Provisional Governor');
INSERT INTO NormalizedPerson (name) VALUES ('P. S. Decherd');
INSERT INTO NormalizedPerson (name) VALUES ('P S le Hicks');
INSERT INTO NormalizedPerson (name) VALUES ('P. S. Slocum');
INSERT INTO NormalizedPerson (name) VALUES ('P. T. Dimmitt');
INSERT INTO NormalizedPerson (name) VALUES ('Public');
INSERT INTO NormalizedPerson (name) VALUES ('P W Grayson');
INSERT INTO NormalizedPerson (name) VALUES ('P W Grayson et Al');
INSERT INTO NormalizedPerson (name) VALUES ('Rafael Gonzales');
INSERT INTO NormalizedPerson (name) VALUES ('Rafae Llanos');
INSERT INTO NormalizedPerson (name) VALUES ('Raleigh');
INSERT INTO NormalizedPerson (name) VALUES ('Ramon Musquiz');
INSERT INTO NormalizedPerson (name) VALUES ('Randall Jones');
INSERT INTO NormalizedPerson (name) VALUES ('Rawson Alley');
INSERT INTO NormalizedPerson (name) VALUES ('R. Carpenter');
INSERT INTO NormalizedPerson (name) VALUES ('R. C. Bruffey');
INSERT INTO NormalizedPerson (name) VALUES ('R C Langdon');
INSERT INTO NormalizedPerson (name) VALUES ('R C Nicholas');
INSERT INTO NormalizedPerson (name) VALUES ('Residents of Texas');
INSERT INTO NormalizedPerson (name) VALUES ('R. Hawes');
INSERT INTO NormalizedPerson (name) VALUES ('Richard Ellis');
INSERT INTO NormalizedPerson (name) VALUES ('Richard Fields');
INSERT INTO NormalizedPerson (name) VALUES ('Richard Hawes');
INSERT INTO NormalizedPerson (name) VALUES ('Richard R Royall');
INSERT INTO NormalizedPerson (name) VALUES ('Richard Thurmond');
INSERT INTO NormalizedPerson (name) VALUES ('Richared Ellis et al');
INSERT INTO NormalizedPerson (name) VALUES ('R M Carwright');
INSERT INTO NormalizedPerson (name) VALUES ('R M Johnson');
INSERT INTO NormalizedPerson (name) VALUES ('R. M. Williamson');
INSERT INTO NormalizedPerson (name) VALUES ('Robert Andrews');
INSERT INTO NormalizedPerson (name) VALUES ('Robert Brooke');
INSERT INTO NormalizedPerson (name) VALUES ('Robert Brotherton and James McNair');
INSERT INTO NormalizedPerson (name) VALUES ('Robert C. Bruffy');
INSERT INTO NormalizedPerson (name) VALUES ('Robert Collet');
INSERT INTO NormalizedPerson (name) VALUES ('Robert D. Dawson');
INSERT INTO NormalizedPerson (name) VALUES ('Robert Desha');
INSERT INTO NormalizedPerson (name) VALUES ('Robert Kuykendall');
INSERT INTO NormalizedPerson (name) VALUES ('Robert Leftwich');
INSERT INTO NormalizedPerson (name) VALUES ('Robert Leftwich or Haden Edwards');
INSERT INTO NormalizedPerson (name) VALUES ('Robert Lewis');
INSERT INTO NormalizedPerson (name) VALUES ('Robert Lewis, Stephen F Austin, Jose Antonio Saucedo');
INSERT INTO NormalizedPerson (name) VALUES ('Robert M Williamson');
INSERT INTO NormalizedPerson (name) VALUES ('Robert Peebles');
INSERT INTO NormalizedPerson (name) VALUES ('Robert Pogue');
INSERT INTO NormalizedPerson (name) VALUES ('Robert S. Todd');
INSERT INTO NormalizedPerson (name) VALUES ('Robert T. Conrad');
INSERT INTO NormalizedPerson (name) VALUES ('Robert Triplett');
INSERT INTO NormalizedPerson (name) VALUES ('Robert Wash');
INSERT INTO NormalizedPerson (name) VALUES ('Robert Wescott');
INSERT INTO NormalizedPerson (name) VALUES ('Robert Williams');
INSERT INTO NormalizedPerson (name) VALUES ('Robert Wilson');
INSERT INTO NormalizedPerson (name) VALUES ('Roswell Mills');
INSERT INTO NormalizedPerson (name) VALUES ('Rovert Westcott');
INSERT INTO NormalizedPerson (name) VALUES ('R. P. Guyard');
INSERT INTO NormalizedPerson (name) VALUES ('R. R. Royall');
INSERT INTO NormalizedPerson (name) VALUES ('R R Royall and Austin');
INSERT INTO NormalizedPerson (name) VALUES ('R R Royall and S. Rhoads Fisher');
INSERT INTO NormalizedPerson (name) VALUES ('R Salmon');
INSERT INTO NormalizedPerson (name) VALUES ('R Semple');
INSERT INTO NormalizedPerson (name) VALUES ('R Stowers');
INSERT INTO NormalizedPerson (name) VALUES ('Rufus Easton');
INSERT INTO NormalizedPerson (name) VALUES ('S. A. Anderson');
INSERT INTO NormalizedPerson (name) VALUES ('Sam C. Carter and Benjamin Fowler');
INSERT INTO NormalizedPerson (name) VALUES ('Sameul M Williams');
INSERT INTO NormalizedPerson (name) VALUES ('Sam Houston');
INSERT INTO NormalizedPerson (name) VALUES ('Sam McCraw');
INSERT INTO NormalizedPerson (name) VALUES ('Sam Perry');
INSERT INTO NormalizedPerson (name) VALUES ('Sam Perry and Company');
INSERT INTO NormalizedPerson (name) VALUES ('Sam Sexton');
INSERT INTO NormalizedPerson (name) VALUES ('Samuel A. Cartwright');
INSERT INTO NormalizedPerson (name) VALUES ('Samuel and Elizabeth Pharr');
INSERT INTO NormalizedPerson (name) VALUES ('Samuel Ayers and Others');
INSERT INTO NormalizedPerson (name) VALUES ('Samuel Bridge');
INSERT INTO NormalizedPerson (name) VALUES ('Samuel C. Hirams');
INSERT INTO NormalizedPerson (name) VALUES ('Samuel Crawford');
INSERT INTO NormalizedPerson (name) VALUES ('Samuel Dixon');
INSERT INTO NormalizedPerson (name) VALUES ('Samuel Ellis');
INSERT INTO NormalizedPerson (name) VALUES ('Samuel Houston');
INSERT INTO NormalizedPerson (name) VALUES ('Samuel M. Williams');
INSERT INTO NormalizedPerson (name) VALUES ('Samuel Norris');
INSERT INTO NormalizedPerson (name) VALUES ('Samuel Parker');
INSERT INTO NormalizedPerson (name) VALUES ('Samuel Parkman');
INSERT INTO NormalizedPerson (name) VALUES ('Samuel Ricker, Jr.');
INSERT INTO NormalizedPerson (name) VALUES ('Samuel R. Ober');
INSERT INTO NormalizedPerson (name) VALUES ('Samuel Sexton');
INSERT INTO NormalizedPerson (name) VALUES ('Samuel Sexton and Charles Morgan');
INSERT INTO NormalizedPerson (name) VALUES ('Samuel Sheares');
INSERT INTO NormalizedPerson (name) VALUES ('Samuel S. Pearson');
INSERT INTO NormalizedPerson (name) VALUES ('Samuel Swartwout');
INSERT INTO NormalizedPerson (name) VALUES ('Samuel T. Angier');
INSERT INTO NormalizedPerson (name) VALUES ('Samuel Williams');
INSERT INTO NormalizedPerson (name) VALUES ('Samuel W. Mullin');
INSERT INTO NormalizedPerson (name) VALUES ('Santa Anna');
INSERT INTO NormalizedPerson (name) VALUES ('S B Dickinson');
INSERT INTO NormalizedPerson (name) VALUES ('S. C. Hirams');
INSERT INTO NormalizedPerson (name) VALUES ('Schooner Lively');
INSERT INTO NormalizedPerson (name) VALUES ('S. Dooley');
INSERT INTO NormalizedPerson (name) VALUES ('Secretary of Relations');
INSERT INTO NormalizedPerson (name) VALUES ('Senator L F Linn');
INSERT INTO NormalizedPerson (name) VALUES ('Seth Ingram');
INSERT INTO NormalizedPerson (name) VALUES ('Seth M. Hunt');
INSERT INTO NormalizedPerson (name) VALUES ('S. Hammond');
INSERT INTO NormalizedPerson (name) VALUES ('S Hatch');
INSERT INTO NormalizedPerson (name) VALUES ('Sheriff of the Colony');
INSERT INTO NormalizedPerson (name) VALUES ('S H Everett');
INSERT INTO NormalizedPerson (name) VALUES ('Simpson and Quarles');
INSERT INTO NormalizedPerson (name) VALUES ('S. M. Williams');
INSERT INTO NormalizedPerson (name) VALUES ('Solomon Dally');
INSERT INTO NormalizedPerson (name) VALUES ('Solomon R. Bolin');
INSERT INTO NormalizedPerson (name) VALUES ('S Perry and Company');
INSERT INTO NormalizedPerson (name) VALUES ('S Rhoades Fisher');
INSERT INTO NormalizedPerson (name) VALUES ('S Sawyer');
INSERT INTO NormalizedPerson (name) VALUES ('S. T. Angier');
INSERT INTO NormalizedPerson (name) VALUES ('State Congress');
INSERT INTO NormalizedPerson (name) VALUES ('State of Kentucky');
INSERT INTO NormalizedPerson (name) VALUES ('State of Missouri');
INSERT INTO NormalizedPerson (name) VALUES ('State of New York');
INSERT INTO NormalizedPerson (name) VALUES ('Stephen Ashton');
INSERT INTO NormalizedPerson (name) VALUES ('Stephen F. Austin');
INSERT INTO NormalizedPerson (name) VALUES ('Stephen F. Austin and Company');
INSERT INTO NormalizedPerson (name) VALUES ('Stephen F Austin and Samuel Houston');
INSERT INTO NormalizedPerson (name) VALUES ('Stephen F Austin and William H Wharton');
INSERT INTO NormalizedPerson (name) VALUES ('Stephen F Austin and William Wharton');
INSERT INTO NormalizedPerson (name) VALUES ('Stephen F Austin. Branch T Archer');
INSERT INTO NormalizedPerson (name) VALUES ('Stephen F Austin, Branch T Archer, and William H Wharton');
INSERT INTO NormalizedPerson (name) VALUES ('Stephen F Austin, Branch T Archer, and William Wharton');
INSERT INTO NormalizedPerson (name) VALUES ('Stephen F. Austin et al');
INSERT INTO NormalizedPerson (name) VALUES ('Stephen Holmes');
INSERT INTO NormalizedPerson (name) VALUES ('Sterling C Tobertson');
INSERT INTO NormalizedPerson (name) VALUES ('Sumner Bacon');
INSERT INTO NormalizedPerson (name) VALUES ('Susan W. Maxwell');
INSERT INTO NormalizedPerson (name) VALUES ('Sylvanus Castleman');
INSERT INTO NormalizedPerson (name) VALUES ('Sylvester Murphy');
INSERT INTO NormalizedPerson (name) VALUES ('Tacitus Clay');
INSERT INTO NormalizedPerson (name) VALUES ('Taylor Wilkins and Company');
INSERT INTO NormalizedPerson (name) VALUES ('Texas Army');
INSERT INTO NormalizedPerson (name) VALUES ('Texas Gazette');
INSERT INTO NormalizedPerson (name) VALUES ('T. Farelly');
INSERT INTO NormalizedPerson (name) VALUES ('Thomas Barnett');
INSERT INTO NormalizedPerson (name) VALUES ('Thomas B. Bell, et al.');
INSERT INTO NormalizedPerson (name) VALUES ('Thomas Carter');
INSERT INTO NormalizedPerson (name) VALUES ('Thomas C. Banks');
INSERT INTO NormalizedPerson (name) VALUES ('Thomas Corwin');
INSERT INTO NormalizedPerson (name) VALUES ('Thomas Darle');
INSERT INTO NormalizedPerson (name) VALUES ('Thomas Davis');
INSERT INTO NormalizedPerson (name) VALUES ('Thomas F Leaming');
INSERT INTO NormalizedPerson (name) VALUES ('Thomas F. McKinney');
INSERT INTO NormalizedPerson (name) VALUES ('Thomas Gray');
INSERT INTO NormalizedPerson (name) VALUES ('Thomas G Western');
INSERT INTO NormalizedPerson (name) VALUES ('Thomas G Western and Others');
INSERT INTO NormalizedPerson (name) VALUES ('Thomas H Benton');
INSERT INTO NormalizedPerson (name) VALUES ('Thomas H Borden');
INSERT INTO NormalizedPerson (name) VALUES ('Thomas H. Ficklin');
INSERT INTO NormalizedPerson (name) VALUES ('Thomas Hockley');
INSERT INTO NormalizedPerson (name) VALUES ('Thomas Hooper');
INSERT INTO NormalizedPerson (name) VALUES ('Thomas Jamison');
INSERT INTO NormalizedPerson (name) VALUES ('Thomas Jefferson Chambers');
INSERT INTO NormalizedPerson (name) VALUES ('Thomas J Pilgrim');
INSERT INTO NormalizedPerson (name) VALUES ('Thomas J Rusk');
INSERT INTO NormalizedPerson (name) VALUES ('Thomas M. Duke');
INSERT INTO NormalizedPerson (name) VALUES ('Thomas Norvell');
INSERT INTO NormalizedPerson (name) VALUES ('Thomas O Meaux');
INSERT INTO NormalizedPerson (name) VALUES ('Thomas P. Hart');
INSERT INTO NormalizedPerson (name) VALUES ('Thomas Powell');
INSERT INTO NormalizedPerson (name) VALUES ('Thomas R Leaming');
INSERT INTO NormalizedPerson (name) VALUES ('Thomas Ruston');
INSERT INTO NormalizedPerson (name) VALUES ('Thomas Todd');
INSERT INTO NormalizedPerson (name) VALUES ('Thomas Westall');
INSERT INTO NormalizedPerson (name) VALUES ('Thomas White');
INSERT INTO NormalizedPerson (name) VALUES ('Timothy Flint');
INSERT INTO NormalizedPerson (name) VALUES ('Timothy Phelps');
INSERT INTO NormalizedPerson (name) VALUES ('Toby and Brother');
INSERT INTO NormalizedPerson (name) VALUES ('T. [or J.] Reilly');
INSERT INTO NormalizedPerson (name) VALUES ('Unknown');
INSERT INTO NormalizedPerson (name) VALUES ('Unsent');
INSERT INTO NormalizedPerson (name) VALUES ('U. S. Consul');
INSERT INTO NormalizedPerson (name) VALUES ('Various New Orleans firms');
INSERT INTO NormalizedPerson (name) VALUES ('Victor Blanco');
INSERT INTO NormalizedPerson (name) VALUES ('Volunteers at Bexar');
INSERT INTO NormalizedPerson (name) VALUES ('V. W. Love');
INSERT INTO NormalizedPerson (name) VALUES ('Waco Indians');
INSERT INTO NormalizedPerson (name) VALUES ('W A Ficklin');
INSERT INTO NormalizedPerson (name) VALUES ('Walter C. White');
INSERT INTO NormalizedPerson (name) VALUES ('Walter Turnbull');
INSERT INTO NormalizedPerson (name) VALUES ('Warren Buford');
INSERT INTO NormalizedPerson (name) VALUES ('Warren D. C. Hall');
INSERT INTO NormalizedPerson (name) VALUES ('Warren D C Hall and James R Phelps');
INSERT INTO NormalizedPerson (name) VALUES ('Washington Hotel');
INSERT INTO NormalizedPerson (name) VALUES ('W B Allen');
INSERT INTO NormalizedPerson (name) VALUES ('W. B. Travis');
INSERT INTO NormalizedPerson (name) VALUES ('W. Bullock');
INSERT INTO NormalizedPerson (name) VALUES ('W. Carothers');
INSERT INTO NormalizedPerson (name) VALUES ('W. Christy');
INSERT INTO NormalizedPerson (name) VALUES ('W C Whitaker');
INSERT INTO NormalizedPerson (name) VALUES ('W D C Hall');
INSERT INTO NormalizedPerson (name) VALUES ('W D Dunlap');
INSERT INTO NormalizedPerson (name) VALUES ('W. G. Whiteside');
INSERT INTO NormalizedPerson (name) VALUES ('W. H. Wharton and Thos. Hastings');
INSERT INTO NormalizedPerson (name) VALUES ('Wilkins and Catron');
INSERT INTO NormalizedPerson (name) VALUES ('Willaim Bunaugh');
INSERT INTO NormalizedPerson (name) VALUES ('Willaim Williams');
INSERT INTO NormalizedPerson (name) VALUES ('William and Andrew Rabb');
INSERT INTO NormalizedPerson (name) VALUES ('William Anderson');
INSERT INTO NormalizedPerson (name) VALUES ('William Ashbrook');
INSERT INTO NormalizedPerson (name) VALUES ('William A. Sheldon');
INSERT INTO NormalizedPerson (name) VALUES ('William Austin');
INSERT INTO NormalizedPerson (name) VALUES ('William Blanks');
INSERT INTO NormalizedPerson (name) VALUES ('William B Lewis');
INSERT INTO NormalizedPerson (name) VALUES ('William Bloodgood');
INSERT INTO NormalizedPerson (name) VALUES ('William Brenaugh');
INSERT INTO NormalizedPerson (name) VALUES ('William Bryan');
INSERT INTO NormalizedPerson (name) VALUES ('William B. Travis');
INSERT INTO NormalizedPerson (name) VALUES ('William Carroll');
INSERT INTO NormalizedPerson (name) VALUES ('William C Carpenter');
INSERT INTO NormalizedPerson (name) VALUES ('William C Carr');
INSERT INTO NormalizedPerson (name) VALUES ('William Cooper');
INSERT INTO NormalizedPerson (name) VALUES ('William Eads');
INSERT INTO NormalizedPerson (name) VALUES ('William E. Woodruff');
INSERT INTO NormalizedPerson (name) VALUES ('William Ficklin');
INSERT INTO NormalizedPerson (name) VALUES ('William F. Roberts');
INSERT INTO NormalizedPerson (name) VALUES ('William G Hall');
INSERT INTO NormalizedPerson (name) VALUES ('William Hall');
INSERT INTO NormalizedPerson (name) VALUES ('William Harris');
INSERT INTO NormalizedPerson (name) VALUES ('William H. Ashley');
INSERT INTO NormalizedPerson (name) VALUES ('William H Jack');
INSERT INTO NormalizedPerson (name) VALUES ('William H Skerrett');
INSERT INTO NormalizedPerson (name) VALUES ('William H Wharton');
INSERT INTO NormalizedPerson (name) VALUES ('William Johnson');
INSERT INTO NormalizedPerson (name) VALUES ('William Kennert and Company');
INSERT INTO NormalizedPerson (name) VALUES ('William Kincheloe');
INSERT INTO NormalizedPerson (name) VALUES ('William Kingheloe');
INSERT INTO NormalizedPerson (name) VALUES ('William Laughlin');
INSERT INTO NormalizedPerson (name) VALUES ('William Little');
INSERT INTO NormalizedPerson (name) VALUES ('William McNair');
INSERT INTO NormalizedPerson (name) VALUES ('William M. O\'Hara');
INSERT INTO NormalizedPerson (name) VALUES ('William Morrison');
INSERT INTO NormalizedPerson (name) VALUES ('William Morse');
INSERT INTO NormalizedPerson (name) VALUES ('William Morton');
INSERT INTO NormalizedPerson (name) VALUES ('William N. Henderson');
INSERT INTO NormalizedPerson (name) VALUES ('William Perry');
INSERT INTO NormalizedPerson (name) VALUES ('William Pettus');
INSERT INTO NormalizedPerson (name) VALUES ('William P Harris');
INSERT INTO NormalizedPerson (name) VALUES ('William P Harris and John W Moore');
INSERT INTO NormalizedPerson (name) VALUES ('William P. Perkins');
INSERT INTO NormalizedPerson (name) VALUES ('William Rabb');
INSERT INTO NormalizedPerson (name) VALUES ('William Reed');
INSERT INTO NormalizedPerson (name) VALUES ('William S. Archer');
INSERT INTO NormalizedPerson (name) VALUES ('William S. Brown');
INSERT INTO NormalizedPerson (name) VALUES ('William Scott');
INSERT INTO NormalizedPerson (name) VALUES ('William Selkirk');
INSERT INTO NormalizedPerson (name) VALUES ('William S. Fisher');
INSERT INTO NormalizedPerson (name) VALUES ('William S. Hall');
INSERT INTO NormalizedPerson (name) VALUES ('William Shreve');
INSERT INTO NormalizedPerson (name) VALUES ('William S. Lewis');
INSERT INTO NormalizedPerson (name) VALUES ('William Smith');
INSERT INTO NormalizedPerson (name) VALUES ('William S. Parrott');
INSERT INTO NormalizedPerson (name) VALUES ('William Stafford');
INSERT INTO NormalizedPerson (name) VALUES ('William T Austin');
INSERT INTO NormalizedPerson (name) VALUES ('William Trimble');
INSERT INTO NormalizedPerson (name) VALUES ('William Vince');
INSERT INTO NormalizedPerson (name) VALUES ('William W Alsbury');
INSERT INTO NormalizedPerson (name) VALUES ('William W Lea');
INSERT INTO NormalizedPerson (name) VALUES ('William W. Little');
INSERT INTO NormalizedPerson (name) VALUES ('William W Morris');
INSERT INTO NormalizedPerson (name) VALUES ('Wily Martin');
INSERT INTO NormalizedPerson (name) VALUES ('W. J. Powell');
INSERT INTO NormalizedPerson (name) VALUES ('W. McFarland');
INSERT INTO NormalizedPerson (name) VALUES ('W P Hill');
INSERT INTO NormalizedPerson (name) VALUES ('W P Smith et Al');
INSERT INTO NormalizedPerson (name) VALUES ('W. Richardson');
INSERT INTO NormalizedPerson (name) VALUES ('W. S. Archer');
INSERT INTO NormalizedPerson (name) VALUES ('W. S. Hall?');
INSERT INTO NormalizedPerson (name) VALUES ('W. S. Parrott');
INSERT INTO NormalizedPerson (name) VALUES ('W. Stevenson');
INSERT INTO NormalizedPerson (name) VALUES ('W. Sutherland');
INSERT INTO NormalizedPerson (name) VALUES ('W Taylor');
INSERT INTO NormalizedPerson (name) VALUES ('W. W. Hunter');
INSERT INTO NormalizedPerson (name) VALUES ('Wyatt Hanks');
INSERT INTO NormalizedPerson (name) VALUES ('Wyly Martin');
INSERT INTO NormalizedPerson (name) VALUES ('Wyly Martin et al');
INSERT INTO NormalizedPerson (name) VALUES ('Yeatman and Anderson');
INSERT INTO NormalizedPerson (name) VALUES ('Y. M. Daniel');
INSERT INTO NormalizedPerson (name) VALUES ('Zacharie and Company');
INSERT INTO NormalizedPerson (name) VALUES ('Zenas Priest');
INSERT INTO NormalizedPerson (name) VALUES ('Zeno Phillips');
