concat('INSERT INTO NormalizedPerson (name) VALUES (\'', trim(substr(title, locate(' to ', title)+3, locate(',', title)-locate(' to ', title)-3)), '\');')
INSERT INTO NormalizedPerson (name) VALUES ('');
INSERT INTO NormalizedPerson (name) VALUES ('A J Harris');
INSERT INTO NormalizedPerson (name) VALUES ('A J Yates');
INSERT INTO NormalizedPerson (name) VALUES ('A. G. Wavell');
INSERT INTO NormalizedPerson (name) VALUES ('A. McNair and Stephen F. Austin');
INSERT INTO NormalizedPerson (name) VALUES ('A. Robinson');
INSERT INTO NormalizedPerson (name) VALUES ('Aaron Elliot');
INSERT INTO NormalizedPerson (name) VALUES ('Aaron Elliott');
INSERT INTO NormalizedPerson (name) VALUES ('Absolom Johnson');
INSERT INTO NormalizedPerson (name) VALUES ('Adner Kuykendall');
INSERT INTO NormalizedPerson (name) VALUES ('Ahumada');
INSERT INTO NormalizedPerson (name) VALUES ('Albert Gallatin');
INSERT INTO NormalizedPerson (name) VALUES ('Alcade of San Felipe');
INSERT INTO NormalizedPerson (name) VALUES ('Alcalde of Gonzales');
INSERT INTO NormalizedPerson (name) VALUES ('Alcalde of San Felipe');
INSERT INTO NormalizedPerson (name) VALUES ('Alcalde');
INSERT INTO NormalizedPerson (name) VALUES ('Alex McNair');
INSERT INTO NormalizedPerson (name) VALUES ('Alexander Frazer');
INSERT INTO NormalizedPerson (name) VALUES ('Alexander Jackson');
INSERT INTO NormalizedPerson (name) VALUES ('Alexenander Calvit');
INSERT INTO NormalizedPerson (name) VALUES ('American Hotel');
INSERT INTO NormalizedPerson (name) VALUES ('Amos Rawls');
INSERT INTO NormalizedPerson (name) VALUES ('Anastacio Bustamante');
INSERT INTO NormalizedPerson (name) VALUES ('Andrew Henry');
INSERT INTO NormalizedPerson (name) VALUES ('Andrew Jackson');
INSERT INTO NormalizedPerson (name) VALUES ('Andrew Mitchell');
INSERT INTO NormalizedPerson (name) VALUES ('Andrew Roberson');
INSERT INTO NormalizedPerson (name) VALUES ('Andrew Robinson');
INSERT INTO NormalizedPerson (name) VALUES ('Anthony Butler');
INSERT INTO NormalizedPerson (name) VALUES ('Antoine Soulard');
INSERT INTO NormalizedPerson (name) VALUES ('Antonio Martinez');
INSERT INTO NormalizedPerson (name) VALUES ('Archilbald Austin');
INSERT INTO NormalizedPerson (name) VALUES ('Arthur G. Wavell');
INSERT INTO NormalizedPerson (name) VALUES ('Asa Brigham and J S D Byrom');
INSERT INTO NormalizedPerson (name) VALUES ('Authorities of La Bahia');
INSERT INTO NormalizedPerson (name) VALUES ('Ayunatmiento of San Felipe');
INSERT INTO NormalizedPerson (name) VALUES ('Ayuntamiento of Bexar');
INSERT INTO NormalizedPerson (name) VALUES ('Ayuntamiento of San Felipe');
INSERT INTO NormalizedPerson (name) VALUES ('Ayuntamiento of San Fellipe');
INSERT INTO NormalizedPerson (name) VALUES ('Ayuntamineto of Nacogdoches');
INSERT INTO NormalizedPerson (name) VALUES ('B. W. Edwards');
INSERT INTO NormalizedPerson (name) VALUES ('Baron de Bastrop');
INSERT INTO NormalizedPerson (name) VALUES ('Bartlett Sims');
INSERT INTO NormalizedPerson (name) VALUES ('Bellows and Cochran');
INSERT INTO NormalizedPerson (name) VALUES ('Benjamin Fowler');
INSERT INTO NormalizedPerson (name) VALUES ('Berry and Battle Dr.');
INSERT INTO NormalizedPerson (name) VALUES ('Branch T Archer');
INSERT INTO NormalizedPerson (name) VALUES ('Bustamente');
INSERT INTO NormalizedPerson (name) VALUES ('Captain Dickson');
INSERT INTO NormalizedPerson (name) VALUES ('Captain Dillard');
INSERT INTO NormalizedPerson (name) VALUES ('Captains');
INSERT INTO NormalizedPerson (name) VALUES ('Captian Richard Fields');
INSERT INTO NormalizedPerson (name) VALUES ('Carbajal's Mother');
INSERT INTO NormalizedPerson (name) VALUES ('Carlos Garcia');
INSERT INTO NormalizedPerson (name) VALUES ('Central Committee');
INSERT INTO NormalizedPerson (name) VALUES ('Chapman');
INSERT INTO NormalizedPerson (name) VALUES ('Charles Austin');
INSERT INTO NormalizedPerson (name) VALUES ('Charles McDormitt');
INSERT INTO NormalizedPerson (name) VALUES ('Cherokee Chiefs');
INSERT INTO NormalizedPerson (name) VALUES ('Christian Wilt');
INSERT INTO NormalizedPerson (name) VALUES ('Citizens of Jefferson County');
INSERT INTO NormalizedPerson (name) VALUES ('Citizens of Mina');
INSERT INTO NormalizedPerson (name) VALUES ('Collinsworth and Grayson');
INSERT INTO NormalizedPerson (name) VALUES ('Colonel Charles Caldwell');
INSERT INTO NormalizedPerson (name) VALUES ('Colonel Lewis');
INSERT INTO NormalizedPerson (name) VALUES ('Colonists');
INSERT INTO NormalizedPerson (name) VALUES ('Colonlists');
INSERT INTO NormalizedPerson (name) VALUES ('Colony');
INSERT INTO NormalizedPerson (name) VALUES ('Colorado District');
INSERT INTO NormalizedPerson (name) VALUES ('Columbia Committee');
INSERT INTO NormalizedPerson (name) VALUES ('Comittee of Safety of San Felipe');
INSERT INTO NormalizedPerson (name) VALUES ('Committee at Convention');
INSERT INTO NormalizedPerson (name) VALUES ('Committee of Harrisburgh');
INSERT INTO NormalizedPerson (name) VALUES ('Committee of San Felipe');
INSERT INTO NormalizedPerson (name) VALUES ('Committees of Nacogdoches and San Augustine');
INSERT INTO NormalizedPerson (name) VALUES ('Commodore David Porter');
INSERT INTO NormalizedPerson (name) VALUES ('Congress');
INSERT INTO NormalizedPerson (name) VALUES ('Convention');
INSERT INTO NormalizedPerson (name) VALUES ('Conventional Committee');
INSERT INTO NormalizedPerson (name) VALUES ('Council of War');
INSERT INTO NormalizedPerson (name) VALUES ('D C Barrett');
INSERT INTO NormalizedPerson (name) VALUES ('D. W Smith');
INSERT INTO NormalizedPerson (name) VALUES ('Dan Black');
INSERT INTO NormalizedPerson (name) VALUES ('Daniel Phelps');
INSERT INTO NormalizedPerson (name) VALUES ('David G Burnet');
INSERT INTO NormalizedPerson (name) VALUES ('David G Burnett');
INSERT INTO NormalizedPerson (name) VALUES ('David G. Burnet');
INSERT INTO NormalizedPerson (name) VALUES ('David Marple');
INSERT INTO NormalizedPerson (name) VALUES ('David Mills');
INSERT INTO NormalizedPerson (name) VALUES ('Deaf Smith');
INSERT INTO NormalizedPerson (name) VALUES ('Dillard');
INSERT INTO NormalizedPerson (name) VALUES ('District of Bravo settlers');
INSERT INTO NormalizedPerson (name) VALUES ('Document not sent');
INSERT INTO NormalizedPerson (name) VALUES ('Douglas Forsythe');
INSERT INTO NormalizedPerson (name) VALUES ('Dr. Joseph Bowers');
INSERT INTO NormalizedPerson (name) VALUES ('Dr. Wells');
INSERT INTO NormalizedPerson (name) VALUES ('E M Perry');
INSERT INTO NormalizedPerson (name) VALUES ('E R Wightman');
INSERT INTO NormalizedPerson (name) VALUES ('E. R. Wightman');
INSERT INTO NormalizedPerson (name) VALUES ('E. St John Hawkins');
INSERT INTO NormalizedPerson (name) VALUES ('E. W. Gregory');
INSERT INTO NormalizedPerson (name) VALUES ('Editor of the Telegraph and Texas Register');
INSERT INTO NormalizedPerson (name) VALUES ('Edward and John Lovelace');
INSERT INTO NormalizedPerson (name) VALUES ('Edward Lovelace');
INSERT INTO NormalizedPerson (name) VALUES ('Elias Austin Elliot');
INSERT INTO NormalizedPerson (name) VALUES ('Elias Bates');
INSERT INTO NormalizedPerson (name) VALUES ('Elias R Wightman');
INSERT INTO NormalizedPerson (name) VALUES ('Elias Wightman');
INSERT INTO NormalizedPerson (name) VALUES ('Emigrants');
INSERT INTO NormalizedPerson (name) VALUES ('Emily Austin');
INSERT INTO NormalizedPerson (name) VALUES ('Emily Bryan');
INSERT INTO NormalizedPerson (name) VALUES ('Emily M Perry');
INSERT INTO NormalizedPerson (name) VALUES ('Emily M. Perry');
INSERT INTO NormalizedPerson (name) VALUES ('Emily Perry');
INSERT INTO NormalizedPerson (name) VALUES ('Emperor Iturbide');
INSERT INTO NormalizedPerson (name) VALUES ('Estate of Moses Austin');
INSERT INTO NormalizedPerson (name) VALUES ('Evans and Shields');
INSERT INTO NormalizedPerson (name) VALUES ('F W Johnson');
INSERT INTO NormalizedPerson (name) VALUES ('Falconer and Comegys');
INSERT INTO NormalizedPerson (name) VALUES ('Federal Congress');
INSERT INTO NormalizedPerson (name) VALUES ('Felipe de la Garza');
INSERT INTO NormalizedPerson (name) VALUES ('Felix Trudeau');
INSERT INTO NormalizedPerson (name) VALUES ('FranÃ§ois Grapp');
INSERT INTO NormalizedPerson (name) VALUES ('Francis Bigham');
INSERT INTO NormalizedPerson (name) VALUES ('Francis Keller');
INSERT INTO NormalizedPerson (name) VALUES ('Francis Major');
INSERT INTO NormalizedPerson (name) VALUES ('Francis W. Johnson');
INSERT INTO NormalizedPerson (name) VALUES ('Frederick Bates');
INSERT INTO NormalizedPerson (name) VALUES ('G. W. Treat');
INSERT INTO NormalizedPerson (name) VALUES ('Gail Borden');
INSERT INTO NormalizedPerson (name) VALUES ('General Fernandez');
INSERT INTO NormalizedPerson (name) VALUES ('General Gaines');
INSERT INTO NormalizedPerson (name) VALUES ('general public');
INSERT INTO NormalizedPerson (name) VALUES ('General Wilkinson');
INSERT INTO NormalizedPerson (name) VALUES ('General William H Ashley');
INSERT INTO NormalizedPerson (name) VALUES ('George Fisher');
INSERT INTO NormalizedPerson (name) VALUES ('George Orr');
INSERT INTO NormalizedPerson (name) VALUES ('Gerguson');
INSERT INTO NormalizedPerson (name) VALUES ('Gilbert');
INSERT INTO NormalizedPerson (name) VALUES ('Government of the Province of Texas');
INSERT INTO NormalizedPerson (name) VALUES ('Governor Martinez');
INSERT INTO NormalizedPerson (name) VALUES ('Governor of Coahuila and Texas');
INSERT INTO NormalizedPerson (name) VALUES ('Governor Rafael Gonzales');
INSERT INTO NormalizedPerson (name) VALUES ('Governor Viesca');
INSERT INTO NormalizedPerson (name) VALUES ('Grayson and Jack');
INSERT INTO NormalizedPerson (name) VALUES ('H Meigs');
INSERT INTO NormalizedPerson (name) VALUES ('Harrison and Hopkins');
INSERT INTO NormalizedPerson (name) VALUES ('Hart');
INSERT INTO NormalizedPerson (name) VALUES ('Heerl and Pogue');
INSERT INTO NormalizedPerson (name) VALUES ('Henry Austin');
INSERT INTO NormalizedPerson (name) VALUES ('Henry Elliot');
INSERT INTO NormalizedPerson (name) VALUES ('Henry Meigs');
INSERT INTO NormalizedPerson (name) VALUES ('Henry Smith');
INSERT INTO NormalizedPerson (name) VALUES ('Hinton Curtis');
INSERT INTO NormalizedPerson (name) VALUES ('His mother and Sister');
INSERT INTO NormalizedPerson (name) VALUES ('Hockley and Bee');
INSERT INTO NormalizedPerson (name) VALUES ('Honey and Bates');
INSERT INTO NormalizedPerson (name) VALUES ('Horace Chrisman');
INSERT INTO NormalizedPerson (name) VALUES ('Horatio Chriesman');
INSERT INTO NormalizedPerson (name) VALUES ('Humphry Fullerton');
INSERT INTO NormalizedPerson (name) VALUES ('Humphry Jackson');
INSERT INTO NormalizedPerson (name) VALUES ('Hyde and Merit');
INSERT INTO NormalizedPerson (name) VALUES ('Inhabitants of Colony');
INSERT INTO NormalizedPerson (name) VALUES ('Inhabitants of Pecan Point');
INSERT INTO NormalizedPerson (name) VALUES ('Ira Lewis');
INSERT INTO NormalizedPerson (name) VALUES ('Ira R. Lewis');
INSERT INTO NormalizedPerson (name) VALUES ('Israel McGready');
INSERT INTO NormalizedPerson (name) VALUES ('Israel Waters');
INSERT INTO NormalizedPerson (name) VALUES ('J B Bailey');
INSERT INTO NormalizedPerson (name) VALUES ('J E B and J Austin');
INSERT INTO NormalizedPerson (name) VALUES ('J E B Austin');
INSERT INTO NormalizedPerson (name) VALUES ('J H Bell');
INSERT INTO NormalizedPerson (name) VALUES ('J L Woodbuy');
INSERT INTO NormalizedPerson (name) VALUES ('J M Wolfe');
INSERT INTO NormalizedPerson (name) VALUES ('J Mariano Guerra');
INSERT INTO NormalizedPerson (name) VALUES ('J. A. Wharton et Al.');
INSERT INTO NormalizedPerson (name) VALUES ('J. Allcorn');
INSERT INTO NormalizedPerson (name) VALUES ('J. B. Bailey');
INSERT INTO NormalizedPerson (name) VALUES ('J. B. Baley');
INSERT INTO NormalizedPerson (name) VALUES ('J. Bryant');
INSERT INTO NormalizedPerson (name) VALUES ('J. C. Peyton');
INSERT INTO NormalizedPerson (name) VALUES ('J. Cable');
INSERT INTO NormalizedPerson (name) VALUES ('J. E. B. Austin');
INSERT INTO NormalizedPerson (name) VALUES ('J. F. Perry');
INSERT INTO NormalizedPerson (name) VALUES ('J. H. Bell');
INSERT INTO NormalizedPerson (name) VALUES ('J. H. Hawkins');
INSERT INTO NormalizedPerson (name) VALUES ('J. J. Ross and A. C. Buckner');
INSERT INTO NormalizedPerson (name) VALUES ('J. R. Poinsett');
INSERT INTO NormalizedPerson (name) VALUES ('J.E.B. Austin');
INSERT INTO NormalizedPerson (name) VALUES ('James and John Austin');
INSERT INTO NormalizedPerson (name) VALUES ('James Austin');
INSERT INTO NormalizedPerson (name) VALUES ('James Bowie and James Fannin');
INSERT INTO NormalizedPerson (name) VALUES ('James Bryan and Mrs. Mary Austin');
INSERT INTO NormalizedPerson (name) VALUES ('James Bryan');
INSERT INTO NormalizedPerson (name) VALUES ('James Cummins');
INSERT INTO NormalizedPerson (name) VALUES ('James E. B. Austin');
INSERT INTO NormalizedPerson (name) VALUES ('James F and Emily Perry');
INSERT INTO NormalizedPerson (name) VALUES ('James F Perrry');
INSERT INTO NormalizedPerson (name) VALUES ('James F Perry');
INSERT INTO NormalizedPerson (name) VALUES ('James F. Perry');
INSERT INTO NormalizedPerson (name) VALUES ('James Fannin');
INSERT INTO NormalizedPerson (name) VALUES ('James Gaines');
INSERT INTO NormalizedPerson (name) VALUES ('James Holloway');
INSERT INTO NormalizedPerson (name) VALUES ('James Hope');
INSERT INTO NormalizedPerson (name) VALUES ('James Kerr and John Alley');
INSERT INTO NormalizedPerson (name) VALUES ('James R. Perry');
INSERT INTO NormalizedPerson (name) VALUES ('James Richardson');
INSERT INTO NormalizedPerson (name) VALUES ('James Staples');
INSERT INTO NormalizedPerson (name) VALUES ('James W Breedlove');
INSERT INTO NormalizedPerson (name) VALUES ('James Whiteside');
INSERT INTO NormalizedPerson (name) VALUES ('Jared E. Groce');
INSERT INTO NormalizedPerson (name) VALUES ('Jess Thompson');
INSERT INTO NormalizedPerson (name) VALUES ('Jessee Grimes');
INSERT INTO NormalizedPerson (name) VALUES ('John Andrews');
INSERT INTO NormalizedPerson (name) VALUES ('John Austin');
INSERT INTO NormalizedPerson (name) VALUES ('John Blanchard and George Lauman');
INSERT INTO NormalizedPerson (name) VALUES ('John Butler');
INSERT INTO NormalizedPerson (name) VALUES ('John Cummings');
INSERT INTO NormalizedPerson (name) VALUES ('John Davis Bradburn');
INSERT INTO NormalizedPerson (name) VALUES ('John Durst');
INSERT INTO NormalizedPerson (name) VALUES ('John Francis Merieult');
INSERT INTO NormalizedPerson (name) VALUES ('John G. Bond');
INSERT INTO NormalizedPerson (name) VALUES ('John Hawkins');
INSERT INTO NormalizedPerson (name) VALUES ('John McIntire');
INSERT INTO NormalizedPerson (name) VALUES ('John P Austin');
INSERT INTO NormalizedPerson (name) VALUES ('John P Coles');
INSERT INTO NormalizedPerson (name) VALUES ('John P. Coles');
INSERT INTO NormalizedPerson (name) VALUES ('John S Brickley');
INSERT INTO NormalizedPerson (name) VALUES ('John Scott');
INSERT INTO NormalizedPerson (name) VALUES ('John Smith T');
INSERT INTO NormalizedPerson (name) VALUES ('John Smith');
INSERT INTO NormalizedPerson (name) VALUES ('John Sprowl');
INSERT INTO NormalizedPerson (name) VALUES ('John Sprowl/ J T Gross');
INSERT INTO NormalizedPerson (name) VALUES ('John T Mason');
INSERT INTO NormalizedPerson (name) VALUES ('Jose Antonio Mexia');
INSERT INTO NormalizedPerson (name) VALUES ('Jose Antonio Navarro');
INSERT INTO NormalizedPerson (name) VALUES ('Jose Antonio Saucedo');
INSERT INTO NormalizedPerson (name) VALUES ('Jose Felix Trespalacios');
INSERT INTO NormalizedPerson (name) VALUES ('Joseph Burr');
INSERT INTO NormalizedPerson (name) VALUES ('Joseph Ficklin');
INSERT INTO NormalizedPerson (name) VALUES ('Joseph H. Hawkins');
INSERT INTO NormalizedPerson (name) VALUES ('Joseph Nye and Sons');
INSERT INTO NormalizedPerson (name) VALUES ('Joshua Pilcher');
INSERT INTO NormalizedPerson (name) VALUES ('Josiah H Bell');
INSERT INTO NormalizedPerson (name) VALUES ('Josiah H. Bell et al');
INSERT INTO NormalizedPerson (name) VALUES ('Josiah H. Bell');
INSERT INTO NormalizedPerson (name) VALUES ('Junta Gobernativa');
INSERT INTO NormalizedPerson (name) VALUES ('Junta Instituyente');
INSERT INTO NormalizedPerson (name) VALUES ('Kendall and Bates');
INSERT INTO NormalizedPerson (name) VALUES ('L. R. Kenny');
INSERT INTO NormalizedPerson (name) VALUES ('L. V. Hawkins');
INSERT INTO NormalizedPerson (name) VALUES ('Lastraps and Desmare');
INSERT INTO NormalizedPerson (name) VALUES ('Laurence Richard Kenny');
INSERT INTO NormalizedPerson (name) VALUES ('Legislature');
INSERT INTO NormalizedPerson (name) VALUES ('Lieutenant Governor DeLassus');
INSERT INTO NormalizedPerson (name) VALUES ('Lucas Alaman');
INSERT INTO NormalizedPerson (name) VALUES ('Luciano Garcia');
INSERT INTO NormalizedPerson (name) VALUES ('Luke Lesassier');
INSERT INTO NormalizedPerson (name) VALUES ('M B Menard');
INSERT INTO NormalizedPerson (name) VALUES ('Maria Austin');
INSERT INTO NormalizedPerson (name) VALUES ('Martin');
INSERT INTO NormalizedPerson (name) VALUES ('Mary Austin Holley');
INSERT INTO NormalizedPerson (name) VALUES ('Mateo Ahumada');
INSERT INTO NormalizedPerson (name) VALUES ('Mathew Wilson');
INSERT INTO NormalizedPerson (name) VALUES ('Matthew Kerr');
INSERT INTO NormalizedPerson (name) VALUES ('McCormick');
INSERT INTO NormalizedPerson (name) VALUES ('McNeil');
INSERT INTO NormalizedPerson (name) VALUES ('Members of Consultation');
INSERT INTO NormalizedPerson (name) VALUES ('Merle and Company');
INSERT INTO NormalizedPerson (name) VALUES ('Micajah Morris');
INSERT INTO NormalizedPerson (name) VALUES ('Michael Hart');
INSERT INTO NormalizedPerson (name) VALUES ('Military Commandant');
INSERT INTO NormalizedPerson (name) VALUES ('Militia');
INSERT INTO NormalizedPerson (name) VALUES ('Militiamen');
INSERT INTO NormalizedPerson (name) VALUES ('Mirabeau B. Lamar');
INSERT INTO NormalizedPerson (name) VALUES ('Missouri Territory Legislature');
INSERT INTO NormalizedPerson (name) VALUES ('Moses Austin and Stephen F. Austin');
INSERT INTO NormalizedPerson (name) VALUES ('Moses Austin');
INSERT INTO NormalizedPerson (name) VALUES ('Moses Morrison');
INSERT INTO NormalizedPerson (name) VALUES ('Mr Gray');
INSERT INTO NormalizedPerson (name) VALUES ('Mr Jinkins');
INSERT INTO NormalizedPerson (name) VALUES ('Mr Paskall');
INSERT INTO NormalizedPerson (name) VALUES ('Mrs Emily Perry');
INSERT INTO NormalizedPerson (name) VALUES ('Mrs John Hall');
INSERT INTO NormalizedPerson (name) VALUES ('Mrs Mary Austin Holley');
INSERT INTO NormalizedPerson (name) VALUES ('Mrs. E. M. Perry');
INSERT INTO NormalizedPerson (name) VALUES ('Mrs. James F. Perry');
INSERT INTO NormalizedPerson (name) VALUES ('Mrs. Joseph H. Hawkins');
INSERT INTO NormalizedPerson (name) VALUES ('N A Ware');
INSERT INTO NormalizedPerson (name) VALUES ('Nathan Pusey');
INSERT INTO NormalizedPerson (name) VALUES ('Nathaniel Cox');
INSERT INTO NormalizedPerson (name) VALUES ('Nicholas Biddle');
INSERT INTO NormalizedPerson (name) VALUES ('Nicholas Rightor');
INSERT INTO NormalizedPerson (name) VALUES ('no recipient');
INSERT INTO NormalizedPerson (name) VALUES ('none');
INSERT INTO NormalizedPerson (name) VALUES ('Oliver Jones');
INSERT INTO NormalizedPerson (name) VALUES ('P W Grayson');
INSERT INTO NormalizedPerson (name) VALUES ('Parish Gasquet and Company');
INSERT INTO NormalizedPerson (name) VALUES ('People of Colony');
INSERT INTO NormalizedPerson (name) VALUES ('People of Texas');
INSERT INTO NormalizedPerson (name) VALUES ('People of the Colony');
INSERT INTO NormalizedPerson (name) VALUES ('People');
INSERT INTO NormalizedPerson (name) VALUES ('Permanent Council');
INSERT INTO NormalizedPerson (name) VALUES ('Perry and Somervell');
INSERT INTO NormalizedPerson (name) VALUES ('Peter and Joseph Powell');
INSERT INTO NormalizedPerson (name) VALUES ('Peter W. Love');
INSERT INTO NormalizedPerson (name) VALUES ('Philip Dimmitt');
INSERT INTO NormalizedPerson (name) VALUES ('Phillip Reddinger');
INSERT INTO NormalizedPerson (name) VALUES ('Pierre Laforge');
INSERT INTO NormalizedPerson (name) VALUES ('Powers of Commissioners to Waco Indians');
INSERT INTO NormalizedPerson (name) VALUES ('President of Consultation');
INSERT INTO NormalizedPerson (name) VALUES ('President of the Consultation');
INSERT INTO NormalizedPerson (name) VALUES ('President of the Provisional Government of Texas');
INSERT INTO NormalizedPerson (name) VALUES ('Provincial Deputation');
INSERT INTO NormalizedPerson (name) VALUES ('Provisional Government of Texas');
INSERT INTO NormalizedPerson (name) VALUES ('Provisional Government');
INSERT INTO NormalizedPerson (name) VALUES ('Provisional Governor');
INSERT INTO NormalizedPerson (name) VALUES ('Public');
INSERT INTO NormalizedPerson (name) VALUES ('R R Royall and Austin');
INSERT INTO NormalizedPerson (name) VALUES ('R R Royall and S. Rhoads Fisher');
INSERT INTO NormalizedPerson (name) VALUES ('R R Royall');
INSERT INTO NormalizedPerson (name) VALUES ('R. M. Williamson');
INSERT INTO NormalizedPerson (name) VALUES ('R. R. Royall');
INSERT INTO NormalizedPerson (name) VALUES ('Rafae Llanos');
INSERT INTO NormalizedPerson (name) VALUES ('Rafael Gonzales');
INSERT INTO NormalizedPerson (name) VALUES ('Raleigh');
INSERT INTO NormalizedPerson (name) VALUES ('Ramon Musquiz');
INSERT INTO NormalizedPerson (name) VALUES ('Residents of Texas');
INSERT INTO NormalizedPerson (name) VALUES ('Richard Fields');
INSERT INTO NormalizedPerson (name) VALUES ('Richared Ellis et al');
INSERT INTO NormalizedPerson (name) VALUES ('Robert C. Bruffy');
INSERT INTO NormalizedPerson (name) VALUES ('Robert Collet');
INSERT INTO NormalizedPerson (name) VALUES ('Robert Kuykendall');
INSERT INTO NormalizedPerson (name) VALUES ('Robert M Williamson');
INSERT INTO NormalizedPerson (name) VALUES ('Robert Wash');
INSERT INTO NormalizedPerson (name) VALUES ('S H Everett');
INSERT INTO NormalizedPerson (name) VALUES ('S M Williams');
INSERT INTO NormalizedPerson (name) VALUES ('S Rhoads Fisher');
INSERT INTO NormalizedPerson (name) VALUES ('S. M. Williams');
INSERT INTO NormalizedPerson (name) VALUES ('Sam C. Carter and Benjamin Fowler');
INSERT INTO NormalizedPerson (name) VALUES ('Sam Houston');
INSERT INTO NormalizedPerson (name) VALUES ('Sam McCraw');
INSERT INTO NormalizedPerson (name) VALUES ('Sameul M Williams');
INSERT INTO NormalizedPerson (name) VALUES ('Samuel Dixon');
INSERT INTO NormalizedPerson (name) VALUES ('Samuel Houston');
INSERT INTO NormalizedPerson (name) VALUES ('Samuel M Williams');
INSERT INTO NormalizedPerson (name) VALUES ('Samuel M. Williams');
INSERT INTO NormalizedPerson (name) VALUES ('Samuel Sexton and Charles Morgan');
INSERT INTO NormalizedPerson (name) VALUES ('Samuel Swartwout');
INSERT INTO NormalizedPerson (name) VALUES ('Samuel Williams');
INSERT INTO NormalizedPerson (name) VALUES ('Secretary of Relations');
INSERT INTO NormalizedPerson (name) VALUES ('Senator L F Linn');
INSERT INTO NormalizedPerson (name) VALUES ('Seth Hunt');
INSERT INTO NormalizedPerson (name) VALUES ('Seth Ingram');
INSERT INTO NormalizedPerson (name) VALUES ('Sheriff of Colony');
INSERT INTO NormalizedPerson (name) VALUES ('Sheriff of the Colony');
INSERT INTO NormalizedPerson (name) VALUES ('Spephen F Austin');
INSERT INTO NormalizedPerson (name) VALUES ('State Congress');
INSERT INTO NormalizedPerson (name) VALUES ('State of Kentucky');
INSERT INTO NormalizedPerson (name) VALUES ('State of Missouri');
INSERT INTO NormalizedPerson (name) VALUES ('Stepehn F. Austin');
INSERT INTO NormalizedPerson (name) VALUES ('Stephen Austin');
INSERT INTO NormalizedPerson (name) VALUES ('Stephen F Austin and Samuel Houston');
INSERT INTO NormalizedPerson (name) VALUES ('Stephen F Austin et Al');
INSERT INTO NormalizedPerson (name) VALUES ('Stephen F Austin');
INSERT INTO NormalizedPerson (name) VALUES ('Stephen F Austin. Branch T Archer');
INSERT INTO NormalizedPerson (name) VALUES ('Stephen F. Austin and Company');
INSERT INTO NormalizedPerson (name) VALUES ('Stephen F. Austin et al');
INSERT INTO NormalizedPerson (name) VALUES ('Stephen F. Austin');
INSERT INTO NormalizedPerson (name) VALUES ('Stephen F. Austion');
INSERT INTO NormalizedPerson (name) VALUES ('Taylor Wilkins and Company');
INSERT INTO NormalizedPerson (name) VALUES ('Texas Army');
INSERT INTO NormalizedPerson (name) VALUES ('Texas Gazette');
INSERT INTO NormalizedPerson (name) VALUES ('Thomas Barnett');
INSERT INTO NormalizedPerson (name) VALUES ('Thomas C. Banks');
INSERT INTO NormalizedPerson (name) VALUES ('Thomas F Leaming');
INSERT INTO NormalizedPerson (name) VALUES ('Thomas F McKinney');
INSERT INTO NormalizedPerson (name) VALUES ('Thomas F. McKinney');
INSERT INTO NormalizedPerson (name) VALUES ('Thomas H Benton');
INSERT INTO NormalizedPerson (name) VALUES ('Thomas J Rusk');
INSERT INTO NormalizedPerson (name) VALUES ('Thomas Novell');
INSERT INTO NormalizedPerson (name) VALUES ('Thomas O Meaux');
INSERT INTO NormalizedPerson (name) VALUES ('Thomas White');
INSERT INTO NormalizedPerson (name) VALUES ('Toby and Brother');
INSERT INTO NormalizedPerson (name) VALUES ('U. S. Consul');
INSERT INTO NormalizedPerson (name) VALUES ('Unknown');
INSERT INTO NormalizedPerson (name) VALUES ('Unkown');
INSERT INTO NormalizedPerson (name) VALUES ('Unsent');
INSERT INTO NormalizedPerson (name) VALUES ('Victor Blanco');
INSERT INTO NormalizedPerson (name) VALUES ('Volunteers at Bexar');
INSERT INTO NormalizedPerson (name) VALUES ('W B Allen');
INSERT INTO NormalizedPerson (name) VALUES ('W C Carr');
INSERT INTO NormalizedPerson (name) VALUES ('W D C Hall');
INSERT INTO NormalizedPerson (name) VALUES ('W D Dunlap');
INSERT INTO NormalizedPerson (name) VALUES ('W. Carothers');
INSERT INTO NormalizedPerson (name) VALUES ('W. G. Whiteside');
INSERT INTO NormalizedPerson (name) VALUES ('W. S. Archer');
INSERT INTO NormalizedPerson (name) VALUES ('W. S. Hall?');
INSERT INTO NormalizedPerson (name) VALUES ('Waco Indians');
INSERT INTO NormalizedPerson (name) VALUES ('Warren Buford');
INSERT INTO NormalizedPerson (name) VALUES ('Warren D. C. Hall');
INSERT INTO NormalizedPerson (name) VALUES ('Wilkins and Catron');
INSERT INTO NormalizedPerson (name) VALUES ('William Ashbrook');
INSERT INTO NormalizedPerson (name) VALUES ('William Bryan');
INSERT INTO NormalizedPerson (name) VALUES ('William Eads');
INSERT INTO NormalizedPerson (name) VALUES ('William Ficklin');
INSERT INTO NormalizedPerson (name) VALUES ('William H Wharton');
INSERT INTO NormalizedPerson (name) VALUES ('William Kincheloe');
INSERT INTO NormalizedPerson (name) VALUES ('William M. O'Hara');
INSERT INTO NormalizedPerson (name) VALUES ('William O'Hara');
INSERT INTO NormalizedPerson (name) VALUES ('William Pettus');
INSERT INTO NormalizedPerson (name) VALUES ('William S. Brown');
INSERT INTO NormalizedPerson (name) VALUES ('William Selkerk');
INSERT INTO NormalizedPerson (name) VALUES ('William Smith');
INSERT INTO NormalizedPerson (name) VALUES ('William T Austin');
INSERT INTO NormalizedPerson (name) VALUES ('William W. Little');
INSERT INTO NormalizedPerson (name) VALUES ('Wily Martin');
INSERT INTO NormalizedPerson (name) VALUES ('Zeno Phillips');
INSERT INTO NormalizedPerson (name) VALUES ('[Edward Livingston?]');
