INSERT INTO NormalizedPerson (name) VALUES ('Abiel P Mead');
INSERT INTO NormalizedPerson (name) VALUES ('Abraham Armstrong');
INSERT INTO NormalizedPerson (name) VALUES ('A C Ainsworth');
INSERT INTO NormalizedPerson (name) VALUES ('Adam Trinno');
INSERT INTO NormalizedPerson (name) VALUES ('A Holdridge');
INSERT INTO NormalizedPerson (name) VALUES ('Ahumada');
INSERT INTO NormalizedPerson (name) VALUES ('Albert Gallatin');
INSERT INTO NormalizedPerson (name) VALUES ('Alcade of San Felipe');
INSERT INTO NormalizedPerson (name) VALUES ('Alcalde');
INSERT INTO NormalizedPerson (name) VALUES ('Alcalde of San Felipe');
INSERT INTO NormalizedPerson (name) VALUES ('Alex McNair');
INSERT INTO NormalizedPerson (name) VALUES ('Alijah Hull');
INSERT INTO NormalizedPerson (name) VALUES ('A. McNair');
INSERT INTO NormalizedPerson (name) VALUES ('Amos Rawls');
INSERT INTO NormalizedPerson (name) VALUES ('Anastacio Bustamante');
INSERT INTO NormalizedPerson (name) VALUES ('Archibald Austin');
INSERT INTO NormalizedPerson (name) VALUES ('Archilbald Austin');
INSERT INTO NormalizedPerson (name) VALUES ('Armistead Moore');
INSERT INTO NormalizedPerson (name) VALUES ('A. Sampyrac');
INSERT INTO NormalizedPerson (name) VALUES ('Authorities of La Bahia');
INSERT INTO NormalizedPerson (name) VALUES ('Ayunatmiento of San Felipe');
INSERT INTO NormalizedPerson (name) VALUES ('Bank of St Louis');
INSERT INTO NormalizedPerson (name) VALUES ('Ben J. Shakelford');
INSERT INTO NormalizedPerson (name) VALUES ('Bogart');
INSERT INTO NormalizedPerson (name) VALUES ('Branch T Archer');
INSERT INTO NormalizedPerson (name) VALUES ('Bryrd Lockhart, Green De Witt, James Kerr');
INSERT INTO NormalizedPerson (name) VALUES ('B T Jacques');
INSERT INTO NormalizedPerson (name) VALUES ('Bustamentes');
INSERT INTO NormalizedPerson (name) VALUES ('Captian Richard Fields');
INSERT INTO NormalizedPerson (name) VALUES ('Carbajal's Mother');
INSERT INTO NormalizedPerson (name) VALUES ('Carlos Garcia');
INSERT INTO NormalizedPerson (name) VALUES ('C. Dyer,David Hamilton, William Spence, Joseph Newman, Nicholas Whitehead, John Clark, Thomas J. Rabb, Charles Henderson, Moses Windham, William Luce, Alexander Brown, ANdrew Rabb, John Ingram, Gabriel Straw Snyder, Andrew Rabb');
INSERT INTO NormalizedPerson (name) VALUES ('Central Committee');
INSERT INTO NormalizedPerson (name) VALUES ('Chapman');
INSERT INTO NormalizedPerson (name) VALUES ('Christian Wilt');
INSERT INTO NormalizedPerson (name) VALUES ('Churchill Fulshear');
INSERT INTO NormalizedPerson (name) VALUES ('Citizens of Jefferson County');
INSERT INTO NormalizedPerson (name) VALUES ('Citizens of Mina');
INSERT INTO NormalizedPerson (name) VALUES ('Colonists');
INSERT INTO NormalizedPerson (name) VALUES ('Colonists(');
INSERT INTO NormalizedPerson (name) VALUES ('Colonlists');
INSERT INTO NormalizedPerson (name) VALUES ('Colony');
INSERT INTO NormalizedPerson (name) VALUES ('Colorado District');
INSERT INTO NormalizedPerson (name) VALUES ('Columbia Committee');
INSERT INTO NormalizedPerson (name) VALUES ('Comittee of Safety of San Felipe');
INSERT INTO NormalizedPerson (name) VALUES ('Committee at Convention');
INSERT INTO NormalizedPerson (name) VALUES ('Committee of Harrisburgh');
INSERT INTO NormalizedPerson (name) VALUES ('Committee of San Felipe');
INSERT INTO NormalizedPerson (name) VALUES ('Congress');
INSERT INTO NormalizedPerson (name) VALUES ('Convention');
INSERT INTO NormalizedPerson (name) VALUES ('Conventional Committee');
INSERT INTO NormalizedPerson (name) VALUES ('Council of War');
INSERT INTO NormalizedPerson (name) VALUES ('Dan Bissell');
INSERT INTO NormalizedPerson (name) VALUES ('Dan Black');
INSERT INTO NormalizedPerson (name) VALUES ('Darius Shaw');
INSERT INTO NormalizedPerson (name) VALUES ('D C Barrett');
INSERT INTO NormalizedPerson (name) VALUES ('D. Crozer');
INSERT INTO NormalizedPerson (name) VALUES ('Dexter C. Gunn and David Bucklin');
INSERT INTO NormalizedPerson (name) VALUES ('Dillard');
INSERT INTO NormalizedPerson (name) VALUES ('District of Bravo settlers');
INSERT INTO NormalizedPerson (name) VALUES ('Document not sent');
INSERT INTO NormalizedPerson (name) VALUES ('Duff Chadwell');
INSERT INTO NormalizedPerson (name) VALUES ('Ebel Miton,Ranford Berry, F. Smith, Wm. H Smith, John Teal, and Thomas ?');
INSERT INTO NormalizedPerson (name) VALUES ('Edwin L Pettit');
INSERT INTO NormalizedPerson (name) VALUES ('Elias R Wightman');
INSERT INTO NormalizedPerson (name) VALUES ('Elias Wightman');
INSERT INTO NormalizedPerson (name) VALUES ('Emigrants');
INSERT INTO NormalizedPerson (name) VALUES ('Enoch Brenson');
INSERT INTO NormalizedPerson (name) VALUES ('E R Wightman');
INSERT INTO NormalizedPerson (name) VALUES ('E. R. Wightman');
INSERT INTO NormalizedPerson (name) VALUES ('Falconer');
INSERT INTO NormalizedPerson (name) VALUES ('Faris and White');
INSERT INTO NormalizedPerson (name) VALUES ('Federal Congress');
INSERT INTO NormalizedPerson (name) VALUES ('Felix Trudeau');
INSERT INTO NormalizedPerson (name) VALUES ('François Grapp');
INSERT INTO NormalizedPerson (name) VALUES ('Frederick Bates');
INSERT INTO NormalizedPerson (name) VALUES ('Freeman Pettus');
INSERT INTO NormalizedPerson (name) VALUES ('G B Cotten');
INSERT INTO NormalizedPerson (name) VALUES ('general public');
INSERT INTO NormalizedPerson (name) VALUES ('General Public');
INSERT INTO NormalizedPerson (name) VALUES ('General William H Ashley');
INSERT INTO NormalizedPerson (name) VALUES ('Geo Huff');
INSERT INTO NormalizedPerson (name) VALUES ('George S. Pentacost');
INSERT INTO NormalizedPerson (name) VALUES ('Gideon Blackburn');
INSERT INTO NormalizedPerson (name) VALUES ('Government of the Province of Texas');
INSERT INTO NormalizedPerson (name) VALUES ('Governor Martinez');
INSERT INTO NormalizedPerson (name) VALUES ('Governor of Coahuila');
INSERT INTO NormalizedPerson (name) VALUES ('Governor Viesca');
INSERT INTO NormalizedPerson (name) VALUES ('G. Pearce');
INSERT INTO NormalizedPerson (name) VALUES ('Green De Witt');
INSERT INTO NormalizedPerson (name) VALUES ('Hamiton N Yett and Alexr Calvit');
INSERT INTO NormalizedPerson (name) VALUES ('Hanson Alsbury');
INSERT INTO NormalizedPerson (name) VALUES ('Hart');
INSERT INTO NormalizedPerson (name) VALUES ('Heerl');
INSERT INTO NormalizedPerson (name) VALUES ('Henry Dodge');
INSERT INTO NormalizedPerson (name) VALUES ('Henry Morse');
INSERT INTO NormalizedPerson (name) VALUES ('Henry W. Munson');
INSERT INTO NormalizedPerson (name) VALUES ('H. H. League, James C. Ludlow, Elias Wightman, Richard Matson.');
INSERT INTO NormalizedPerson (name) VALUES ('Hinton Curtis');
INSERT INTO NormalizedPerson (name) VALUES ('Horatio Alsberry');
INSERT INTO NormalizedPerson (name) VALUES ('Horatio Chriesman');
INSERT INTO NormalizedPerson (name) VALUES ('Hyde');
INSERT INTO NormalizedPerson (name) VALUES ('Inhabitants of Colony');
INSERT INTO NormalizedPerson (name) VALUES ('Inhabitants of Pecan Point');
INSERT INTO NormalizedPerson (name) VALUES ('Ireston C. Devan');
INSERT INTO NormalizedPerson (name) VALUES ('Isaac C. Oglem');
INSERT INTO NormalizedPerson (name) VALUES ('Isaac Jesses');
INSERT INTO NormalizedPerson (name) VALUES ('Israel McGready');
INSERT INTO NormalizedPerson (name) VALUES ('Israel Waters');
INSERT INTO NormalizedPerson (name) VALUES ('Jacob Betts');
INSERT INTO NormalizedPerson (name) VALUES ('J. B. Baley');
INSERT INTO NormalizedPerson (name) VALUES ('J. Blair');
INSERT INTO NormalizedPerson (name) VALUES ('J. Botts');
INSERT INTO NormalizedPerson (name) VALUES ('J. Cable');
INSERT INTO NormalizedPerson (name) VALUES ('J Child');
INSERT INTO NormalizedPerson (name) VALUES ('J. Child');
INSERT INTO NormalizedPerson (name) VALUES ('J. D. Bludworth');
INSERT INTO NormalizedPerson (name) VALUES ('Jessee Grimes');
INSERT INTO NormalizedPerson (name) VALUES ('J. F. Buchetti');
INSERT INTO NormalizedPerson (name) VALUES ('J G Wright');
INSERT INTO NormalizedPerson (name) VALUES ('J. L. Dumanday');
INSERT INTO NormalizedPerson (name) VALUES ('J. L Phillips');
INSERT INTO NormalizedPerson (name) VALUES ('J Mariano Guerra');
INSERT INTO NormalizedPerson (name) VALUES ('John McIntire');
INSERT INTO NormalizedPerson (name) VALUES ('John P Sheldon');
INSERT INTO NormalizedPerson (name) VALUES ('John Smith T');
INSERT INTO NormalizedPerson (name) VALUES ('John T Criswell');
INSERT INTO NormalizedPerson (name) VALUES ('Joshua Marsh');
INSERT INTO NormalizedPerson (name) VALUES ('Josiah H. Bell et al');
INSERT INTO NormalizedPerson (name) VALUES ('J R Bedford');
INSERT INTO NormalizedPerson (name) VALUES ('J. Sargeant');
INSERT INTO NormalizedPerson (name) VALUES ('Juan Francicso Buchetti');
INSERT INTO NormalizedPerson (name) VALUES ('Junta Gobernativa');
INSERT INTO NormalizedPerson (name) VALUES ('Junta Instituyente');
INSERT INTO NormalizedPerson (name) VALUES ('Knight and White');
INSERT INTO NormalizedPerson (name) VALUES ('Lastraps');
INSERT INTO NormalizedPerson (name) VALUES ('Legislature');
INSERT INTO NormalizedPerson (name) VALUES ('Leonidas W. Baker');
INSERT INTO NormalizedPerson (name) VALUES ('Lieutenant Governor DeLassus');
INSERT INTO NormalizedPerson (name) VALUES ('Louisiana Advertiser');
INSERT INTO NormalizedPerson (name) VALUES ('Martin F Maher and Company');
INSERT INTO NormalizedPerson (name) VALUES ('Mateo Ahumada');
INSERT INTO NormalizedPerson (name) VALUES ('Matthew G White');
INSERT INTO NormalizedPerson (name) VALUES ('McCoy and Scanlan');
INSERT INTO NormalizedPerson (name) VALUES ('Members of Consultation');
INSERT INTO NormalizedPerson (name) VALUES ('Michael Hart');
INSERT INTO NormalizedPerson (name) VALUES ('Military Commandant');
INSERT INTO NormalizedPerson (name) VALUES ('Militia');
INSERT INTO NormalizedPerson (name) VALUES ('Missouri Legislature');
INSERT INTO NormalizedPerson (name) VALUES ('Missouri Territory Legislature');
INSERT INTO NormalizedPerson (name) VALUES ('Mr Paskall');
INSERT INTO NormalizedPerson (name) VALUES ('M. Slocum');
INSERT INTO NormalizedPerson (name) VALUES ('Nathan Pusey');
INSERT INTO NormalizedPerson (name) VALUES ('N A Ware');
INSERT INTO NormalizedPerson (name) VALUES ('no recipient');
INSERT INTO NormalizedPerson (name) VALUES ('Oliver Jones');
INSERT INTO NormalizedPerson (name) VALUES ('Pascal Detchemendy');
INSERT INTO NormalizedPerson (name) VALUES ('Patick and Lindsay Clopper');
INSERT INTO NormalizedPerson (name) VALUES ('Paul Dimmitt');
INSERT INTO NormalizedPerson (name) VALUES ('People');
INSERT INTO NormalizedPerson (name) VALUES ('People of Colony');
INSERT INTO NormalizedPerson (name) VALUES ('People of Texas');
INSERT INTO NormalizedPerson (name) VALUES ('People of the Colony');
INSERT INTO NormalizedPerson (name) VALUES ('Permanent Council');
INSERT INTO NormalizedPerson (name) VALUES ('Pierre Delassus De Luziere');
INSERT INTO NormalizedPerson (name) VALUES ('Pierre Laforge');
INSERT INTO NormalizedPerson (name) VALUES ('Powers of Commissioners to Waco Indians');
INSERT INTO NormalizedPerson (name) VALUES ('President of the Consultation');
INSERT INTO NormalizedPerson (name) VALUES ('President of the Provisional Government of Texas');
INSERT INTO NormalizedPerson (name) VALUES ('Provincial Deputation');
INSERT INTO NormalizedPerson (name) VALUES ('Provisional Government');
INSERT INTO NormalizedPerson (name) VALUES ('Provisional Government of Texas');
INSERT INTO NormalizedPerson (name) VALUES ('Provisional Governor');
INSERT INTO NormalizedPerson (name) VALUES ('P S le Hicks');
INSERT INTO NormalizedPerson (name) VALUES ('P. S. Slocum');
INSERT INTO NormalizedPerson (name) VALUES ('Public');
INSERT INTO NormalizedPerson (name) VALUES ('Rafae Llanos');
INSERT INTO NormalizedPerson (name) VALUES ('Raleigh');
INSERT INTO NormalizedPerson (name) VALUES ('Ramon Musquiz');
INSERT INTO NormalizedPerson (name) VALUES ('Randall Jones');
INSERT INTO NormalizedPerson (name) VALUES ('Residents of Texas');
INSERT INTO NormalizedPerson (name) VALUES ('Robert Leftwich or Haden Edwards');
INSERT INTO NormalizedPerson (name) VALUES ('Roswell Mills');
INSERT INTO NormalizedPerson (name) VALUES ('R. P. Guyard');
INSERT INTO NormalizedPerson (name) VALUES ('Sam McCraw');
INSERT INTO NormalizedPerson (name) VALUES ('Schooner Lively');
INSERT INTO NormalizedPerson (name) VALUES ('Secretary of Relations');
INSERT INTO NormalizedPerson (name) VALUES ('Seth Hunt');
INSERT INTO NormalizedPerson (name) VALUES ('S Hatch');
INSERT INTO NormalizedPerson (name) VALUES ('Sheriff of Colony');
INSERT INTO NormalizedPerson (name) VALUES ('Sheriff of the Colony');
INSERT INTO NormalizedPerson (name) VALUES ('S. T. Angier');
INSERT INTO NormalizedPerson (name) VALUES ('State Congress');
INSERT INTO NormalizedPerson (name) VALUES ('State of Kentucky');
INSERT INTO NormalizedPerson (name) VALUES ('State of Missouri');
INSERT INTO NormalizedPerson (name) VALUES ('Sylvester Murphy');
INSERT INTO NormalizedPerson (name) VALUES ('Tacitus Clay');
INSERT INTO NormalizedPerson (name) VALUES ('Texas Army');
INSERT INTO NormalizedPerson (name) VALUES ('Texas Gazette');
INSERT INTO NormalizedPerson (name) VALUES ('T. Farelly');
INSERT INTO NormalizedPerson (name) VALUES ('T. [or J.] Reilly');
INSERT INTO NormalizedPerson (name) VALUES ('Unknown');
INSERT INTO NormalizedPerson (name) VALUES ('Unsent');
INSERT INTO NormalizedPerson (name) VALUES ('U. S. Consul');
INSERT INTO NormalizedPerson (name) VALUES ('Various New Orleans firms');
INSERT INTO NormalizedPerson (name) VALUES ('Volunteers at Bexar');
INSERT INTO NormalizedPerson (name) VALUES ('Warren Buford');
INSERT INTO NormalizedPerson (name) VALUES ('Washington Hotel');
INSERT INTO NormalizedPerson (name) VALUES ('W D C Hall');
INSERT INTO NormalizedPerson (name) VALUES ('Wyatt Hanks');
INSERT INTO NormalizedPerson (name) VALUES ('Zenas Priest');
INSERT INTO NormalizedPerson (name) VALUES ('Zeno Phillips');
