INSERT INTO NormalizedPerson (name) VALUES ('Ahumada');
INSERT INTO NormalizedPerson (name) VALUES ('Albert Gallatin');
INSERT INTO NormalizedPerson (name) VALUES ('Alcade of San Felipe');
INSERT INTO NormalizedPerson (name) VALUES ('Alcalde');
INSERT INTO NormalizedPerson (name) VALUES ('Alcalde of San Felipe');
INSERT INTO NormalizedPerson (name) VALUES ('Alex McNair');
INSERT INTO NormalizedPerson (name) VALUES ('Amos Rawls');
INSERT INTO NormalizedPerson (name) VALUES ('Anastacio Bustamante');
INSERT INTO NormalizedPerson (name) VALUES ('Archilbald Austin');
INSERT INTO NormalizedPerson (name) VALUES ('Authorities of La Bahia');
INSERT INTO NormalizedPerson (name) VALUES ('Ayunatmiento of San Felipe');
INSERT INTO NormalizedPerson (name) VALUES ('Branch T Archer');
INSERT INTO NormalizedPerson (name) VALUES ('Bustamentes');
INSERT INTO NormalizedPerson (name) VALUES ('Captian Richard Fields');
INSERT INTO NormalizedPerson (name) VALUES ('Carbajal's Mother');
INSERT INTO NormalizedPerson (name) VALUES ('Carlos Garcia');
INSERT INTO NormalizedPerson (name) VALUES ('Central Committee');
INSERT INTO NormalizedPerson (name) VALUES ('Chapman');
INSERT INTO NormalizedPerson (name) VALUES ('Christian Wilt');
INSERT INTO NormalizedPerson (name) VALUES ('Citizens of Jefferson County');
INSERT INTO NormalizedPerson (name) VALUES ('Citizens of Mina');
INSERT INTO NormalizedPerson (name) VALUES ('Colonists');
INSERT INTO NormalizedPerson (name) VALUES ('Colonists(');
INSERT INTO NormalizedPerson (name) VALUES ('Colonlists');
INSERT INTO NormalizedPerson (name) VALUES ('Colony');
INSERT INTO NormalizedPerson (name) VALUES ('Colorado District');
INSERT INTO NormalizedPerson (name) VALUES ('Columbia Committee');
INSERT INTO NormalizedPerson (name) VALUES ('Comittee of Safety of San Felipe');
INSERT INTO NormalizedPerson (name) VALUES ('Committee at Convention');
INSERT INTO NormalizedPerson (name) VALUES ('Committee of Harrisburgh');
INSERT INTO NormalizedPerson (name) VALUES ('Committee of San Felipe');
INSERT INTO NormalizedPerson (name) VALUES ('Congress');
INSERT INTO NormalizedPerson (name) VALUES ('Convention');
INSERT INTO NormalizedPerson (name) VALUES ('Conventional Committee');
INSERT INTO NormalizedPerson (name) VALUES ('Council of War');
INSERT INTO NormalizedPerson (name) VALUES ('Dan Black');
INSERT INTO NormalizedPerson (name) VALUES ('D C Barrett');
INSERT INTO NormalizedPerson (name) VALUES ('Dillard');
INSERT INTO NormalizedPerson (name) VALUES ('District of Bravo settlers');
INSERT INTO NormalizedPerson (name) VALUES ('Document not sent');
INSERT INTO NormalizedPerson (name) VALUES ('Elias R Wightman');
INSERT INTO NormalizedPerson (name) VALUES ('Elias Wightman');
INSERT INTO NormalizedPerson (name) VALUES ('Emigrants');
INSERT INTO NormalizedPerson (name) VALUES ('E R Wightman');
INSERT INTO NormalizedPerson (name) VALUES ('E. R. Wightman');
INSERT INTO NormalizedPerson (name) VALUES ('Falconer');
INSERT INTO NormalizedPerson (name) VALUES ('Federal Congress');
INSERT INTO NormalizedPerson (name) VALUES ('Felix Trudeau');
INSERT INTO NormalizedPerson (name) VALUES ('François Grapp');
INSERT INTO NormalizedPerson (name) VALUES ('Frederick Bates');
INSERT INTO NormalizedPerson (name) VALUES ('general public');
INSERT INTO NormalizedPerson (name) VALUES ('General Public');
INSERT INTO NormalizedPerson (name) VALUES ('General William H Ashley');
INSERT INTO NormalizedPerson (name) VALUES ('Government of the Province of Texas');
INSERT INTO NormalizedPerson (name) VALUES ('Governor Martinez');
INSERT INTO NormalizedPerson (name) VALUES ('Governor of Coahuila');
INSERT INTO NormalizedPerson (name) VALUES ('Governor Viesca');
INSERT INTO NormalizedPerson (name) VALUES ('Hart');
INSERT INTO NormalizedPerson (name) VALUES ('Heerl');
INSERT INTO NormalizedPerson (name) VALUES ('Hinton Curtis');
INSERT INTO NormalizedPerson (name) VALUES ('Horatio Chriesman');
INSERT INTO NormalizedPerson (name) VALUES ('Hyde');
INSERT INTO NormalizedPerson (name) VALUES ('Inhabitants of Colony');
INSERT INTO NormalizedPerson (name) VALUES ('Inhabitants of Pecan Point');
INSERT INTO NormalizedPerson (name) VALUES ('Israel McGready');
INSERT INTO NormalizedPerson (name) VALUES ('Israel Waters');
INSERT INTO NormalizedPerson (name) VALUES ('J. B. Baley');
INSERT INTO NormalizedPerson (name) VALUES ('J. Cable');
INSERT INTO NormalizedPerson (name) VALUES ('Jessee Grimes');
INSERT INTO NormalizedPerson (name) VALUES ('J Mariano Guerra');
INSERT INTO NormalizedPerson (name) VALUES ('John McIntire');
INSERT INTO NormalizedPerson (name) VALUES ('John Smith T');
INSERT INTO NormalizedPerson (name) VALUES ('Josiah H. Bell et al');
INSERT INTO NormalizedPerson (name) VALUES ('Junta Gobernativa');
INSERT INTO NormalizedPerson (name) VALUES ('Junta Instituyente');
INSERT INTO NormalizedPerson (name) VALUES ('Lastraps');
INSERT INTO NormalizedPerson (name) VALUES ('Legislature');
INSERT INTO NormalizedPerson (name) VALUES ('Lieutenant Governor DeLassus');
INSERT INTO NormalizedPerson (name) VALUES ('Mateo Ahumada');
INSERT INTO NormalizedPerson (name) VALUES ('Members of Consultation');
INSERT INTO NormalizedPerson (name) VALUES ('Michael Hart');
INSERT INTO NormalizedPerson (name) VALUES ('Military Commandant');
INSERT INTO NormalizedPerson (name) VALUES ('Militia');
INSERT INTO NormalizedPerson (name) VALUES ('Missouri Territory Legislature');
INSERT INTO NormalizedPerson (name) VALUES ('Mr Paskall');
INSERT INTO NormalizedPerson (name) VALUES ('Nathan Pusey');
INSERT INTO NormalizedPerson (name) VALUES ('N A Ware');
INSERT INTO NormalizedPerson (name) VALUES ('no recipient');
INSERT INTO NormalizedPerson (name) VALUES ('Oliver Jones');
INSERT INTO NormalizedPerson (name) VALUES ('People');
INSERT INTO NormalizedPerson (name) VALUES ('People of Colony');
INSERT INTO NormalizedPerson (name) VALUES ('People of Texas');
INSERT INTO NormalizedPerson (name) VALUES ('People of the Colony');
INSERT INTO NormalizedPerson (name) VALUES ('Permanent Council');
INSERT INTO NormalizedPerson (name) VALUES ('Pierre Laforge');
INSERT INTO NormalizedPerson (name) VALUES ('Powers of Commissioners to Waco Indians');
INSERT INTO NormalizedPerson (name) VALUES ('President of the Consultation');
INSERT INTO NormalizedPerson (name) VALUES ('President of the Provisional Government of Texas');
INSERT INTO NormalizedPerson (name) VALUES ('Provincial Deputation');
INSERT INTO NormalizedPerson (name) VALUES ('Provisional Government');
INSERT INTO NormalizedPerson (name) VALUES ('Provisional Government of Texas');
INSERT INTO NormalizedPerson (name) VALUES ('Provisional Governor');
INSERT INTO NormalizedPerson (name) VALUES ('Public');
INSERT INTO NormalizedPerson (name) VALUES ('Rafae Llanos');
INSERT INTO NormalizedPerson (name) VALUES ('Raleigh');
INSERT INTO NormalizedPerson (name) VALUES ('Ramon Musquiz');
INSERT INTO NormalizedPerson (name) VALUES ('Residents of Texas');
INSERT INTO NormalizedPerson (name) VALUES ('Sam McCraw');
INSERT INTO NormalizedPerson (name) VALUES ('Secretary of Relations');
INSERT INTO NormalizedPerson (name) VALUES ('Seth Hunt');
INSERT INTO NormalizedPerson (name) VALUES ('Sheriff of Colony');
INSERT INTO NormalizedPerson (name) VALUES ('Sheriff of the Colony');
INSERT INTO NormalizedPerson (name) VALUES ('State Congress');
INSERT INTO NormalizedPerson (name) VALUES ('State of Kentucky');
INSERT INTO NormalizedPerson (name) VALUES ('State of Missouri');
INSERT INTO NormalizedPerson (name) VALUES ('Texas Army');
INSERT INTO NormalizedPerson (name) VALUES ('Texas Gazette');
INSERT INTO NormalizedPerson (name) VALUES ('Unknown');
INSERT INTO NormalizedPerson (name) VALUES ('Unknown');
INSERT INTO NormalizedPerson (name) VALUES ('Unsent');
INSERT INTO NormalizedPerson (name) VALUES ('U. S. Consul');
INSERT INTO NormalizedPerson (name) VALUES ('Volunteers at Bexar');
INSERT INTO NormalizedPerson (name) VALUES ('Warren Buford');
INSERT INTO NormalizedPerson (name) VALUES ('W D C Hall');
INSERT INTO NormalizedPerson (name) VALUES ('Zeno Phillips');
