                INSERT INTO NormalizedPerson (name) VALUES ('Abiel P Mead');
                INSERT INTO NormalizedPerson (name) VALUES ('Abraham Armstrong');
                INSERT INTO NormalizedPerson (name) VALUES ('A C Ainsworth');
                INSERT INTO NormalizedPerson (name) VALUES ('Adam Trinno');
                INSERT INTO NormalizedPerson (name) VALUES ('A Holdridge');
                INSERT INTO NormalizedPerson (name) VALUES ('Alijah Hull');
                INSERT INTO NormalizedPerson (name) VALUES ('A. McNair');
                INSERT INTO NormalizedPerson (name) VALUES ('Amos Rawls');
                INSERT INTO NormalizedPerson (name) VALUES ('Archibald Austin');
                INSERT INTO NormalizedPerson (name) VALUES ('Armistead Moore');
                INSERT INTO NormalizedPerson (name) VALUES ('A. Sampyrac');
                INSERT INTO NormalizedPerson (name) VALUES ('Bank of St Louis ');
                INSERT INTO NormalizedPerson (name) VALUES ('Ben J. Shakelford');
                INSERT INTO NormalizedPerson (name) VALUES ('Bogart');
                INSERT INTO NormalizedPerson (name) VALUES ('Bryrd Lockhart, Green De Witt, James Kerr');
                INSERT INTO NormalizedPerson (name) VALUES ('B T Jacques');
                INSERT INTO NormalizedPerson (name) VALUES ('C. Dyer,David Hamilton, William Spence, Joseph Newman, Nicholas Whitehead, John Clark, Thomas J. Rabb, Charles Henderson, Moses Windham, William Luce, Alexander Brown, ANdrew Rabb, John Ingram, Gabriel Straw Snyder, Andrew Rabb');
                INSERT INTO NormalizedPerson (name) VALUES ('Churchill Fulshear');
                INSERT INTO NormalizedPerson (name) VALUES ('Colonists');
                INSERT INTO NormalizedPerson (name) VALUES ('Dan Bissell');
                INSERT INTO NormalizedPerson (name) VALUES ('Darius Shaw');
                INSERT INTO NormalizedPerson (name) VALUES ('D. Crozer');
                INSERT INTO NormalizedPerson (name) VALUES ('Dexter C. Gunn and David Bucklin');
                INSERT INTO NormalizedPerson (name) VALUES ('Duff Chadwell');
                INSERT INTO NormalizedPerson (name) VALUES ('Ebel Miton,Ranford Berry, F. Smith, Wm. H Smith, John Teal, and Thomas ?');
                INSERT INTO NormalizedPerson (name) VALUES ('Edwin L Pettit');
                INSERT INTO NormalizedPerson (name) VALUES ('Enoch Brenson');
                INSERT INTO NormalizedPerson (name) VALUES ('Faris and White');
                INSERT INTO NormalizedPerson (name) VALUES ('Freeman Pettus');
                INSERT INTO NormalizedPerson (name) VALUES ('G B Cotten');
                INSERT INTO NormalizedPerson (name) VALUES ('Geo Huff');
                INSERT INTO NormalizedPerson (name) VALUES ('George S. Pentacost');
                INSERT INTO NormalizedPerson (name) VALUES ('Gideon Blackburn');
                INSERT INTO NormalizedPerson (name) VALUES ('G. Pearce');
                INSERT INTO NormalizedPerson (name) VALUES ('Green De Witt');
                INSERT INTO NormalizedPerson (name) VALUES ('Hamiton N Yett and Alexr Calvit');
                INSERT INTO NormalizedPerson (name) VALUES ('Hanson Alsbury');
                INSERT INTO NormalizedPerson (name) VALUES ('Henry Dodge');
                INSERT INTO NormalizedPerson (name) VALUES ('Henry Morse');
                INSERT INTO NormalizedPerson (name) VALUES ('Henry W. Munson');
                INSERT INTO NormalizedPerson (name) VALUES ('H. H. League, James C. Ludlow, Elias Wightman, Richard Matson.');
                INSERT INTO NormalizedPerson (name) VALUES ('Horatio Alsberry');
                INSERT INTO NormalizedPerson (name) VALUES ('Ireston C. Devan');
                INSERT INTO NormalizedPerson (name) VALUES ('Isaac C. Oglem');
                INSERT INTO NormalizedPerson (name) VALUES ('Isaac Jesses');
                INSERT INTO NormalizedPerson (name) VALUES ('Jacob Betts');
                INSERT INTO NormalizedPerson (name) VALUES ('J. Blair');
                INSERT INTO NormalizedPerson (name) VALUES ('J. Botts');
                INSERT INTO NormalizedPerson (name) VALUES ('J Child');
                INSERT INTO NormalizedPerson (name) VALUES ('J. Child');
                INSERT INTO NormalizedPerson (name) VALUES ('J. D. Bludworth');
                INSERT INTO NormalizedPerson (name) VALUES ('J. F. Buchetti');
                INSERT INTO NormalizedPerson (name) VALUES ('J G Wright');
                INSERT INTO NormalizedPerson (name) VALUES ('J. L. Dumanday ');
                INSERT INTO NormalizedPerson (name) VALUES ('J. L Phillips');
                INSERT INTO NormalizedPerson (name) VALUES ('John P Sheldon');
                INSERT INTO NormalizedPerson (name) VALUES ('John T Criswell');
                INSERT INTO NormalizedPerson (name) VALUES ('Joshua Marsh');
                INSERT INTO NormalizedPerson (name) VALUES ('J R Bedford');
                INSERT INTO NormalizedPerson (name) VALUES ('J. Sargeant');
                INSERT INTO NormalizedPerson (name) VALUES ('Juan Francicso Buchetti');
                INSERT INTO NormalizedPerson (name) VALUES ('Knight and White');
                INSERT INTO NormalizedPerson (name) VALUES ('Leonidas W. Baker');
                INSERT INTO NormalizedPerson (name) VALUES ('Louisiana Advertiser');
                INSERT INTO NormalizedPerson (name) VALUES ('Martin F Maher and Company');
                INSERT INTO NormalizedPerson (name) VALUES ('Mateo Ahumada');
                INSERT INTO NormalizedPerson (name) VALUES ('Matthew G White');
                INSERT INTO NormalizedPerson (name) VALUES ('McCoy and Scanlan');
                INSERT INTO NormalizedPerson (name) VALUES ('Missouri Legislature');
                INSERT INTO NormalizedPerson (name) VALUES ('M. Slocum');
                INSERT INTO NormalizedPerson (name) VALUES ('Pascal Detchemendy');
                INSERT INTO NormalizedPerson (name) VALUES ('Patick and Lindsay Clopper');
                INSERT INTO NormalizedPerson (name) VALUES ('Paul Dimmitt');
                INSERT INTO NormalizedPerson (name) VALUES ('Pierre Delassus De Luziere');
                INSERT INTO NormalizedPerson (name) VALUES ('P S le Hicks');
                INSERT INTO NormalizedPerson (name) VALUES ('P. S. Slocum');
                INSERT INTO NormalizedPerson (name) VALUES ('Randall Jones');
                INSERT INTO NormalizedPerson (name) VALUES ('Robert Leftwich or Haden Edwards');
                INSERT INTO NormalizedPerson (name) VALUES ('Roswell Mills');
                INSERT INTO NormalizedPerson (name) VALUES ('R. P. Guyard');
                INSERT INTO NormalizedPerson (name) VALUES ('Schooner Lively');
                INSERT INTO NormalizedPerson (name) VALUES ('Seth Hunt');
                INSERT INTO NormalizedPerson (name) VALUES ('S Hatch');
                INSERT INTO NormalizedPerson (name) VALUES ('S. T. Angier');
                INSERT INTO NormalizedPerson (name) VALUES ('Sylvester Murphy');
                INSERT INTO NormalizedPerson (name) VALUES ('Sylvester Murphy ');
                INSERT INTO NormalizedPerson (name) VALUES ('Tacitus Clay');
                INSERT INTO NormalizedPerson (name) VALUES ('T. Farelly');
                INSERT INTO NormalizedPerson (name) VALUES ('T. [or J.] Reilly');
                INSERT INTO NormalizedPerson (name) VALUES ('Unknown');
                INSERT INTO NormalizedPerson (name) VALUES ('Various New Orleans firms');
                INSERT INTO NormalizedPerson (name) VALUES ('Washington Hotel');
                INSERT INTO NormalizedPerson (name) VALUES ('Wyatt Hanks');
                INSERT INTO NormalizedPerson (name) VALUES ('Zenas Priest');
